const kit=window.WDC_COMPONENTS;
const app=document.querySelector('#app');
const defaults={enabled:false,frequency:'Daily',day:'Monday',monthDay:'1',time:'02:00',zone:'Africa/Lagos',keep:'10',scope:'Records + uploaded files',notify:'Failures only'};
let savedSchedule={...defaults};
const state={empty:false,query:'',status:'All statuses',per:10,schedule:{...defaults},selected:[]};
const rows=[{name:'Studio archive',date:'6 Oct 2026 · 09:00',scope:'Records + uploaded files',size:'128 MB',status:'Verified'},{name:'Before studio update',date:'5 Oct 2026 · 16:42',scope:'Records only',size:'2.4 MB',status:'Verified'},{name:'Studio archive',date:'4 Oct 2026 · 09:00',scope:'Records + uploaded files',size:'—',status:'Failed'}];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=n=>kit.icons[n]||'';
const btn=(text,action,primary=false,extra='')=>`<button class="ad__btn ${primary?'ad__btn--primary':''}" data-action="${action}" ${extra}>${text}</button>`;
const close=()=>`<button class="ad__iconButton" data-action="close" aria-label="Close dialog">${icon('X')}</button>`;
const panel=(title,body)=>kit.panel.replace('__TITLE__',esc(title)).replace('__CONTENT__',`<div class="bk-body">${body}</div>`);
const dirty=()=>JSON.stringify(state.schedule)!==JSON.stringify(savedSchedule);
const bulkBar=()=>state.selected.length?`<div class="adBulk" role="region" aria-label="Selected backups"><b class="adBulk__n">${state.selected.length} selected</b><button class="ad__btn adBulk__btn" data-action="bulk:validate">${icon('CircleCheck')}<span class="adBulk__t">Validate</span><span class="ad__sr">Validate selected backups</span></button><button class="ad__btn adBulk__btn" data-action="bulk:download">${icon('Download')}<span class="adBulk__t">Download</span><span class="ad__sr">Download selected backups</span></button><button class="ad__btn adBulk__btn is-danger" data-action="bulk:trash">${icon('X')}<span class="adBulk__t">Move to Trash</span><span class="ad__sr">Move selected backups to Trash</span></button><button class="ad__iconButton adBulk__x" data-action="bulk-clear" aria-label="Clear selection">${icon('X')}</button></div>`:'';
function schedulePanel(){const s=state.schedule;const pick=(label,key,hint='')=>`<div class="bk-setting"><b>${label}</b>${btn(esc(s[key])+icon('ChevronRight'),'schedule-pick:'+key,false,'aria-haspopup="dialog" aria-label="'+label+': '+esc(s[key])+'"')}${hint?`<small>${hint}</small>`:''}</div>`;return panel('Automatic backups',`<div class="bk-auto-head"><div><b>Back up on a schedule</b><p>Create archives automatically, with retries and verification.</p></div><button class="bk-switch" role="switch" aria-checked="${s.enabled}" aria-label="Enable automatic backups in design preview" data-action="schedule-toggle"><span></span></button></div><div class="bk-schedule-grid">${pick('Frequency','frequency')}${s.frequency==='Weekly'?pick('Day of week','day'):s.frequency==='Monthly'?pick('Day of month','monthDay','Use the last day for months of different lengths.'):''}${pick('Run time','time')}${pick('Time zone','zone')}${pick('Include','scope')}${pick('Backups to keep','keep','Never remove the last verified backup or a restore safety checkpoint in use.')}${pick('Email me','notify','Your own notification preference. Other team members choose theirs.')}</div><div class="bk-notice"><b>${s.enabled?'Automatic backups selected · setup required':'Automatic backups are off'}</b><p>${s.enabled?`${s.frequency} at ${s.time} (${s.zone}). Keep the latest ${s.keep} scheduled backups.`:'Manual backups remain available.'} Production will show the next run and last job result only after the scheduler is configured.</p></div><div class="bk-save"><span>${dirty()?'Unsaved changes':'No unsaved changes'} · Preview only</span><div class="bk-actions">${btn('Discard','schedule-discard',false,dirty()?'':'disabled')}${btn('Save changes','schedule-save',true,dirty()?'':'disabled')}</div></div>`);}
function render(){
 document.querySelector('.bk-row-menu')?.remove();
 const list=state.empty?[]:rows.filter(r=>(state.status==='All statuses'||r.status===state.status)&&r.name.toLowerCase().includes(state.query.toLowerCase()));
 const history=state.empty?`<div class="bk-empty">${icon('FolderKanban')}<h3>Your first backup starts here</h3><p>Keep a recoverable copy of your studio records. Choose what to include before creating it.</p>${btn('Create backup','create',true)}</div>`:`<div class="bk-toolbar"><label class="bk-search"><span class="ad__sr">Search backups</span>${icon('Search')}<input type="search" id="backup-search" placeholder="Search backups" value="${esc(state.query)}"></label>${btn(esc(state.status)+' '+icon('ChevronRight'),'filter')}${btn('Import archive','import')}</div><div class="ad__scroll" tabindex="0" aria-label="Backup history. Scroll horizontally for all columns" data-lenis-prevent><table class="ad__t bk-table"><thead><tr><th><label class="bk-select"><input type="checkbox" class="adRowPickAll" aria-label="Select visible backups" ${state.selected.length===list.length&&list.length?'checked':''}>Backup</label></th><th>Includes</th><th>Created</th><th>Size</th><th>Result</th><th><span class="ad__sr">Actions</span></th></tr></thead><tbody>${list.map(r=>`<tr><td><div class="bk-select"><input type="checkbox" class="adRowPick" value="${rows.indexOf(r)}" aria-label="Select ${r.name}, ${r.date}" ${state.selected.includes(rows.indexOf(r))?'checked':''}><div><b>${r.name}</b><small>Illustrative archive</small></div></div></td><td>${r.scope}</td><td>${r.date}</td><td class="ad__num">${r.size}</td><td><span class="ad__pill ad__pill--${r.status==='Verified'?'good':'bad'}">${r.status}</span></td><td><button class="ad__rm" aria-haspopup="menu" data-action="row:${rows.indexOf(r)}" aria-label="Options for ${r.name}, ${r.date}">${icon('MoreHorizontal')}</button></td></tr>`).join('')||`<tr><td colspan="6">No backups match. ${btn('Clear filters','clear')}</td></tr>`}</tbody></table></div><div class="bk-pager">${kit.backupPager.replace('1–3 of 3 backups',`${list.length?'1':'0'}–${list.length} of ${list.length} backups`).replaceAll('10 per page',state.per+' per page').replace('Rows per page, 10','Rows per page, '+state.per)}</div>`;
 const content=`<a class="bk-settings-link" href="#" data-action="settings">${icon('ArrowLeft')} Settings / System</a><header class="bk-head"><div><h1>Backup and restore</h1><p>A copy you can come back to. A clear path to recovery.</p></div>${btn(icon('Plus')+' Create backup','create',true)}</header><div class="bk-stack"><div class="bk-intro">${panel('Latest backup',state.empty?`<h3>No verified backup yet</h3><p>Create your first archive to keep a recoverable copy of the studio.</p>${btn('Create backup','create',true)}`:`<span class="ad__pill ad__pill--good">Verified · example</span><h3>Studio archive</h3><p>Records and uploaded files. Checksums and archive structure checked.</p><div class="bk-actions">${btn('View archive','details')}${btn('Download','download')}</div><dl class="bk-definition"><div><dt>Created</dt><dd>6 Oct 2026 · 09:00</dd></div><div><dt>Archive size</dt><dd>128 MB</dd></div></dl>`)}${panel('Restore an archive',`<p>Review what will change before you restore. A safety backup is created first.</p><ol class="bk-list"><li>Choose and validate an archive</li><li>Review the changes and exclusions</li><li>Confirm, restore and verify</li></ol>${btn('Choose archive','import')}<p class="bk-small">Owner access required. Existing payments and delivered messages cannot be undone.</p>`)}</div>${schedulePanel()}${panel('Backup history',bulkBar()+history)}${panel('What is protected',`<div class="bk-coverage"><div><b>Included in an application archive</b><p>Supported studio records, settings and their relationships. Uploaded file contents only when you choose to include them.</p></div><div><b>Kept separately</b><p>Passwords, sessions, API keys and provider accounts. Full disaster recovery also needs database and storage provider backups.</p></div></div><div class="bk-actions">${btn('Recovery guide','guide')}${btn('Retention & schedules','retention')}</div>`)}</div>`;
 app.innerHTML=kit.shell.replace('__PAGE__',content);
 app.querySelector('.ad__topTitle').textContent='Settings';
 const all=app.querySelector('.adRowPickAll');if(all)all.indeterminate=state.selected.length>0&&state.selected.length<list.length;
 app.querySelectorAll('.ad__link').forEach(a=>{a.classList.remove('is-on');a.removeAttribute('aria-current');if(a.getAttribute('href')==='/admin/settings'){a.classList.add('is-on');a.setAttribute('aria-current','page');}a.setAttribute('href','#');a.dataset.action='settings';});
 app.querySelector('.ad__topMenu').dataset.action='drawer';
 app.querySelector('.ad__themeBtn').dataset.action='theme';
 app.querySelector('[data-tour="sidebar-pin"]')?.setAttribute('data-action','pin');
}
function toast(text){const el=document.querySelector('#announcement');el.textContent=text;el.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('visible'),5000);}
function dialog(title,body,actions=''){document.querySelector('.bk-row-menu')?.remove();document.querySelectorAll('dialog').forEach(d=>d.close());const template=document.createElement('template');template.innerHTML=kit.backupDialog.replace('__TITLE__',esc(title)).replace('__CONTENT__',body+(actions?`<div class="bk-dialog-actions">${actions}</div>`:''));const d=template.content.firstElementChild;d.querySelector('.addlg__x').dataset.action='close';document.body.append(d);d.addEventListener('close',()=>d.remove());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});d.showModal();d.focus({preventScroll:true});}
function rowMenu(index,target){const previous=document.querySelector('.bk-row-menu');const same=previous?.dataset.row===index;previous?.remove();if(same)return;const r=rows[Number(index)];const menu=document.createElement('div');menu.className='ad__rmList bk-row-menu';menu.dataset.row=index;menu.setAttribute('role','menu');menu.setAttribute('aria-label','Actions for '+r.name);const item=(label,action,glyph,disabled=false,danger=false)=>`<button type="button" role="menuitem" class="ad__rmItem ${danger?'is-danger':''}" data-action="${action}" ${disabled?'disabled':''}>${icon(glyph)||'<span class="ad__rmGap"></span>'}${label}</button>`;menu.innerHTML=item('View details','details','FolderKanban')+item('Download archive','download','Download',r.status==='Failed')+item('Validate archive','validate','CircleCheck')+item('Review restore','review','Clock',r.status==='Failed')+item('Move to Trash','trash','Archive',false,true);document.body.append(menu);const place=()=>{const b=target.getBoundingClientRect();if(b.bottom<0||b.top>innerHeight){menu.remove();return;}const height=menu.offsetHeight;menu.style.left=Math.max(8,Math.min(b.right-232,innerWidth-240))+'px';menu.style.top=Math.max(8,b.bottom+6+height>innerHeight-8?b.top-height-6:b.bottom+6)+'px';};menu.style.width='232px';menu.style.maxHeight='calc(100dvh - 16px)';menu.style.overflowY='auto';place();menu.querySelector('button:not([disabled])')?.focus();const outside=e=>{if(!menu.contains(e.target)&&!target.contains(e.target))menu.remove();};const keys=e=>{const items=[...menu.querySelectorAll('button:not([disabled])')];let i=items.indexOf(document.activeElement);if(e.key==='Escape'){menu.remove();target.focus();}else if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();i=e.key==='Home'?0:e.key==='End'?items.length-1:(i+(e.key==='ArrowDown'?1:-1)+items.length)%items.length;items[i].focus();}};const observer=new MutationObserver(()=>{if(!menu.isConnected){document.removeEventListener('pointerdown',outside);menu.removeEventListener('keydown',keys);window.removeEventListener('resize',place);document.removeEventListener('scroll',place,true);observer.disconnect();}});observer.observe(document.body,{childList:true});document.addEventListener('pointerdown',outside);menu.addEventListener('keydown',keys);window.addEventListener('resize',place);document.addEventListener('scroll',place,true);}
document.addEventListener('click',e=>{
 const target=e.target.closest('[data-action],a[href^="#backup-size:"],#empty,#theme');if(!target)return;e.preventDefault();
 if(target.id==='theme'||target.dataset.action==='theme'){document.documentElement.classList.toggle('dark');document.querySelector('#theme').textContent=document.documentElement.classList.contains('dark')?'Light theme':'Dark theme';return;}
 if(target.id==='empty'){state.empty=!state.empty;state.selected=[];target.textContent=state.empty?'Show archive history':'Show empty state';render();return;}
 if(target.matches('a[href^="#backup-size:"]')){state.per=Number(target.getAttribute('href').split(':')[1]);render();return;}
 const [action,value]=target.dataset.action.split(':');
 if(action==='bulk-clear'){state.selected=[];render();return;}
 if(action==='bulk'){const chosen=state.selected.map(i=>rows[i]);dialog(value==='trash'?'Move selected backups to Trash?':value==='download'?'Download selected backups':'Validate selected backups',`<p>${chosen.length} selected. Review each archive before continuing.</p><ul class="bk-list">${chosen.map(r=>`<li>${r.name} · ${r.date}${value==='download'&&r.status==='Failed'?' — unavailable: creation failed':''}</li>`).join('')}</ul><p>Design preview only. No files will be changed or downloaded. Production will report success or failure per archive.</p>`,btn('Cancel','close')+btn('Preview selection result','bulk-done',true));return;}
 if(action==='bulk-done'){target.closest('dialog').close();state.selected=[];render();toast('Preview reviewed. No backup jobs or file operations ran.');return;}
 if(action==='schedule-toggle'){state.schedule.enabled=!state.schedule.enabled;render();return;}
 if(action==='schedule-pick'){const choices={frequency:['Daily','Weekly','Monthly'],day:['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],monthDay:['1','7','14','21','Last day'],time:['00:00','01:00','02:00','03:00','04:00','06:00','12:00','18:00','22:00'],zone:['Africa/Lagos','UTC','Europe/London','America/New_York'],scope:['Studio records','Records + uploaded files'],keep:['3','5','7','10','14','30'],notify:['Failures only','Every completed backup','Off']};dialog('Choose '+({monthDay:'day of month',keep:'backups to keep',notify:'notifications',zone:'time zone',time:'run time',scope:'scope'}[value]||value),`<div class="bk-menu">${choices[value].map(choice=>btn(choice,'schedule-set:'+value,false,'data-value="'+esc(choice)+'"')).join('')}</div>`);return;}
 if(action==='schedule-set'){state.schedule[value]=target.dataset.value;target.closest('dialog').close();render();return;}
 if(action==='schedule-discard'){state.schedule={...savedSchedule};render();toast('Preview changes discarded.');return;}
 if(action==='schedule-save'){savedSchedule={...state.schedule};render();toast('Saved in this preview only. No production backup schedule was created.');return;}
 if(action==='close'){target.closest('dialog').close();return;}
 if(action==='clear'){state.query='';state.status='All statuses';render();return;}
 if(action==='filter'){dialog('Filter backups',`<div class="bk-menu">${['All statuses','Verified','Failed'].map(s=>btn(s,'status:'+s)).join('')}</div>`);return;}
 if(action==='status'){state.status=value;state.selected=[];target.closest('dialog').close();render();return;}
 if(action==='create'){dialog('Create backup',`<p>Choose the scope. This preview creates no files.</p><label class="bk-option"><input type="radio" name="scope" checked><span><b>Studio records</b><small>Supported records, settings and relationships. Smaller archive; no uploaded file contents.</small></span></label><label class="bk-option"><input type="radio" name="scope"><span><b>Studio records + uploaded files</b><small>Includes original files where available. Takes longer and uses more storage.</small></span></label><div class="bk-notice"><b>Credentials stay private</b><p>Passwords, sessions, invitation links and environment keys are excluded.</p></div>`,btn('Cancel','close')+btn('Preview creation','created',true));return;}
 if(action==='created'){target.closest('dialog').close();toast('Preview only. Production will queue creation, then verify the archive before marking it ready.');return;}
 if(action==='row'){rowMenu(value,target);return;}
 if(action==='details'){dialog('Archive details',`<span class="ad__pill ad__pill--good">Verified · example</span><dl class="bk-definition"><div><dt>Format</dt><dd>WDC archive v1</dd></div><div><dt>Created</dt><dd>6 Oct 2026 · 09:00</dd></div><div><dt>Scope</dt><dd>Records + files</dd></div><div><dt>Size</dt><dd>128 MB</dd></div></dl><div class="bk-notice"><b>Verification</b><p>Example state: structure, relationships and file checksums passed. Actual checks are not running in this preview.</p></div><p>Passwords, sessions and provider secrets are excluded.</p>`,btn('Close','close')+btn('Review restore','review',true));return;}
 if(action==='import'){dialog('Choose an archive',`${kit.archiveDrop}<p>Your file is not uploaded in this preview.</p><div class="bk-notice"><b>Validation comes first</b><p>Check format, compatibility, integrity and missing files before allowing any restore.</p></div><p>For design review, continue with the illustrative archive.</p>`,btn('Cancel','close')+btn('Preview validation','validate',true));return;}
 if(action==='validate'){dialog('Archive validation',`<span class="ad__pill ad__pill--good">Example: validation passed</span><ul class="bk-list"><li>Supported archive format</li><li>Compatible application schema</li><li>Checksums and relationships intact</li><li>Required files available</li></ul><p>These illustrate the checks; no uploaded file has been inspected.</p>`,btn('Close','close')+btn('Review restore','review',true));return;}
 if(action==='review'){dialog('Review restore',`<p>Illustrative preview for Studio archive. Real counts will come from validation.</p><div class="ad__scroll" tabindex="0" aria-label="Restore changes"><table class="ad__t"><thead><tr><th>Scope</th><th>Change</th></tr></thead><tbody><tr><td>Studio records</td><td>Replace supported records with the archive version</td></tr><tr><td>Uploaded files</td><td>Restore verified archived files</td></tr><tr><td>Your owner account</td><td>Preserved</td></tr><tr><td>External services</td><td>Not restored</td></tr></tbody></table></div><div class="bk-notice"><b>A safety checkpoint is required</b><p>Create and verify a backup of current data before restoring. Pause conflicting writes and outbound messages.</p></div><p>Restoring does not reverse Paystack charges, Cal bookings or emails already delivered.</p><label class="bk-check"><input type="checkbox" id="restore-understand"><span>I understand that supported current records will be replaced.</span></label>`,btn('Go back','import')+btn('Preview restore','restore',true,'disabled id="restore-submit"'));return;}
 if(action==='restore'){target.closest('dialog').close();toast('Design preview only. No restore has run. Production must create a verified safety checkpoint first.');return;}
 if(action==='download'){toast('Preview only. Real downloads will require fresh owner authorization and a private, short-lived link.');return;}
 if(action==='trash'){dialog('Move this archive to Trash?',`<p>This preview will not remove files. Production keeps trashed archives recoverable until permanent deletion is confirmed.</p>`,btn('Keep archive','close')+btn('Preview Move to Trash','trashed',true));return;}
 if(action==='trashed'){target.closest('dialog').close();toast('Preview only. No archive was removed.');return;}
 if(action==='retention'){dialog('Retention and schedules',`<p>Keep the latest verified recovery point. Automatic schedules need a durable job runner before they can be enabled.</p><div class="bk-menu">${btn('30 days · proposed retention','retention-choice')}</div><div class="bk-notice"><b>Automatic backups: setup required</b><p>Disabled until scheduling, storage limits and retry behavior are verified.</p></div><p>Completion and failure notifications will be personal preferences.</p>`,btn('Close','close'));return;}
 if(action==='retention-choice'){dialog('Choose retention',`<div class="bk-menu">${['30 days','60 days','90 days'].map(s=>btn(s,'retention-preview:'+s)).join('')}</div>`);return;}
 if(action==='retention-preview'){target.closest('dialog').close();toast(value+' shown for design review. No setting saved.');return;}
 if(action==='guide'){dialog('Recovery guide',`<ol class="bk-list"><li>Keep a verified application archive.</li><li>Maintain database-provider and original-file backups separately.</li><li>Recover deployment and secrets through their secured providers.</li><li>Validate on an isolated environment first.</li><li>Restore with a safety checkpoint, then verify before reopening writes.</li></ol><p>An application archive is one part of disaster recovery.</p>`,btn('Close','close'));return;}
 if(action==='drawer'){document.querySelector('.ad__shell')?.classList.toggle('is-drawerOpen');return;}
 if(action==='pin'){document.querySelector('.ad__shell')?.classList.toggle('is-collapsed');return;}
 toast('Backup and restore design preview. Other Settings pages are outside this artifact.');
});
document.addEventListener('input',e=>{if(e.target.id==='backup-search'){const start=e.target.selectionStart;state.query=e.target.value;state.selected=[];render();const input=document.querySelector('#backup-search');input.focus();input.setSelectionRange(start,start);}});
document.addEventListener('change',e=>{if(e.target.id==='restore-understand')document.querySelector('#restore-submit').disabled=!e.target.checked;});
render();
document.addEventListener('change',e=>{if(e.target.matches('.bk-table .adRowPick')){const index=Number(e.target.value);state.selected=e.target.checked?[...new Set([...state.selected,index])]:state.selected.filter(i=>i!==index);render();}else if(e.target.matches('.bk-table .adRowPickAll')){state.selected=e.target.checked?[...document.querySelectorAll('.bk-table .adRowPick')].map(el=>Number(el.value)):[];render();}else if(e.target.id==='archive-file'){const file=e.target.files?.[0];const label=e.target.closest('.adFileDrop')?.querySelector('.adFileDrop__lead');if(file&&label)label.textContent=file.name+' · selected locally, not uploaded';}});
document.addEventListener('pointerdown',event=>{document.querySelectorAll('.ad__perPage[open]').forEach(details=>{if(!details.contains(event.target))details.open=false;});});
document.addEventListener('keydown',event=>{if(event.key==='Escape')document.querySelectorAll('.ad__perPage[open]').forEach(details=>{details.open=false;details.querySelector('summary').focus();});});
