const app = document.querySelector('#app');
const state = { screen: 'booking', step: 0, date: 12, time: '', view: 'month', tab: 'Calendar', selected: 0, error: false, changes: 0, name: '', email: '', notes: '' };
const meetings = [
  { title: 'Project conversation', client: 'Sample client · new enquiry', day: 12, time: '10:00', status: 'Confirmed' },
  { title: 'Brand direction review', client: 'Sample client · branding project', day: 14, time: '14:00', status: 'Awaiting approval' },
  { title: 'Project check-in', client: 'Sample client · website project', day: 16, time: '11:30', status: 'Confirmed' }
];
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const components = window.WDC_COMPONENTS;
state.month = 9; state.year = 2026; state.setting = 'Availability';
state.reminders = { enabled: true, day: true, hour: true, owner: true };
const monthNames = ['January','February','March','April','May','June','July','August','September','October','November','December'];
const period = () => `${monthNames[state.month]} ${state.year}`;
let savedReminders = {...state.reminders};
const dateLabel = () => `${monthNames[state.month]} ${state.date}, ${state.year}`;
const icon = name => components.icons[name] || '';
const button = (label, action, cls = '', extra = '') => {
  const glyph = { '‹':'ChevronLeft', '›':'ChevronRight', '×':'X', '+':'Plus' }[label];
  const leading = {'Schedule a meeting':'Plus','View meeting':'CalendarClock','Copy booking link':'Link','Join meeting':'Video','Reschedule':'CalendarClock','Save changes':'Check','Add a date override':'Plus'}[label];
  const kit = glyph ? 'ad__iconButton' : cls.includes('public-') || cls==='day' || cls.startsWith('day ') ? '' : 'ad__btn';
  return `<button class="${kit} ${cls==='primary'?'ad__btn--primary':cls}" data-action="${action}" ${extra}>${glyph?icon(glyph):(leading?icon(leading):'')+label}</button>`;
};
function toast(message) { const box = document.querySelector('#announcement'); box.textContent = message; box.classList.add('visible'); clearTimeout(toast.timer); toast.timer = setTimeout(() => box.classList.remove('visible'), 3500); }
function month(booking = false) {
  const offset=(new Date(state.year,state.month,1).getDay()+6)%7;
  const length=new Date(state.year,state.month+1,0).getDate();
  return `<div class="month-toolbar">${button('‹','previous-month','','aria-label="Previous month"')}${button(period(),'pick-period','period-button','aria-label="Choose month and year" aria-haspopup="dialog"')}${button('›','next-month','','aria-label="Next month"')}</div><div class="month">${['M','T','W','T','F','S','S'].map((d,i)=>`<span class="weekday" aria-label="${['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][i]}">${d}</span>`).join('')}${'<span></span>'.repeat(offset)}${Array.from({length},(_,i)=> { const d=i+1; const dt=new Date(state.year,state.month,d); const available = dt>=new Date(2026,9,8)&&![0,6].includes(dt.getDay()); return button(d,`date:${d}`,`day ${available?'available':''} ${state.date===d?'selected':''}`,`aria-label="${monthNames[state.month]} ${d}, ${state.year}" aria-pressed="${state.date===d}" ${booking&&!available?'disabled':''}`); }).join('')}</div>`;
}
function pickPeriod() {
 const dialog=document.createElement('dialog');dialog.className='ad period-dialog';dialog.setAttribute('aria-label','Choose month and year');
 dialog.innerHTML=`<div class="picker-head"><h2>Choose month and year</h2>${button('×','close-picker','','aria-label="Close month picker"')}</div><div class="picker-year">${button('‹','year-back','','aria-label="Previous year"')}<button id="picker-year" data-action="show-years" class="ad__btn" aria-label="Choose year">${state.year}</button>${button('›','year-next','','aria-label="Next year"')}</div><div class="month-options">${monthNames.map((m,i)=>button(m,`pick-month:${i}`,i===state.month?'selected':'',`aria-pressed="${i===state.month}"`)).join('')}</div>`;
 document.body.append(dialog);dialog.showModal();dialog.addEventListener('close',()=>dialog.remove());
}
function reminders() {
 return shell(`<header class="page-head"><div><h1>Reminders</h1><p>Help people arrive prepared, without sending the same message twice.</p></div>${button('View meetings','calendar','primary')}</header><div class="settings-layout"><nav class="settings-nav">${['Availability','Meeting types','Calendars & video','Reminders'].map(n=>button(n,`setting:${n}`,n==='Reminders'?'active':'')).join('')}</nav><div class="settings-body"><section class="panel settings-panel"><h2>Attendee reminders</h2><p>Proposed email policy. Clients can turn optional reminders off for their meeting.</p>${[['enabled','Enable optional email reminders'],['day','24 hours before'],['hour','1 hour before']].map(([k,label])=>`<div class="reminder-row"><div><strong>${label}</strong><p class="muted">${k==='enabled'?'Booking confirmations and changes remain separate.':'Skip this reminder if its scheduled time has already passed.'}</p></div><button class="reminder-switch" role="switch" aria-checked="${state.reminders[k]}" aria-label="${label}" data-action="reminder:${k}"><span></span></button></div>`).join('')}<p class="privacy-note">Times follow the meeting instant; email copy shows the recipient’s time zone.</p></section><section class="panel settings-panel"><h2>Your notifications</h2><div class="reminder-row"><div><strong>Notify me about new requests and changes</strong><p class="muted">A personal setting. Staff choose their own preferences.</p></div><button class="reminder-switch" role="switch" aria-checked="${state.reminders.owner}" aria-label="Notify me about requests and changes" data-action="reminder:owner"><span></span></button></div></section><section class="panel settings-panel"><h2>Delivery and recovery</h2><div class="reminder-row"><div><strong>Cal.com email reminders</strong><p class="muted">Configuration and delivery visibility must be verified on your account before launch.</p></div><span class="pill request">Setup required</span></div><p>Show “Managed by Cal.com” when the provider supplies no delivery receipt. Never call a configured reminder delivered.</p><div class="reminder-row"><div><strong>SMS and WhatsApp</strong><p class="muted">Off until pricing, channel support and consent are verified.</p></div><span class="pill cancelled">Off</span></div><p>Rescheduling replaces reminders for the old time. Cancellation, decline and opt-out suppress pending optional reminders.</p>${button('Preview failed delivery','reminder-failure')}</section><div class="save-bar"><p>${state.changes?`${state.changes} unsaved changes`:'No unsaved changes'} · Preview only</p><div class="button-row">${button('Discard','discard')}${button('Save changes','save','primary',state.changes?'':'disabled')}</div></div></div></div>`,true);
}
function booking() {
  const steps = ['Meeting','Date & time','Your details','Review'];
  let content = '';
  if(state.step===0) content = `<h2>Let’s talk about your project</h2><p class="muted">A little time together to understand what you have in mind.</p><button class="choice selected" data-action="next"><span class="choices-icon" aria-hidden="true">↗</span><span class="choice-main"><b>Project conversation</b><small>30 minutes · Video call · No charge</small></span><span aria-hidden="true">→</span></button><div class="notice"><strong>Prefer to write it down?</strong>Our project enquiry form remains available.</div>${button('Tell us about your project','contact','public-secondary')}`;
  if(state.step===1) content = `<h2>Choose a date and time</h2><p class="muted">Times are shown in your selected time zone.</p><div class="timezone">${button('Africa/Lagos · UTC+1 ▾','timezone')}</div>${state.error?`<div class="notice"><strong>We couldn’t load available times.</strong>Your details are safe. Try again or send a project enquiry.${button('Try again','retry')}</div>`:`<div class="date-time"><section class="calendar-section" aria-label="Choose date">${month(true)}</section><section><h3>${dateLabel()}</h3><p class="muted">30-minute conversations</p><div class="slots">${['09:00','10:00','11:30','14:00','15:00','16:00'].map(t=>button(t,`time:${t}`,state.time===t?'selected':'',`aria-pressed="${state.time===t}"`)).join('')}</div></section></div>`}<div class="preview-state">Preview a recovery state: ${button('Availability unavailable','error')}</div>`;
  if(state.step===2) content = `<h2>A little about you</h2><p class="muted">Help us arrive prepared.</p><form id="details"><div class="fields"><label>Your name<input name="name" autocomplete="name" required value="${esc(state.name)}"></label><label>Email address<input name="email" type="email" autocomplete="email" required value="${esc(state.email)}"></label><label class="wide">What would you like to discuss?<textarea name="notes">${esc(state.notes)}</textarea></label></div><p class="privacy-note">In the finished flow, we’ll use these details to manage your meeting. This preview sends nothing.</p></form>`;
  if(state.step===3) content = `<h2>Everything look right?</h2><p class="muted">Check the details before confirming.</p><dl class="review-list"><dt>Meeting</dt><dd>Project conversation</dd><dt>When</dt><dd>${dateLabel()} · ${state.time}</dd><dt>Time zone</dt><dd>Africa/Lagos · UTC+1</dd><dt>Duration</dt><dd>30 minutes</dd><dt>Location</dt><dd>Video call · link after confirmation</dd><dt>Your details</dt><dd>${esc(state.name)}<br>${esc(state.email)}</dd></dl>`;
  if(state.step===4) content = `<div class="success-mark" aria-hidden="true">✓</div><h2>You’re all set</h2><p>This is the proposed confirmation screen. No meeting was booked.</p><dl class="review-list"><dt>Conversation</dt><dd>${dateLabel()} · ${state.time}<br>Africa/Lagos · 30 minutes</dd><dt>Next steps</dt><dd>Your confirmation would include the video link and secure options to reschedule or cancel.</dd></dl><div class="button-row">${button('Manage meeting','manage','public-primary')}${button('Back to booking','restart','public-secondary')}</div>`;
  return `<header class="hero"><div class="hero-nav"><span class="wordmark">We Dig Creativity</span><span>Meet the studio</span></div><span class="eyebrow">A conversation is a good place to start</span><h1>Make time for your next idea.</h1><p>Choose a time that works for you. We’ll bring the questions, the attention and a fresh perspective.</p></header><main class="booking-wrap"><aside class="panel summary"><span class="pill">We Dig Creativity</span><h2>Project conversation</h2><p>Tell us where you are and where you want to go.</p><div class="figure">30 <small>min</small></div><div class="summary-row">Video conversation</div><div class="summary-details"><div class="summary-row">No charge for this first conversation</div><p class="muted">A clear next step, whether we work together now or later.</p></div></aside><section class="panel booking-body"><ol class="step-indicator">${steps.map((s,i)=>`<li class="${state.step===i?'current':''}" ${state.step===i?'aria-current="step"':''}>${i+1}. ${s}</li>`).join('')}</ol>${content}${state.step<4?`<div class="actions">${button(state.step?'Back':'Contact instead',state.step?'back':'contact','public-secondary')}${button(state.step===3?'Confirm sample booking':'Continue','next','public-primary',state.step===1&&!state.time?'disabled':'')}</div>`:''}</section></main>`;
}
function shell(content, settings = false) {
  return components.shell.replace('__PAGE__',components.demo + content);
}
function agenda(items) { return items.length?`<div class="agenda-list">${items.map(m=>`<button class="agenda-row" data-action="meeting:${meetings.indexOf(m)}"><span class="agenda-time">${m.time}<small>Oct ${m.day}</small></span><span class="agenda-copy"><b>${m.title}</b><small>${m.client}</small><span class="pill ${m.status==='Awaiting approval'?'request':m.status==='Cancelled'?'cancelled':''}">${m.status}</span></span><span aria-hidden="true">→</span></button>`).join('')}</div>`:`<div class="meeting-empty"><strong>Nothing here yet</strong><p>Meetings will appear here when their status changes.</p>${button('View calendar','calendar')}</div>`; }
function workspace() {
  const m = meetings[state.selected];
  const visibleMeetings = state.year===2026 && state.month===9 ? meetings : [];
  let calendar = agenda(visibleMeetings);
  if(state.tab==='Requests') calendar=agenda(meetings.filter(m=>m.status==='Awaiting approval'));
  else if(state.tab==='History') calendar=agenda(meetings.filter(m=>m.status==='Cancelled'));
  else if(state.view==='month') calendar=`<div class="calendar-table">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=>`<span class="weekday">${d}</span>`).join('')}${Array.from({length:Math.ceil(((new Date(state.year,state.month,1).getDay()+6)%7+new Date(state.year,state.month+1,0).getDate())/7)*7},(_,i)=>{const d=i-(new Date(state.year,state.month,1).getDay()+6)%7+1;return `<div class="calendar-cell ${d===5?'today':''}">${d>0&&d<=new Date(state.year,state.month+1,0).getDate()?`<span class="date-number">${d}</span>${visibleMeetings.filter(m=>m.day===d&&m.status!=='Cancelled').map(m=>`<button class="event ${m.status==='Awaiting approval'?'request':''}" data-action="meeting:${meetings.indexOf(m)}"><span>${m.time}</span><span>${m.title}</span></button>`).join('')}`:''}</div>`;}).join('')}</div><div class="mobile-calendar">${month()}<h3 class="upcoming-title">Upcoming meetings</h3>${agenda(visibleMeetings)}</div>`;
  else if(state.view==='week' && !visibleMeetings.length) calendar=agenda([]);
  else if(state.view==='week') calendar=`<div class="week-grid" role="region" aria-label="Week calendar. Scroll horizontally to view all days" tabindex="0" data-lenis-prevent><div class="week-row head"><div>Time</div>${[12,13,14,15,16].map(d=>`<div>Oct ${d}</div>`).join('')}</div>${['09:00','10:00','11:30','14:00'].map(t=>`<div class="week-row"><div class="time">${t}</div>${[12,13,14,15,16].map(d=>`<div>${meetings.filter(m=>m.day===d&&m.time===t).map(m=>`<button class="event" data-action="meeting:${meetings.indexOf(m)}">${m.title}</button>`).join('')}</div>`).join('')}</div>`).join('')}</div>`;
  else if(state.view==='day') calendar=agenda(visibleMeetings.filter(m=>m.day===state.date));
  return shell(`<header class="page-head"><div><h1>Meetings</h1><p>A little preparation. Better conversations.</p></div>${button('Schedule a meeting','booking','primary')}</header><section class="panel next-meeting"><div><span class="eyebrow">Next conversation · sample</span><h3>Project conversation</h3><span class="muted">Oct 12 · 30 minutes · Video call</span></div><span class="next-time">10:00</span><div class="button-row">${button('View meeting','meeting:0','primary')}${button('Copy booking link','copy')}</div></section><div class="tabs">${['Calendar','Requests','History'].map(t=>button(t,`tab:${t}`,state.tab===t?'active':'')).join('')}</div><div class="meeting-layout"><section class="panel calendar-panel"><div class="toolbar"><div class="toolbar-nav">${button('‹','previous-month','','aria-label="Previous period"')}${button(period(),'pick-period','period-button','aria-label="Choose month and year" aria-haspopup="dialog"')}${button('›','next-month','','aria-label="Next period"')}</div><div class="view-buttons">${['agenda','day','week','month'].map(v=>button(v[0].toUpperCase()+v.slice(1),`view:${v}`,state.view===v?'active':'',`data-view="${v}"`)).join('')}</div></div><h2 class="day-agenda-title">${state.tab==='Calendar'?'Your schedule':state.tab}</h2>${calendar}</section><aside class="panel detail" id="meeting-detail">${button('×','close-detail','close-detail','aria-label="Close meeting details"')}<span class="pill ${m.status==='Awaiting approval'?'request':''}">${m.status}</span><h2>${m.title}</h2><p class="muted">${m.client}</p><dl><dt>Date & time</dt><dd>October ${m.day}, 2026 · ${m.time}</dd><dt>Duration</dt><dd>30 minutes</dd><dt>Location</dt><dd>Video call</dd><dt>Project context</dt><dd>Discuss goals, scope and the best next step.</dd></dl><div class="detail-actions">${m.status==='Awaiting approval'?button('Approve sample request','approve','primary'):button('Join meeting','join','primary')}${button('Reschedule','reschedule')}${button('Cancel meeting','cancel')}</div><div class="timeline"><strong>Activity</strong><p>Sample booking received.<br>Confirmation state shown for design review.</p></div></aside></div>`);
}
function availability() { return shell(`<header class="page-head"><div><h1>Availability</h1><p>Your time, on your terms.</p></div>${button('View booking page','booking','primary')}</header><div class="settings-layout"><nav class="settings-nav">${['Availability','Meeting types','Calendars & video','Reminders'].map(n=>button(n,`setting:${n}`,n==='Availability'?'active':'')).join('')}</nav><div class="settings-body"><section class="panel settings-panel"><h2>Weekly hours</h2><p>Set your usual week. Date overrides take priority.</p><div class="timezone">${button('Africa/Lagos · UTC+1 ▾','timezone')}</div>${['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map((d,i)=>`<div class="hours-row"><strong>${d}</strong><div class="hours-control">${i<5?`${button('09:00',`hours:${d}`)}<span>to</span>${button('17:00',`hours:${d}`)}`:'Unavailable'}</div>${button('+',`period:${d}`,'plus',`aria-label="Add hours for ${d}"`)}</div>`).join('')}</section><section class="panel settings-panel"><h2>Date overrides</h2><p>Take a day off or add hours for a particular date.</p><div class="override"><div><strong>October 23, 2026</strong><p class="muted">Unavailable · Sample override</p></div>${button('Edit','override')}</div><p>${button('Add a date override','override')}</p></section><section class="panel settings-panel"><h2>Booking boundaries</h2><p>Proposed defaults; yours to adjust.</p><div class="button-row">${button('24 hours notice','boundary')}${button('15 minute buffers','boundary')}${button('30 day booking window','boundary')}</div></section><div class="save-bar"><p>${state.changes?`${state.changes} unsaved change${state.changes===1?'':'s'}`:'No unsaved changes'} · Preview only</p><div class="button-row">${button('Discard','discard')}${button('Save changes','save','primary',state.changes?'':'disabled')}</div></div></div></div>`,true); }
function render() {
 app.innerHTML=state.screen==='booking'?booking():state.screen==='meetings'?workspace():state.setting==='Reminders'?reminders():availability();
 document.querySelectorAll('[data-screen]').forEach(b=>b.setAttribute('aria-current',b.dataset.screen===state.screen));
 app.querySelectorAll('.page-head').forEach(el=>el.classList.add('ad__head'));
 app.querySelectorAll('.pill').forEach(el=>{el.classList.add('ad__pill'); if(el.classList.contains('request'))el.classList.add('ad__pill--warn'); else if(el.classList.contains('cancelled'))el.classList.add('ad__pill--flat'); else if(el.textContent==='Confirmed')el.classList.add('ad__pill--good');});
 app.querySelectorAll('.settings-panel,.calendar-panel,.detail').forEach(el=>{
  const title=el.querySelector('h2');const titleText=title?.textContent || 'Meeting details';title?.remove();
  const replacement=document.createElement('div');replacement.innerHTML=components.panel.replace('__TITLE__',esc(titleText)).replace('__CONTENT__','<div class="meeting-panel-body">'+el.innerHTML+'</div>');
  const panel=replacement.firstElementChild;panel.classList.add(...[...el.classList].filter(c=>c!=='panel'));if(el.id)panel.id=el.id;el.replaceWith(panel);
 });
 app.querySelectorAll('.choices-icon').forEach(el=>el.innerHTML=icon('Video'));
 app.querySelectorAll('.choice>span:last-child,.agenda-row>span:last-child').forEach(el=>el.innerHTML=icon('ArrowRight'));
 app.querySelectorAll('.success-mark').forEach(el=>el.innerHTML=icon('Check'));
 app.querySelectorAll('.hero-nav .wordmark').forEach(el=>el.innerHTML=components.logo+'<span>We Dig Creativity</span>');
 const menu=app.querySelector('.ad__topMenu');if(menu)menu.dataset.action='drawer';
 const theme=app.querySelector('.ad__themeBtn');if(theme){theme.dataset.action='theme';theme.innerHTML=icon(document.documentElement.classList.contains('dark')?'Sun':'Moon');}
 const pin=app.querySelector('[data-tour="sidebar-pin"]');if(pin)pin.dataset.action='collapse';
 app.querySelectorAll('a[href^="/admin"]').forEach(el=>{el.dataset.action=el.getAttribute('href')==='/admin/settings'?'settings':'preview-link';el.setAttribute('href','#');});
 if(state.screen==='availability'){app.querySelector('[data-action="calendar"]')?.classList.remove('is-on');app.querySelector('.ad__nav [data-action="settings"]')?.classList.add('is-on');}
}
document.addEventListener('click',e=>{
 const target=e.target.closest('[data-screen],[data-action]');if(!target)return;e.preventDefault();
 if(target.dataset.screen){state.screen=target.dataset.screen;render();return;}
 const [action,value]=target.dataset.action.split(':');
 if(action==='pick-period'){pickPeriod();return;}
 if(action==='close-picker'){target.closest('dialog').close();return;}
 if(action==='pick-year'){target.closest('dialog').querySelector('#picker-year').textContent=value;target.closest('dialog').querySelector('.year-options')?.remove();return;}
 if(action==='show-years'){const dialog=target.closest('dialog');if(!dialog.querySelector('.year-options')){const center=Number(dialog.querySelector('#picker-year').textContent);dialog.insertAdjacentHTML('beforeend',`<div class="year-options" aria-label="Choose year">${Array.from({length:12},(_,i)=>button(center-5+i,`pick-year:${center-5+i}`)).join('')}</div>`);}return;}
 if(action==='year-back'||action==='year-next'){const el=target.closest('dialog').querySelector('#picker-year');el.textContent=Number(el.textContent)+(action==='year-back'?-1:1);return;}
 if(action==='pick-month'){state.month=Number(value);state.year=Number(target.closest('dialog').querySelector('#picker-year').textContent);state.date=1;state.time='';target.closest('dialog').close();render();return;}
 if(action==='previous-month'||action==='next-month'){const dt=new Date(state.year,state.month+(action==='previous-month'?-1:1),1);state.year=dt.getFullYear();state.month=dt.getMonth();state.date=1;state.time='';render();return;}
 if(action==='reminder'){state.reminders[value]=!state.reminders[value];state.changes++;toast('Reminder preference changed · save to keep the sample policy');render();return;}
 if(action==='reminder-failure'){toast('Sample failure: connection unavailable. Reconcile delivery before retrying; uncertain delivery is not blindly resent.');return;}
 if(action==='next'){if(state.step===2){const form=document.querySelector('#details');if(!form.reportValidity())return;const data=new FormData(form);state.name=data.get('name');state.email=data.get('email');state.notes=data.get('notes');}state.step=Math.min(4,state.step+1);}
 else if(action==='back')state.step=Math.max(0,state.step-1);
 else if(action==='date'){state.date=Number(value);state.time='';}
 else if(action==='time')state.time=value+':'+target.dataset.action.split(':')[2];
 else if(action==='view')state.view=value;
 else if(action==='tab')state.tab=value;
 else if(action==='calendar'){state.screen='meetings';state.tab='Calendar';state.view='month';}
 else if(action==='meeting'){state.selected=Number(value);render();document.querySelector('#meeting-detail').classList.add('open');return;}
 else if(action==='close-detail'){document.querySelector('#meeting-detail').classList.remove('open');return;}
 else if(action==='cancel'){document.querySelector('#confirm').showModal();return;}
 else if(action==='approve'){meetings[state.selected].status='Confirmed';toast('Updated · sample request approved');}
 else if(action==='booking'||action==='reschedule'||action==='restart'){state.screen='booking';state.step=action==='reschedule'?1:0;state.time='';}
 else if(action==='settings')state.screen='availability';
 else if(action==='error')state.error=true;
 else if(action==='retry')state.error=false;
 else if(['period','hours','override','boundary'].includes(action)){state.changes++;toast('Sample change added. Save or discard below.');}
 else if(action==='save'){savedReminders={...state.reminders};state.changes=0;toast('Saved · preview only');}
 else if(action==='discard'){state.reminders={...savedReminders};state.changes=0;toast('Sample changes discarded');}
 else if(action==='manage'){state.screen='meetings';state.selected=0;}
 else if(action==='drawer'){const dialog=document.createElement('dialog');dialog.className='drawer ad';dialog.innerHTML=`${app.querySelector('.ad__sideInner').innerHTML}<div>${button('Close menu','close-menu')}</div>`;document.body.append(dialog);dialog.showModal();return;}
 else if(action==='collapse'){app.querySelector('.ad__wrap').classList.toggle('is-collapsed');return;}
 else if(action==='theme'){document.querySelector('#theme').click();render();return;}
 else if(action==='close-menu'){target.closest('dialog').remove();return;}
 else if(action==='timezone')toast('Preview time zone: Africa/Lagos (UTC+1). A searchable zone picker is included in the implementation plan.');
 else if(action==='copy')toast('The finished flow will copy your public booking link. This preview has no live booking URL.');
 else if(action==='join')toast('The confirmed provider video link will open here. No sample meeting room exists.');
 else if(action==='contact')toast('The existing project enquiry form stays available alongside booking.');
 else if(action==='setting'){if(value==='Availability'||value==='Reminders'){state.screen='availability';state.setting=value;}else toast(`${value} is included in the integration plan.`);}
 else toast('This design preview shows October 2026 and the Meetings workspace.');
 render();
});
document.querySelector('#theme').addEventListener('click',()=>{const dark=document.documentElement.classList.toggle('dark');document.querySelector('#theme').textContent=dark?'Light theme':'Dark theme';document.querySelector('#theme').setAttribute('aria-label',dark?'Switch to light theme':'Switch to dark theme');});
document.querySelector('#keep').onclick=()=>document.querySelector('#confirm').close();
document.querySelector('#cancel-confirm').onclick=()=>{meetings[state.selected].status='Cancelled';document.querySelector('#confirm').close();render();toast('Updated · sample meeting cancelled');};
render();
