"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _admin_dashboard from './admin-dashboard.bones.json'

configureBoneyard({"color":"#e7e8f1","darkColor":"#202044","animate":"pulse","speed":"1.8s","transition":180})

registerBones({
  "admin-dashboard": _admin_dashboard,
})
