(function(){
var UN="I'm not sure, please advise me";
var W={'Logo':1,'Full identity system':3,'Brand guidelines':3,'Flyers':1,'Social templates':1,'Promotional branding':1,'Packaging':2,'Signage':2,'Pitch deck':2,'Motion design':2,'Other':1};
var OUTSUG={'Look more professional':['Logo','Full identity system','Brand guidelines'],'Get noticed on social media':['Social templates','Flyers','Motion design'],'Sell more':['Promotional branding','Flyers','Packaging'],'Launch something new':['Logo','Full identity system','Signage'],'Refresh a look that feels old':['Full identity system','Brand guidelines'],'Show up well to partners and investors':['Pitch deck','Brand guidelines']};
var anyOf=function(a,l){return l.some(function(v){return has('deliverables',v)})};
var join=function(a){return (a||[]).join(', ')};
var L=function(map,v){return map[v]||v};
var RH={one:'One piece',batch:'A batch',monthly:'A regular monthly job'};
var DL={none:'No fixed date',month:'Within a month',two:'Within two weeks',set:'A set date'};
var Q=[
{id:'size',key:'job_size',label:'How big is the job?',type:'choice',req:true,unsure:true,short:'Size the client gave',cond:'Always. First question of this flow.',
 opts:[{v:'S',t:'One piece or a small set',d:'For example one logo, or a few flyers.'},{v:'M',t:'Several pieces',d:'For example a logo, a look and some social posts.'},{v:'L',t:'A full brand',d:'A whole identity with guidelines and more.'}],
 note:function(A){return 'Client says the job is: '+({S:'one piece or a small set',M:'several pieces',L:'a full brand'}[A.size]||'')}},
{id:'outcome',key:'brand_outcome',label:'What do you want your brand to help you do?',type:'multi',req:true,unsure:true,short:'Wants',cond:'Always. First question of this flow.',hint:'Pick as many as you like. We will suggest pieces that fit.',
 opts:Object.keys(OUTSUG),note:function(A){return 'Wants the brand to help with: '+join(A.outcome)}},
{id:'depth',key:'form_depth',label:'How much time do you want to spend on this form?',type:'choice',req:true,short:'Depth chosen',cond:'Always. Asked after the short core.',
 opts:[{v:'quick',t:'Quick',d:function(){return 'About '+depthMin(1)+' min. The short core only.'}},{v:'standard',t:'Standard',d:function(){return 'About '+depthMin(2)+' min. Adds style, colours and what exists today.'}},{v:'deep',t:'Deep',d:function(){return 'About '+depthMin(3)+' min. Adds references, uploads and detail.'}}],
 note:function(A){return 'Chose the '+A.depth+' depth'}},
{id:'deliverables',key:'deliverables',old:true,label:'What are we making?',type:'cards',req:true,unsure:true,short:'Deliverables',cond:'Always',hint:'Pick as many as you need. Tap a card to pick it.',
 suggest:function(A,v){return window.__wdc&&window.__wdc.FI===1&&(A.outcome||[]).some(function(o){return (OUTSUG[o]||[]).indexOf(v)>-1})},
 opts:[
 {v:'Logo',t:'Logo',d:'The mark people remember you by. Comes in colour, black and white.',img:['logo__thinkers-diary-logo','logo__direct-link-logo','logo__vickygold-logo'],alt:['Thinkers Diary logo','Direct Link logo','VICKYGOLD logo'],cap:'Thinkers Diary, Direct Link, VICKYGOLD'},
 {v:'Full identity system',t:'Full identity system',d:'A whole look: logo, colours, type and how they work together.',img:['identity__moore-mockups','identity__marfaa-mockups','identity__thinkers-mockups'],alt:['Moore Designs identity on clothing and bags','MARFAA identity mockups','Thinkers Diary identity mockups'],cap:'Moore Designs, MARFAA, Thinkers Diary'},
 {v:'Brand guidelines',t:'Brand guidelines',d:'A rulebook so anyone can use your brand the right way.',img:['guidelines__dhiol-brand-guide-1','guidelines__tab-guide-1','guidelines__skinish-colour-system'],alt:['Dhiol World brand guide cover','The Ajoks Brand guide cover','Skinish colour system page'],cap:'Dhiol World, TAB The Ajoks Brand, Skinish'},
 {v:'Flyers',t:'Flyers',d:'Single sheets for events, offers and launches.',img:['flyers__abebi-treats-flyer','flyers__tife-luxe-flyer','flyers__bay-accessories-flyer'],alt:['Abebi Treats flyer','Tife Luxe flyer','Bay Accessories flyer'],cap:'Abebi Treats, Tife Luxe, Bay Accessories'},
 {v:'Social templates',t:'Social templates',d:'Post layouts you reuse each time, in your colours.',img:['social__dhiol-world-april','social__bamssa-new-month','social__span-welcome-back'],alt:['Dhiol World monthly post','BAMSSA OOU new month post','SPAN OOU welcome back post'],cap:'Dhiol World, BAMSSA OOU, SPAN OOU'},
 {v:'Promotional branding',t:'Promotional branding',d:'Sale and offer pieces that match your brand.',img:['promo__delivery-promo','promo__fragrance-promo','promo__hair-sale'],alt:['Delivery promo','Fragrance promo','Hair sale promo'],cap:'Delivery, fragrance and hair sale promos'},
 {v:'Packaging',t:'Packaging',d:'Bags, boxes and labels that carry your brand to the customer.',img:['packaging__marfaa-packaging','packaging__fash-shopping-bag','packaging__merch-range'],alt:['MARFAA packaging','Fash shopping bag','SPAN merch range'],cap:'MARFAA, Fash, SPAN merch'},
 {v:'Signage',t:'Signage',d:'Shop signs and boards people see from the street.',img:['signage__moore-signage','signage__moore-storefront','signage__mayrols-signage'],alt:['Moore Designs signage','Moore Designs storefront','Mayrols signage'],cap:'Moore Designs, Mayrols'},
 {v:'Pitch deck',t:'Pitch deck',d:'Slides or a profile that explain your business to partners.',img:['pitch-profile__millcon-cover','pitch-profile__millcon-services','pitch-profile__millcon-partners'],alt:['Millcon profile cover','Millcon services page','Millcon partners page'],cap:'Millcon corporate profile pages'},
 {v:'Motion design',t:'Motion design',d:'Moving brand work, like reveals, promos and reels. You pick the kind next.',tile:'Clip pending',capNote:'Sample clips are pending'},
 {v:'Other',t:'Something else',d:'Tell us what you have in mind.',tile:'Your idea'}],
 note:function(A){return 'Deliverables: '+join(A.deliverables)},
 pts:function(A){var n=0;(A.deliverables||[]).forEach(function(v){n+=W[v]||1});return {t:'Deliverables',n:n}},
 risk:function(A){var r=[];if(has('deliverables','Logo')||has('deliverables','Full identity system'))r.push('Logo or identity: the trademark check is the client’s duty, as the agreement says.');return r}},
{id:'deliverables_other',key:'deliverables_other',old:true,label:'What else would you like us to create?',type:'text',req:false,parent:'deliverables',cond:'Shows when "Something else" is picked in What are we making?',fn:function(A){return has('deliverables','Other')},short:'Other deliverable'},
{id:'motion_kinds',key:'motion_kinds',label:'What kind of motion design?',type:'motion',req:true,parent:'deliverables',unsureOpt:UN,cond:'Shows when "Motion design" is picked in What are we making?',fn:function(A){return has('deliverables','Motion design')},
 hint:'Pick as many as you need. The clips show here once the owner supplies them.',
 opts:[{v:'logo-reveal',t:'Logo reveal',d:'Your mark appears in a few seconds.',clip:'16:9'},{v:'promo-video',t:'Promo video',d:'A short film that sells one thing.',clip:'16:9'},{v:'social-reel',t:'Social reel',d:'Upright video for Instagram and TikTok.',clip:'9:16'},{v:'explainer',t:'Explainer',d:'Shows how something works in plain steps.',clip:'16:9'},{v:'hero-loop',t:'Website hero loop',d:'A quiet looping film behind your homepage.',clip:'16:9'},{v:'unsure',t:UN,d:'We will suggest the right kind.'}],
 short:'Motion kinds',note:function(A){return 'Motion design kinds: '+(A.motion_kinds||[]).map(function(v){return ({'logo-reveal':'logo reveal','promo-video':'promo video','social-reel':'social reel','explainer':'explainer','hero-loop':'website hero loop',unsure:'client wants advice'})[v]}).join(', ')},
 pts:function(A){var k=(A.motion_kinds||[]).filter(function(v){return v!=='unsure'}).length;return k?{t:'Motion kinds',n:k}:null},
 risk:function(A){return ['Motion design: music and motion asset licences to confirm before work starts.'].concat(has('motion_kinds','unsure')?['Motion kind not chosen: advise the client before quoting.']:[])}},
{id:'job_rhythm',key:'job_rhythm',label:'Is this one piece, a batch, or a regular job?',type:'choice',req:true,short:'Rhythm',cond:'Always',hint:'Flyers and social templates are small jobs. They can be any of these.',
 opts:[{v:'one',t:'One piece'},{v:'batch',t:'A batch'},{v:'monthly',t:'A regular monthly job'}],
 note:function(A){return 'Rhythm: '+RH[A.job_rhythm].toLowerCase()},
 pts:function(A){return A.job_rhythm==='batch'?{t:'Batch',n:1}:A.job_rhythm==='monthly'?{t:'Regular monthly job',n:2}:null},
 risk:function(A){return A.job_rhythm==='monthly'?['Recurring work: needs monthly terms and a capacity check.']:A.job_rhythm==='batch'?['Batch work: agree the count and a price per piece.']:[]}},
{id:'batch_count',key:'batch_count',label:'How many pieces are in the batch?',type:'number',req:true,unsure:true,parent:'job_rhythm',ph:'For example 8',cond:'Shows when the rhythm is "A batch"',fn:function(A){return A.job_rhythm==='batch'},short:'Batch size',
 pts:function(A){return parseInt(A.batch_count,10)>10?{t:'More than 10 pieces',n:1}:null}},
{id:'monthly_count',key:'monthly_count',label:'How many pieces a month?',type:'number',req:true,unsure:true,parent:'job_rhythm',ph:'For example 4',cond:'Shows when the rhythm is "A regular monthly job"',fn:function(A){return A.job_rhythm==='monthly'},short:'Pieces per month',
 pts:function(A){return parseInt(A.monthly_count,10)>10?{t:'More than 10 pieces a month',n:1}:null}},
{id:'recurring_kind',key:'recurring_kind',label:'What kind of pieces?',type:'multi',req:true,parent:'job_rhythm',cond:'Shows when the rhythm is "A regular monthly job"',fn:function(A){return A.job_rhythm==='monthly'},short:'Monthly pieces',
 opts:['Flyers','Social posts','Ad pictures','Short videos','Something else']},
{id:'deadline_kind',key:'deadline_kind',label:'When do you need it?',type:'choice',req:true,short:'Timing',cond:'Always',
 opts:[{v:'none',t:'No fixed date'},{v:'month',t:'Within a month'},{v:'two',t:'Within two weeks'},{v:'set',t:'A set date'}],
 note:function(A){return 'Timing: '+DL[A.deadline_kind].toLowerCase()},pts:function(A){return A.deadline_kind==='two'?{t:'Rush',n:1}:null},
 risk:function(A){return A.deadline_kind==='two'?['Rush date: within two weeks.']:[]}},
{id:'fixed_dates',key:'fixed_dates',old:true,label:'Which date, and what is it for?',type:'long',req:false,parent:'deadline_kind',ph:'A launch, an event, a print deadline.',cond:'Shows when timing is "Within two weeks" or "A set date"',fn:function(A){return A.deadline_kind==='two'||A.deadline_kind==='set'},short:'Fixed date',unsure:false,typeNote:'Long text. In the build this is a text box, not the browser date picker.'},
{id:'brand_state',key:'brand_state',old:true,label:'What exists today?',type:'choice',req:true,short:'Exists today',cond:'Always',
 opts:['Nothing yet','A logo only','A full identity needing a refresh'],
 risk:function(A){return A.brand_state==='Nothing yet'?[]:['Existing brand to protect: confirm what must not change before design starts.']}},
{id:'untouchable',key:'untouchable',old:true,label:'Anything that must not change?',type:'long',req:false,unsure:true,parent:'brand_state',ph:'A name, a colour or a logo people already know you by.',cond:'Shows when "What exists today?" is "A logo only" or "A full identity needing a refresh"',fn:function(A){return A.brand_state==='A logo only'||A.brand_state==='A full identity needing a refresh'},short:'Must not change'},
{id:'logo_files',key:'logo_files',old:true,label:'Upload what you have today',type:'upload',req:false,parent:'brand_state',cond:'Shows when "What exists today?" is "A logo only" or "A full identity needing a refresh"',fn:function(A){return A.brand_state==='A logo only'||A.brand_state==='A full identity needing a refresh'},short:'Files supplied',dropNote:'Logo files, brand guide, fonts. This is a mock. Nothing leaves this page.'},
{id:'style_help',key:'style_help',label:'How would you like to set the style?',type:'choice',req:true,short:'Style route',cond:'Always',
 opts:[{v:'refs',t:'I have references',d:'Upload pictures or paste links.'},{v:'suggest',t:'Suggest for me',d:'We pick a direction for you.'},{v:'both',t:'A bit of both',d:'You share some, we fill the gaps.'}],
 note:function(A){return 'Style route: '+({refs:'client has references',suggest:'studio suggests',both:'a bit of both'})[A.style_help]}},
{id:'style_links',key:'inspiration',old:true,label:'Paste links to examples you like, and say what you like about each',type:'links',req:false,parent:'style_help',ph:'One link per line, then a few words.',cond:'Shows when the style route is "I have references" or "A bit of both"',fn:function(A){return A.style_help==='refs'||A.style_help==='both'},short:'Reference links',d:3,s:1},
{id:'style_files',key:'assets',old:true,label:'Upload pictures you like',type:'upload',req:false,parent:'style_help',cond:'Shows when the style route is "I have references" or "A bit of both"',fn:function(A){return A.style_help==='refs'||A.style_help==='both'},short:'Reference pictures',d:3,s:2},
{id:'style_note_refs',type:'notice',parent:'style_help',label:'In this flow, references open at the Deep depth.',html:'<b>References open at the Deep depth.</b> Pick Deep to add links and pictures now, or send them later in the portal.',cond:'Shows when the style route is "I have references" or "A bit of both" and the depth is Quick or Standard. This flow only.',fn:function(A){return (A.style_help==='refs'||A.style_help==='both')&&A.depth!=='deep'}},
{id:'style_directions',key:'style_directions',label:'Would you like to see a few directions before we start?',type:'yesno',req:true,parent:'style_help',cond:'Shows when the style route is "Suggest for me"',fn:function(A){return A.style_help==='suggest'},short:'Directions first',
 note:function(A){return A.style_directions==='yes'?'Client wants to see a few directions first. Send options before design starts.':'Client does not want directions first. The studio picks a direction and confirms it before going further.'},
 risk:function(A){return A.style_directions==='no'?['Studio picks the direction: confirm it with the client before design continues.']:[]}},
{id:'style_copy',type:'notice',parent:'style_help',label:'Either way, we will do this properly. If you say no, we will choose a direction that fits your business and confirm it with you before we go further.',html:'Either way, we will do this properly. If you say no, we will choose a direction that fits your business and confirm it with you before we go further.',cond:'Shows with the directions question, when the style route is "Suggest for me"',fn:function(A){return A.style_help==='suggest'}},
{id:'colours',key:'brand_colours',old:true,label:'Colours you like',type:'colours',req:false,unsure:true,short:'Colours',typeNote:'Colour system: family, shade, auto name, Like it to Love it slider, first choice mark, up to 5. Stored as readable text in brand_colours.',
 cond:'Shows when "Full identity system", "Brand guidelines", "Flyers" or "Social templates" is picked',fn:function(A){return anyOf(A,['Full identity system','Brand guidelines','Flyers','Social templates'])},
 note:function(A){var c=A.colours||[];return c.length?'Colours (stored lines): '+c.map(function(x){return x.name+' '+x.hex.toUpperCase()+' (like '+x.like+' of 5'+(x.first?', first choice':'')+')'}).join(', '):null}},
{id:'surfaces',key:'surfaces',old:true,label:'Where will people see or use your logo?',type:'multi',req:false,unsure:true,short:'Used on',cond:'Shows when "Logo", "Signage" or "Packaging" is picked',fn:function(A){return anyOf(A,['Logo','Signage','Packaging'])},
 opts:['Embroidery','Signage','Print','Screen','Packaging','Vehicle','Stamp or seal','Other'],
 risk:function(A){return has('surfaces','Embroidery')?['Embroidery: check the logo stays clear at small sizes.']:[]}},
{id:'surfaces_other',key:'surfaces_other',old:true,label:'Where else must the brand work?',type:'text',req:false,parent:'surfaces',cond:'Shows when "Other" is picked in the places question',fn:function(A){return has('surfaces','Other')},short:'Other places'},
{id:'supplied_assets',key:'supplied_assets',label:'Will you give us fonts, pictures or music to use?',type:'multi',req:false,short:'Client supplies',cond:'Shows when any deliverable is picked',fn:function(A){return (A.deliverables||[]).length>0},hint:'You promise you may use them. The agreement below explains this.',
 opts:['Fonts','Pictures or photos','Music','Logos from other people','None'],
 risk:function(A){var l=(A.supplied_assets||[]).filter(function(v){return v!=='None'});return l.length?['Client supplies '+l.join(', ').toLowerCase()+': licence check before use.']:[]}},
{id:'guide_voice',key:'guide_voice',label:'How should the brand sound?',type:'choice',req:false,unsure:true,short:'Voice',cond:'Shows when "Brand guidelines" is picked',fn:function(A){return has('deliverables','Brand guidelines')},opts:['Warm and friendly','Calm and professional','Bold and playful','Smart and direct']},
{id:'guide_personality',key:'guide_personality',label:'Which words fit the brand?',type:'multi',req:false,unsure:true,short:'Personality',cond:'Shows when "Brand guidelines" is picked',fn:function(A){return has('deliverables','Brand guidelines')},opts:['Friendly','Trusted','Modern','Premium','Fun','Serious','Local','Global']},
{id:'guide_layouts',key:'guide_layouts',label:'Which layouts should the guide cover?',type:'multi',req:false,unsure:true,short:'Layouts',cond:'Shows when "Brand guidelines" is picked',fn:function(A){return has('deliverables','Brand guidelines')},opts:['Letterhead and documents','Social posts','Presentations','Website','Packaging','Signage']},
{id:'avoid',key:'avoid',old:true,label:'Anything we should steer well clear of?',type:'long',req:false,unsure:true,short:'Avoid',cond:'Always',typeNote:'Long text'}
];
/* levels: s is the size gate, d the depth gate */
var S2=['untouchable','logo_files','style_files','colours','surfaces','supplied_assets'],S3=['guide_voice','guide_personality','guide_layouts','avoid'];
Q.forEach(function(q){if(q.s==null)q.s=S2.indexOf(q.id)>-1?2:S3.indexOf(q.id)>-1?3:1});
var D2=['brand_state','style_help','style_directions','style_copy','style_note_refs','colours','surfaces'],D3=['untouchable','logo_files','style_links','style_files','supplied_assets','guide_voice','guide_personality','guide_layouts','avoid'];
Q.forEach(function(q){if(q.d==null||q.d===3&&q.id==='style_links')q.d=D3.indexOf(q.id)>-1?3:D2.indexOf(q.id)>-1?2:1});
var core=['deliverables','deliverables_other','motion_kinds','job_rhythm','batch_count','monthly_count','recurring_kind','deadline_kind','fixed_dates'];
var rest=['brand_state','untouchable','logo_files','style_help','style_links','style_files','style_note_refs','style_directions','style_copy','colours','surfaces','surfaces_other','supplied_assets','guide_voice','guide_personality','guide_layouts','avoid'];
window.CFG={shortName:'Branding and Design',h1:'Onboarding: Branding & Design',
 lede:'One form for logos, identities, guidelines, small jobs, motion design and more. Three ways to run it. Pick the one that feels right for your clients.',
 previewNote:'The shared details step (name, phone, email, business, about) stays as it is today. This page covers the Branding & Design step and the questions moved here from the closing step.',
 flows:[
 {name:'Size first',short:'One opening question about how big the job is.',blurb:'The client says how big the job is. A small job finishes in about 6 to 8 questions. Bigger jobs open more questions.',best:'Mixed clients and many small jobs.',head:'size',gate:'s',levels:{S:1,M:2,L:3},levelText:{2:'And the job is "Several pieces" or "A full brand", or the client was not sure.',3:'And the job is "A full brand".'},
  order:['size'].concat(core,rest),studioNote:'The size question is the client’s own view. The score on the left is counted from the picks.'},
 {name:'Outcome first',short:'Start with what the brand should help them do.',blurb:'Open with what the client wants to happen. The cards then show suggested pieces. Places and licences come last, and only if they apply.',best:'Clients with no technical knowledge.',head:'outcome',tech:['surfaces','surfaces_other','supplied_assets','guide_voice','guide_personality','guide_layouts','avoid'],
  order:['outcome','deliverables','deliverables_other','motion_kinds','job_rhythm','batch_count','monthly_count','recurring_kind','style_help','style_links','style_files','style_directions','style_copy','colours','deadline_kind','fixed_dates','brand_state','untouchable','logo_files','surfaces','surfaces_other','supplied_assets','guide_voice','guide_personality','guide_layouts','avoid'],studioNote:'Suggested cards are hints. Nothing is ticked for the client.'},
 {name:'Choose your depth',short:'Same short core, then Quick, Standard or Deep.',blurb:'Everyone answers the same short core. Then they pick Quick, Standard or Deep. Deep opens references, uploads and detail.',best:'Clients who want to spend more time, and clients who do not.',head:'depth',gate:'d',levels:{quick:1,standard:2,deep:3},levelText:{2:'And the depth is Standard or Deep.',3:'And the depth is Deep.'},
  order:core.concat(['depth'],rest),studioNote:'Depth only changes how many questions show.'}],
 Q:Q,defaults:{size:'M',outcome:['Look more professional'],depth:'standard'},
 sample:{deliverables:['Logo','Full identity system','Flyers','Motion design'],motion_kinds:['logo-reveal','social-reel'],job_rhythm:'monthly',monthly_count:'4',recurring_kind:['Flyers'],deadline_kind:'two',fixed_dates:'The shop opens on 30 November.',brand_state:'A logo only',untouchable:'Keep the navy and the name.',style_help:'suggest',style_directions:'yes',colours:[{hex:'#0b5d3b',name:'Deep green',like:5,first:true},{hex:'#f4c430',name:'Gold',like:4,first:false},{hex:'#111111',name:'Dark grey',like:3,first:false}],surfaces:['Signage','Screen'],supplied_assets:['Fonts']},
 bands:[{max:3,t:'Small'},{max:8,t:'Medium'},{max:999,t:'Large'}],
 sizeRule:'Small is up to 3, Medium is 4 to 8, Large is 9 or more. Points: logo 1, identity 3, guidelines 3, flyers 1, social templates 1, promo 1, packaging 2, signage 2, pitch deck 2, motion 2, other 1. Batch adds 1, a regular job adds 2, each motion kind adds 1, more than 10 pieces adds 1, a rush date adds 1.',
 extra:function(A,h){var c=A.colours||[];if(!c.length)return '';var s=h.sortColours(c),roles=[['Primary','primary'],['Secondary','secondary'],['Accent','accent'],['Text','text'],['Neutral','neutral']],e=h.esc;
  var x='<h3 style="margin-top:14px">Colours, sorted for the studio</h3><p class="sm">A suggestion, computed when read, not stored. First choice becomes primary. The next most liked colour that differs enough becomes secondary. A strong saturated colour becomes accent. A very dark colour with little tint becomes text. A very light or low tint colour becomes neutral.</p><div class="tw"><table style="min-width:420px"><thead><tr><th>Role</th><th>Colour</th><th>Like</th></tr></thead><tbody>';
  roles.forEach(function(r){var v=s[r[1]];x+='<tr><td>'+r[0]+'</td><td>'+(v?'<span class="sw" style="display:inline-block;width:18px;height:18px;vertical-align:middle;margin-right:8px;background:'+v.hex+'"></span>'+e(v.name)+' '+v.hex.toUpperCase():'None picked')+'</td><td>'+(v?v.like+' of 5':'')+'</td></tr>'});
  if(s.extra)x+='<tr><td>Extra</td><td>'+s.extra.map(function(v){return e(v.name)}).join(', ')+'</td><td></td></tr>';
  x+='</tbody></table></div><h3 style="margin-top:14px">Stored text, one line per colour</h3><div class="code">'+c.map(function(v){return e(h.colLine(v))}).join('<br>')+'</div><p class="sm">Proposed format. Old lines such as "Navy | #000065 | Primary" still read and display. brand-colours.ts and its check script change together.</p>';return x},
 next:['We read your answers.','We book a short call to go through them with you.','Your quote follows that call. Owner to confirm when the quote arrives.','You can come back to change your answers until you send them. Your link is saved.'],
 eng:{extra:{1:['The work covers the kinds of motion design you picked. Each kind is quoted on its own.','Batch and regular monthly work follow the volume and monthly terms in your quote. Work above that volume is quoted again.'],5:['Licences for fonts, stock pictures and music that the work needs are a third party cost. You pay them. We tell you first.','Regular monthly work is billed as your quote sets out.'],6:['Fonts, pictures and music we license for you stay under their own licence terms. Owning the finished design does not change those terms.'],7:['You promise you may use every font, picture, logo and piece of music you supply.','Music and motion material you supply needs a licence that covers where the work will be shown.','Trademark checks are your duty. We do not search or register trademarks for you unless the quote says so.'],8:['This includes claims about fonts, pictures or music you ask us to use.'],9:['We cannot promise that a design will be approved, registered or liked by your customers.'],10:['Print shops, platforms and licence holders can change their terms and prices.']}},
 decisions:[
 'Pick one flow for Branding & Design: Size first, Outcome first or Choose your depth.',
 'Approve the exact style help copy: "Would you like to see a few directions before we start?" and "Either way, we will do this properly. If you say no, we will choose a direction that fits your business and confirm it with you before we go further."',
 'The plan shows the directions question only after "Suggest for me". Should "A bit of both" show it too? This page follows the plan.',
 'Motion design clips are not supplied yet. The tiles say "Clip pending". No clip is a stand alone logo reveal or a website hero loop. Supply them, or cut the first seconds of the Realtors’ Practice clips, or use the studio hero films.',
 'Stationery and apparel are not offered as cards because the plan’s deliverable list does not include them. The sample pack has apparel pictures. Add the cards, or leave them out?',
 'The Pitch deck card shows Millcon profile pages, because the Realtors’ Practice decks hold prices and contact details. Confirm that is fine.',
 'Colour storage. Proposed line: "Deep green | #0B5D3B | like 5 of 5 | first choice". Old lines without the new parts must still read. Confirm the format.',
 'The stored not sure value in the code (UNSURE in onboarding.ts) has a semicolon. Owner copy uses a comma. Keep the stored value and show the comma wording?',
 'The review screen says when the quote arrives. No timing exists in the plan. Owner to give the wording or the number of days.',
 'Engagement text is a draft. It stays off until a Nigerian lawyer has reviewed it. Open item O2 still decides whether ticks replace or sit beside a signed agreement.',
 'Dates are typed in a text box here, not the browser date picker, because native pickers are being replaced.',
 'Questions moved from the closing step into this form: fixed dates, references and uploads. The shared "Finishing up" step stays for approver and channels. Confirm.',
 'HeroUI ColorPicker would add a dependency (HeroUI plus React Aria). Repo rule is no package for a small UI effect, owner has allowed it for this component. Confirm that the family and shade chooser, like slider and first choice mark stay custom, and only the free picker uses HeroUI.',
 'HeroUI v3 is built on React Aria and Tailwind 4 (the repo has Tailwind 4), but it brings its own theme tokens and CSS. Before building, a Haiku agent must check it does not fight the WDC tokens, and must style it with the WDC black and white buttons, Space Grotesk and Outfit.']
};
})();
