import 'server-only';
import {randomUUID} from 'node:crypto';
import type {PoolClient} from 'pg';
import {db} from '@/lib/db/pool';
import {transaction} from '@/lib/db/transaction';
import {adoptPersistedRecord} from '@/lib/admin/persist';
import {STAGES,PRIORITIES,naira,type Project,type Client,type Task,type Update,type AuditKind} from '@/lib/admin/types';
import {requireProjectActor,requireWorkspaceUser,projectRecipients,projectRecipientsForRecord,type WorkspaceActor,type WorkspaceUser,type WorkspaceRecipient} from './access';
import {emitWorkspaceEvent} from './events';

type Changed={collection:string;id:string;data:{id:string}|null};
type Context={actor:WorkspaceUser;project:Project;recipients:WorkspaceRecipient[];internal:WorkspaceRecipient[];eventIds:string[];changed:Changed[]};
const now=()=>new Date().toISOString();
function bounded(value:string,max=12000){if(value.length>max)throw Error('This text is too long.');return value.trim();}
async function read<T>(tx:PoolClient,collection:string,id:string):Promise<T>{const result=await tx.query<{data:T}>('SELECT data FROM admin_records WHERE collection=$1 AND id=$2 FOR UPDATE',[collection,id]);if(!result.rows[0]?.data)throw Error('This record is no longer available.');return result.rows[0].data;}
async function put(tx:PoolClient,context:Context,collection:string,data:{id:string}|null,id=data?.id){if(!id)throw Error('Record identity required.');await tx.query(`INSERT INTO admin_records(collection,id,data,seq,ord,updated_at) VALUES($1,$2,$3::JSONB,nextval('admin_records_seq'),currval('admin_records_seq'),now()) ON CONFLICT(collection,id) DO UPDATE SET data=excluded.data,seq=excluded.seq,updated_at=excluded.updated_at`,[collection,id,data?JSON.stringify(data):null]);context.changed.push({collection,id,data});}
async function audit(tx:PoolClient,context:Context,kind:AuditKind,subjectId:string,subject:string,action:string,note='',field?:string,from?:string,to?:string){await tx.query('INSERT INTO audit_log(at,actor,kind,subject_id,subject,action,field,from_value,to_value,note) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[now(),context.actor.name.slice(0,200),kind,subjectId,subject.slice(0,300),action,field??null,from?.slice(0,2000)??null,to?.slice(0,2000)??null,note.slice(0,2000)||null]);}
function history(context:Context,text:string,visibility:'client'|'internal'){context.project.events.push({at:now(),text,visibility} as Project['events'][number]);}
async function event(tx:PoolClient,context:Context,kind:string,title:string,summary:string,visibility:'client'|'internal',recipients=visibility==='internal'?context.internal:context.recipients){const id=randomUUID();await emitWorkspaceEvent({id,projectId:context.project.id,clientId:context.project.clientId,kind,category:kind.includes('stage')?'progress':'actions',actorId:context.actor.userId,actorName:context.actor.name,title,summary,href:'/admin/projects/'+context.project.id,visibility,recipients},tx);context.eventIds.push(id);}
function adopt(context:Context){for(const record of context.changed)adoptPersistedRecord(record.collection,record.id,record.data);}
async function currentProject(tx:PoolClient,actor:WorkspaceActor){const active=await tx.query('SELECT 1 FROM "user" WHERE id=$1 AND role=$2 AND "deactivatedAt" IS NULL',[actor.userId,actor.role]);if(!active.rowCount)throw Error('Your account access has ended.');const project=await read<Project>(tx,'PROJECTS',actor.project.id);const client=await read<Client>(tx,'CLIENTS',project.clientId);if(project.clientId!==actor.clientId||project.archived||client.archived||client.mergedInto)throw Error('This project is no longer open for changes.');if(actor.role!=='owner'&&!project.ownerIds?.includes(actor.userId)){const access=await tx.query('SELECT 1 FROM workspace_project_members WHERE project_id=$1 AND user_id=$2 AND can_manage=true AND revoked_at IS NULL',[project.id,actor.userId]);if(!access.rowCount)throw Error('Your project access changed.');}return project;}
async function contextFor(projectId:string){const actor=await requireProjectActor(projectId,'manage');if(actor.kind!=='staff')throw Error('Only the studio can change the project.');const [recipients,internal]=await Promise.all([projectRecipients(projectId,'all'),projectRecipients(projectId,'internal')]);return {actor,recipients,internal};}
export type ProjectChange={kind:'stage';stage:Project['stage'];expectedStage:string;note?:string;order?:string[]}|{kind:'note';text:string}|{kind:'due';due:string|null}|{kind:'details';patch:Partial<Pick<Project,'owner'|'ownerIds'|'health'|'channel'|'budget'|'scope'|'icon'|'iconColor'>>}|{kind:'update';update:Omit<Update,'id'|'at'|'author'|'projectId'>};
export async function changeProjectRecord(projectId:string,input:ProjectChange){
 const prepared=await contextFor(projectId);
 if(input.kind==='details'&&input.patch.ownerIds){const found=await db.query<{data:Client}>("SELECT data FROM admin_records WHERE collection='CLIENTS' AND id=$1",[prepared.actor.clientId]);if(!found.rows[0]?.data)throw Error('This client is no longer available.');const proposed={...prepared.actor.project,...input.patch};[prepared.recipients,prepared.internal]=await Promise.all([projectRecipientsForRecord(proposed,found.rows[0].data,'all'),projectRecipientsForRecord(proposed,found.rows[0].data,'internal')]);}
 const result=await transaction(async tx=>{const project=await currentProject(tx,prepared.actor);const context:Context={...prepared,project,eventIds:[],changed:[]};
 if(input.kind==='stage'){
  if(!STAGES.includes(input.stage)||!STAGES.includes(input.expectedStage as Project['stage']))throw Error('Refresh this project before moving it.');if(project.stage!==input.expectedStage)throw Error('The stage changed. Refresh before moving it.');
  const note=bounded(input.note||'');const before=project.stage;
  if(before!==input.stage){project.stage=input.stage;history(context,'Moved to '+input.stage,'client');if(note)history(context,note,'internal');await audit(tx,context,'project',project.id,project.title,'moved',note,'stage',before,input.stage);await event(tx,context,'project.stage_changed',project.title+': now '+input.stage,'Moved from '+before+' to '+input.stage+'.','client');}
  if(input.order){const order=[...new Set(input.order)];if(order.length>500)throw Error('Too many board records.');for(const [rank,id]of order.entries()){const record=id===project.id?project:await read<Project>(tx,'PROJECTS',id);if(record.stage!==input.stage)throw Error('The board changed. Refresh before reordering.');if(prepared.actor.role!=='owner'&&!record.ownerIds?.includes(prepared.actor.userId)){const access=await tx.query('SELECT 1 FROM workspace_project_members WHERE project_id=$1 AND user_id=$2 AND can_manage=true AND revoked_at IS NULL',[id,prepared.actor.userId]);if(!access.rowCount)throw Error('You cannot reorder this project.');}if(record.archived)throw Error('An archived project cannot be reordered.');if(record.clientId!==project.clientId){const client=await read<Client>(tx,'CLIENTS',record.clientId);if(client.archived||client.mergedInto)throw Error('A closed client project cannot be reordered.');}record.rank=rank;await put(tx,context,'PROJECTS',record);}}
 }else if(input.kind==='note'){const text=bounded(input.text);if(!text)throw Error('Write a note first.');history(context,text,'internal');await audit(tx,context,'project',project.id,project.title,'noted',text);await event(tx,context,'project.internal_note','Internal project note',text,'internal');
 }else if(input.kind==='due'){if(input.due&&!Number.isFinite(new Date(input.due).getTime()))throw Error('Choose a valid deadline.');if(project.due!==input.due){const before=project.due;project.due=input.due;const text=input.due?'Due date set to '+input.due.slice(0,10):'Due date cleared';history(context,text,'client');await audit(tx,context,'project',project.id,project.title,'changed deadline','', 'due',before||'',input.due||'');await event(tx,context,'project.deadline_changed','Project deadline updated',text,'client');}
 }else if(input.kind==='update'){const update:Update={...input.update,id:randomUUID(),projectId,at:now(),author:prepared.actor.name,progress:bounded(input.update.progress),blockers:bounded(input.update.blockers),next:bounded(input.update.next)};if(!update.progress)throw Error('Explain what moved.');if(project.health!==update.health){history(context,'Health moved to '+update.health,'internal');project.health=update.health;}history(context,update.clientVisible?'Update posted, visible to the client':'Internal note added','internal');await put(tx,context,'UPDATES',update);await audit(tx,context,'update',update.id,project.title,'posted',update.clientVisible?'Shared with the client':'Internal team only');await event(tx,context,'project.progress_shared',update.clientVisible?'Project update shared':'Internal progress update',[update.progress,update.blockers?'Blockers: '+update.blockers:'',update.next?'Next: '+update.next:''].filter(Boolean).join('\n'),update.clientVisible?'client':'internal');
 }else {
  const patch=input.patch;if('budget'in patch&&prepared.actor.role!=='owner')throw Error('Only the owner changes financial figures.');if(patch.budget!=null&&(!Number.isSafeInteger(patch.budget)||patch.budget<0))throw Error('Choose a valid project budget.');for(const key of ['owner','scope']as const)if(patch[key]!=null)bounded(patch[key]!);
  if(patch.ownerIds){const found=await tx.query<{id:string}>('SELECT id FROM "user" WHERE id=ANY($1::STRING[]) AND role IN (\'staff\',\'owner\') AND "deactivatedAt" IS NULL',[patch.ownerIds]);if(found.rows.length!==new Set(patch.ownerIds).size)throw Error('Choose active studio accounts as project leads.');}
  const previous={...project,ownerIds:[...(project.ownerIds||[])]};Object.assign(project,patch);await put(tx,context,'PROJECTS',project);
  const leadChanged=previous.owner!==project.owner||JSON.stringify(previous.ownerIds)!==JSON.stringify(project.ownerIds||[]),scopeChanged=previous.scope!==project.scope;
  if(leadChanged||scopeChanged){const text=[leadChanged?'Responsible: '+(project.owner||'Not assigned'):'',scopeChanged?'The project scope was updated. Review the current project agreement.':''].filter(Boolean).join('\n');history(context,text,'client');await event(tx,context,'project.details_changed','Project responsibilities and details updated',text,'client');}
  if(previous.health!==project.health){history(context,'Health moved to '+project.health,'internal');await event(tx,context,'project.health_changed','Internal project health updated',project.health,'internal');}
  for(const userId of project.ownerIds||[])if(!previous.ownerIds.includes(userId))await event(tx,context,'project.lead_assigned','You are responsible for '+project.title,'Open the project for its current scope and next steps.','internal',[{userId,email:'',name:'',role:'staff'}]);
  for(const userId of previous.ownerIds)if(!(project.ownerIds||[]).includes(userId))await event(tx,context,'project.access_revoked','Project responsibility changed','You are no longer an assigned lead for '+project.title+'.','internal',[{userId,email:'',name:'',role:'staff'}]);
  for(const key of Object.keys(patch) as (keyof typeof patch)[]){if(JSON.stringify(previous[key])!==JSON.stringify(project[key])){const format=(value:unknown)=>key==='budget'?typeof value==='number'?naira(value):'Not agreed':Array.isArray(value)?value.join(', '):String(value??'');await audit(tx,context,'project',project.id,project.title,'changed','',key,format(previous[key]),format(project[key]));}}
 }
 await put(tx,context,'PROJECTS',project);return context;});adopt(result);return {project:result.project,eventIds:result.eventIds};
}

export async function changeLegacyTask(input:{kind:'create';projectId:string;task:Omit<Task,'id'|'projectId'|'done'|'doneAt'>}|{kind:'toggle'|'remove';id:string;expectedDone?:boolean}){
 const initial=input.kind==='create'?null:(await db.query<{data:Task}>("SELECT data FROM admin_records WHERE collection='TASKS' AND id=$1",[input.id])).rows[0]?.data;if(input.kind!=='create'&&!initial)throw Error('This task is no longer available.');const projectId=input.kind==='create'?input.projectId:initial!.projectId,prepared=await contextFor(projectId);
 const result=await transaction(async tx=>{const project=await currentProject(tx,prepared.actor),context:Context={...prepared,project,eventIds:[],changed:[]};let task:Task;
  if(input.kind==='create'){if(!PRIORITIES.includes(input.task.priority))throw Error('Choose a valid priority.');task={...input.task,id:randomUUID(),projectId,done:false,doneAt:null,title:bounded(input.task.title,240),assignee:bounded(input.task.assignee,240)};if(!task.title)throw Error('Write a task title.');if(task.blockedBy){const dependency=await read<Task>(tx,'TASKS',task.blockedBy);if(dependency.projectId!==projectId)throw Error('Dependencies must belong to this project.');}await put(tx,context,'TASKS',task);
  }else{task=await read<Task>(tx,'TASKS',input.id);if(task.projectId!==projectId)throw Error('The task changed project.');if(input.kind==='toggle'){if(input.expectedDone!=null&&task.done!==input.expectedDone)throw Error('The task changed. Refresh before updating it.');if(!task.done&&task.blockedBy){const dependency=await read<Task>(tx,'TASKS',task.blockedBy);if(!dependency.done)throw Error('Complete the prerequisite task first.');}task.done=!task.done;task.doneAt=task.done?now():null;await put(tx,context,'TASKS',task);}else{await put(tx,context,'TASKS',null,task.id);const dependents=await tx.query<{data:Task}>("SELECT data FROM admin_records WHERE collection='TASKS' AND data->>'projectId'=$1 AND data->>'blockedBy'=$2 FOR UPDATE",[projectId,task.id]);for(const dependent of dependents.rows){dependent.data.blockedBy=null;await put(tx,context,'TASKS',dependent.data);}}}
  const text=input.kind==='create'?'Task added: '+task.title:input.kind==='remove'?'Task removed: '+task.title:(task.done?'Done: ':'Reopened: ')+task.title;history(context,text,'internal');await put(tx,context,'PROJECTS',project);await audit(tx,context,'task',task.id,task.title,input.kind==='create'?'added':input.kind==='remove'?'removed':task.done?'completed':'reopened',task.assignee?'Responsible name: '+task.assignee:'');await event(tx,context,'project.task_'+input.kind,text,task.assignee?'Responsible name: '+task.assignee+'. Open the project for the actual task details.':'Open the project for the actual task details.','internal');return {context,task};});adopt(result.context);return {task:result.task,eventIds:result.context.eventIds};
}

export type NewProject=Omit<Project,'id'|'events'|'health'|'owner'|'channel'|'budget'> & Partial<Pick<Project,'health'|'owner'|'channel'|'budget'>>;
export async function createProjectRecord(input:{project:NewProject;newClient?:Omit<Client,'id'|'since'>}){
 const actor=await requireWorkspaceUser(true);if(actor.kind!=='staff')throw Error('Only the studio opens projects.');if(actor.role!=='owner'&&input.project.budget!=null)throw Error('Only the owner sets financial figures.');if(input.project.budget!=null&&(!Number.isSafeInteger(input.project.budget)||input.project.budget<0))throw Error('Choose a valid project budget.');if(input.project.due&&!Number.isFinite(new Date(input.project.due).getTime()))throw Error('Choose a valid deadline.');
 let clientCandidate:Client;
 if(input.newClient){const email=input.newClient.email.trim().toLowerCase(),phone=input.newClient.phone.replace(/\D/g,'').replace(/^(234|0)/,'');const duplicate=await db.query<{data:Client}>("SELECT data FROM admin_records WHERE collection='CLIENTS' AND data IS NOT NULL AND coalesce(data->>'mergedInto','')='' AND (($1<>'' AND lower(trim(data->>'email'))=$1) OR ($2<>'' AND regexp_replace(regexp_replace(data->>'phone','[^0-9]','','g'),'^(234|0)','','')=$2))",[email,phone]);clientCandidate=duplicate.rows[0]?.data||{...input.newClient,id:randomUUID(),since:now()};}
 else {const found=await db.query<{data:Client}>("SELECT data FROM admin_records WHERE collection='CLIENTS' AND id=$1",[input.project.clientId]);if(!found.rows[0]?.data)throw Error('Choose an existing client.');clientCandidate=found.rows[0].data;}
 const proposed:Project={...input.project,id:randomUUID(),clientId:clientCandidate.id,owner:input.project.owner||'',health:input.project.health||'On track',channel:input.project.channel||'Client portal',budget:input.project.budget??null,events:[]};
 const [recipients,internal]=await Promise.all([projectRecipientsForRecord(proposed,clientCandidate,'all'),projectRecipientsForRecord(proposed,clientCandidate,'internal')]);
 const result=await transaction(async tx=>{const project:Project={...proposed,events:[]};const active=await tx.query('SELECT 1 FROM "user" WHERE id=$1 AND role=$2 AND "deactivatedAt" IS NULL',[actor.userId,actor.role]);if(!active.rowCount)throw Error('Your account access has ended.');if(project.ownerIds?.length){const owners=await tx.query('SELECT id FROM "user" WHERE id=ANY($1::STRING[]) AND role IN (\'owner\',\'staff\') AND "deactivatedAt" IS NULL',[project.ownerIds]);if(owners.rowCount!==new Set(project.ownerIds).size)throw Error('Choose active studio leads.');}let client=clientCandidate;
  if(input.newClient){const email=client.email.trim().toLowerCase(),phone=client.phone.replace(/\D/g,'').replace(/^(234|0)/,'');const duplicates=await tx.query<{data:Client}>("SELECT data FROM admin_records WHERE collection='CLIENTS' AND data IS NOT NULL AND coalesce(data->>'mergedInto','')='' AND (($1<>'' AND lower(trim(data->>'email'))=$1) OR ($2<>'' AND regexp_replace(regexp_replace(data->>'phone','[^0-9]','','g'),'^(234|0)','','')=$2)) FOR UPDATE",[email,phone]);if(duplicates.rows[0]){client=duplicates.rows[0].data;if(client.id!==clientCandidate.id)throw Error('A matching client was just added. Refresh and choose the existing client.');}
  }else client=await read<Client>(tx,'CLIENTS',clientCandidate.id);
  if(client.archived||client.mergedInto)throw Error('Restore this client before opening a project.');project.clientId=client.id;if(!STAGES.includes(project.stage)||!bounded(project.title,240))throw Error('Choose a valid project title and stage.');
  const context:Context={actor,project,recipients,internal,eventIds:[],changed:[]};
  const existing=await tx.query("SELECT 1 FROM admin_records WHERE collection='CLIENTS' AND id=$1 AND data IS NOT NULL",[client.id]);if(input.newClient&&!existing.rowCount){await put(tx,context,'CLIENTS',client);await audit(tx,context,'client',client.id,client.company,'added');}
  history(context,'Project opened at '+project.stage,'client');await put(tx,context,'PROJECTS',project);await audit(tx,context,'project',project.id,project.title,'opened','at '+project.stage);await event(tx,context,'project.opened','Project opened: '+project.title,'Your project is now at '+project.stage+'. Open the project for shared work and next steps.','client');for(const userId of project.ownerIds||[])await event(tx,context,'project.lead_assigned','You are responsible for '+project.title,'Open the project for its scope and next steps.','internal',[{userId,email:'',name:'',role:'staff'}]);return context;
 });adopt(result);return {project:result.project,eventIds:result.eventIds};
}
