export type WorkspaceService = 'social'|'branding'|'web'|'apps'|'software'|'seo'|'ads';
export type ServiceField = { key:string; label:string; type?:'text'|'area'|'number'|'date'|'url'; required?:boolean; hint?:string };
export type ServiceKind = { key:string; label:string; service?:WorkspaceService; fields:ServiceField[]; decision?:'approve'|'accept'|'acknowledge'; states:string[] };
const f=(key:string,label:string,type:ServiceField['type']='text',required=false,hint?:string):ServiceField=>({key,label,type,required,hint});
const asset=f('assetUrl','Preview or file link','url',false,'Use an authorised project file or review link. Never paste keys or passwords.');
const deadline=f('due','Response or review due','date');
export const SERVICE_KINDS:ServiceKind[]=[
 {key:'post',label:'Content calendar post',service:'social',decision:'approve',states:['draft','internal_review','client_review','approved','scheduled','published','failed'],fields:[f('platform','Platform','text',true),f('caption','Caption','area',true),asset,f('plannedAt','Planned publishing time','date',true),f('timeZone','Timezone','text',true),f('reviewer','Client reviewer'),f('publicationUrl','Published post link','url'),f('publishedAt','Actual publication time','date'),f('evidence','Publication evidence / failure reason','area'),deadline]},
 {key:'direction',label:'Creative direction',service:'branding',decision:'accept',states:['draft','client_review','accepted','declined'],fields:[f('strategy','Strategy and rationale','area',true),f('logo','Logo applications','area'),f('colours','Colour values and use','area'),f('typography','Typeface choices and use','area'),asset,deadline]},
 {key:'design_round',label:'Design review round',service:'branding',decision:'approve',states:['draft','internal_review','client_review','approved','changes_requested'],fields:[f('round','Review round','number',true),f('changes','What changed','area',true),f('context','Page / frame / artwork context'),asset,deadline]},
 {key:'uat',label:'Website test or issue',service:'web',states:['open','testing','passed','failed','resolved','reopened'],fields:[f('page','Page or journey','text',true),f('steps','Steps to reproduce or test','area',true),f('expected','Expected result','area',true),f('actual','Actual result','area'),f('device','Device and browser'),f('evidence','Evidence or issue reference','area'),asset]},
 {key:'launch',label:'Website launch permission',service:'web',decision:'approve',states:['draft','client_review','approved','launched'],fields:[f('checks','Completed launch checks and outstanding risks','area',true),f('ownership','Domain / hosting ownership','area',true),f('rollback','Rollback and responsible contact','area',true),f('evidence','Actual launch evidence','area'),asset,deadline]},
 {key:'build',label:'App test build',service:'apps',decision:'approve',states:['draft','testing','client_review','approved','submitted','rejected','store_approved','released'],fields:[f('build','Build and version','text',true),f('devices','Supported devices and operating systems','area',true),f('install','Install instructions','area',true),f('changes','Changes and what to test','area',true),f('store','Store submission / decision reference'),f('evidence','Release or rejection evidence','area'),asset,deadline]},
 {key:'app_issue',label:'App issue',service:'apps',states:['open','testing','resolved','reopened'],fields:[f('build','Build and version','text',true),f('device','Device and operating system','text',true),f('steps','Steps to reproduce','area',true),f('expected','Expected result','area',true),f('actual','Actual result','area',true),asset]},
 {key:'milestone',label:'Software milestone',service:'software',decision:'accept',states:['draft','in_progress','client_review','accepted','changes_requested','released'],fields:[f('requirements','Agreed requirements','area',true),f('acceptance','Acceptance criteria','area',true),f('results','Actual test results','area'),f('dependencies','Dependencies and required access','area'),f('evidence','Release evidence','area'),asset,deadline]},
 {key:'ai_evaluation',label:'AI evaluation and limits',service:'software',decision:'accept',states:['draft','testing','client_review','accepted','changes_requested'],fields:[f('dataUse','Permitted data and use','area',true),f('examples','Test examples and expected outcomes','area',true),f('results','Measured outcomes and limitations','area',true),f('escalation','Refusal / human escalation owner','area',true),f('costLimit','Approved monthly running-cost limit (naira)','number',true),asset,deadline]},
 {key:'article',label:'SEO content review',service:'seo',decision:'approve',states:['draft','internal_review','client_review','approved','published'],fields:[f('outline','Outline and search intent','area',true),f('facts','Facts needing client confirmation','area'),f('page','Intended page'),f('checks','Editorial and technical checks','area'),asset,f('publicationUrl','Published page','url'),f('evidence','Publication evidence','area'),deadline]},
 {key:'report',label:'Period report',states:['draft','shared','acknowledged'],decision:'acknowledge',fields:[f('periodStart','Period starts','date',true),f('periodEnd','Period ends','date',true),f('sources','Sources and measurement method','area',true),f('metrics','Metrics, values and interpretation','area',true),f('next','Next priorities','area',true),asset]},
 {key:'creative',label:'Campaign creative',service:'ads',decision:'approve',states:['draft','internal_review','client_review','approved','changes_requested'],fields:[f('audience','Audience and exclusions','area',true),f('copy','Creative copy','area',true),f('destination','Landing-page destination','url',true),f('tracking','Tracking checks','area'),asset,deadline]},
 {key:'budget',label:'Advertising spend approval',service:'ads',decision:'accept',states:['draft','client_review','accepted','declined'],fields:[f('amount','Maximum spend (naira)','number',true),f('periodStart','Period starts','date',true),f('periodEnd','Period ends','date',true),f('platform','Platform','text',true),f('creativeId','Approved creative record ID','text',true),f('terms','Limit, exclusions and approval conditions','area',true),deadline]},
 {key:'campaign',label:'Campaign launch / delivery',service:'ads',states:['draft','platform_review','running','paused','rejected','ended'],fields:[f('creativeId','Approved creative record ID','text',true),f('budgetId','Accepted budget record ID','text',true),f('evidence','Platform reference and actual delivery evidence','area',true),f('tracking','Tracking result','area',true),f('destination','Landing-page destination','url'),deadline]},
 {key:'request',label:'Content or access request',decision:'acknowledge',states:['open','supplied','received','closed'],fields:[f('description','What is needed and why','area',true),f('responsible','Person responsible','text',true),f('reviewer','Studio reviewer','text',true),f('response','Client response','area'),deadline]},
 {key:'change',label:'Scope change',decision:'accept',states:['draft','client_review','accepted','declined','withdrawn'],fields:[f('description','Requested change','area',true),f('cost','Additional cost (naira)','number',true),f('dateEffect','Effect on agreed dates','area',true),f('affected','Affected work and departments','area',true),deadline]},
 {key:'handover',label:'Final package and handover',decision:'acknowledge',states:['draft','shared','acknowledged'],fields:[f('files','Final files and their purpose','area',true),f('ownership','Account ownership and access','area',true),f('training','Training / recording / guide','area',true),f('openItems','Open items and responsible people','area',true),f('support','Agreed support terms and end date','area',true),asset]},
 {key:'renewal',label:'Next service period',decision:'accept',states:['draft','client_review','accepted','declined'],fields:[f('scope','Next period scope','area',true),f('cost','Price (naira)','number',true),f('periodStart','Period starts','date',true),f('periodEnd','Period ends','date',true),f('terms','Term and cancellation details','area',true),deadline]}
];
export function kindsFor(service:WorkspaceService){return SERVICE_KINDS.filter(k=>!k.service||k.service===service);}
export type ServiceItem={id:string;project_id:string;service:WorkspaceService;kind:string;title:string;visibility:'internal'|'shared';state:string;revision:number;version:number;data:Record<string,string>;updated_at:string;};
export type ServiceDecision={version:number;decision:string;actor_name:string;note:string;created_at:string};
export type ServiceNote={id:string;version:number;actor_name:string;body:string;context:string;resolved:boolean;created_at:string};
export type ServiceVersion={visibility:'internal'|'shared';version:number;title:string;data:Record<string,string>;created_at:string};
export type ServiceActivity={version:number;actor_name:string;action:string;details:Record<string,string>;created_at:string};
export type ServiceRecord=ServiceItem & {readOnlyVersion?:boolean;decisions:ServiceDecision[];notes:ServiceNote[];versions:ServiceVersion[];activity:ServiceActivity[]};
export function parseServiceData(kind:ServiceKind,source:Record<string,unknown>):Record<string,string>{
 const out:Record<string,string>={};
 for(const field of kind.fields){const raw=source[field.key];if(raw!==undefined&&typeof raw!=='string')throw Error('Invalid '+field.label+'.');const value=(raw as string||'').trim();if(value.length>12000)throw Error(field.label+' is too long.');if(field.required&&!value)throw Error(field.label+' is required.');if(value&&field.type==='number'&&(!/^\d+(\.\d{1,2})?$/.test(value)||Number(value)>1e12))throw Error(field.label+' must be a positive number.');if(value&&field.type==='url'){let url:URL;try{url=new URL(value);}catch{throw Error(field.label+' must be a valid link.');}if(url.protocol!=='https:'||url.username||url.password)throw Error(field.label+' must use HTTPS without embedded credentials.');}if(value&&field.type==='date'&&!Number.isFinite(Date.parse(value)))throw Error(field.label+' must be a valid date.');out[field.key]=value;}
 if(out.periodStart&&out.periodEnd&&Date.parse(out.periodEnd)<Date.parse(out.periodStart))throw Error('Period end must follow its start.');
 return out;
}
export function checkState(kind:ServiceKind,state:string,data:Record<string,string>,approved:boolean){
 if(!kind.states.includes(state))throw Error('This state is not valid for this type of work.');
 if(['scheduled','published','launched','released','running'].includes(state)&&!approved)throw Error('Record approval of this exact version first.');
 if(['published','launched','released','running'].includes(state)&&!data.evidence)throw Error('Record actual delivery evidence; a planned date is not delivery.');
 if(kind.key==='post'&&state==='published'&&(!data.publicationUrl||!data.publishedAt))throw Error('A published post needs its live link and actual time.');
 if(kind.key==='post'&&state==='failed'&&!data.evidence)throw Error('Record why publishing failed.');
}
