"use client";
import {useEffect,useRef,useState} from 'react';
import {Plus,Trash2} from 'lucide-react';
import {Fields,Field,Select,Area,Hidden,useFieldError} from '@/components/admin/form';
import {SUPPORTED_CURRENCIES,type PaymentAccountSnapshot} from '@/lib/money/currency';
import {useDirtyPing} from './kit';
import {ask} from '@/components/admin/confirm';
export function PaymentAccounts({initial}:{initial:PaymentAccountSnapshot[]}){
 const [accounts,setAccounts]=useState(initial),box=useRef<HTMLDivElement>(null),ping=useDirtyPing(),error=useFieldError('finance.accounts');
 useEffect(()=>{const form=box.current?.closest('form');const reset=()=>setAccounts(initial);form?.addEventListener('reset',reset);return()=>form?.removeEventListener('reset',reset);},[initial]);
 const change=(id:string,key:keyof PaymentAccountSnapshot,value:string)=>{setAccounts(rows=>rows.map(row=>row.id===id?{...row,[key]:value}:row));ping();};
 return <div ref={box} className="adSetPad"><p>Choose one of these accounts when raising an invoice or quote. The document keeps its own copy, so a later settings change does not rewrite an issued document.</p><Hidden name="finance.accounts" value={JSON.stringify(accounts)}/>{error?<p role="alert" className="ad__fe">{error}</p>:null}{accounts.map((account,index)=><section key={account.id} className="ad__panel" style={{margin:'1.25rem 0',padding:'1rem'}} aria-label={`Payment account ${index+1}`}><Fields><Field name={`account-${account.id}-label`} label="Account label" required value={account.label} onChange={event=>change(account.id,'label',event.target.value)} hint="A short name for the account picker."/><Select name={`account-${account.id}-currency`} label="Currency" required value={account.currency} onChange={value=>change(account.id,'currency',value)} options={SUPPORTED_CURRENCIES.map(item=>({...item}))}/><Field name={`account-${account.id}-bank`} label="Bank or payment institution" required value={account.bankName} onChange={event=>change(account.id,'bankName',event.target.value)}/><Field name={`account-${account.id}-name`} label="Account name" required value={account.accountName} onChange={event=>change(account.id,'accountName',event.target.value)}/><Field name={`account-${account.id}-number`} label="Account number or IBAN" required value={account.accountNumber} onChange={event=>change(account.id,'accountNumber',event.target.value)} maxLength={80}/><Area name={`account-${account.id}-instructions`} label="Transfer instructions (optional)" value={account.instructions||''} onChange={event=>change(account.id,'instructions',event.target.value)} rows={2} hint="Routing / SWIFT details or the reference the client should use. Never add passwords or keys."/></Fields><button type="button" className="ad__btn" onClick={async()=>{if(await ask(`Remove ${account.label||'this payment account'} from future document choices? Issued copies keep their details.`,{verb:'Remove account'})){setAccounts(rows=>rows.filter(row=>row.id!==account.id));ping();}}}><Trash2 aria-hidden/>Remove account</button></section>)}<button type="button" className="ad__btn" disabled={accounts.length>=10} onClick={()=>{setAccounts(rows=>[...rows,{id:crypto.randomUUID(),label:'',currency:'NGN',bankName:'',accountName:'',accountNumber:''}]);ping();}}><Plus aria-hidden/>Add payment account</button>{accounts.length>=10?<p>Ten accounts are available. Remove an unused account to add another.</p>:null}</div>;
}
