(function(){
'use strict';
const C=window.WDC_COMPONENTS,S={role:'studio',view:'overview',service:'social',tab:'overview',dark:false};
const names={social:'Social media',branding:'Branding',web:'Website',apps:'Mobile app',software:'Software & AI',seo:'SEO',ads:'Paid advertising'};
const e=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=n=>C.icons[n]||C.icons.Info;
const button=(label,action,extra='')=>`<button class="ad__btn" data-action="${e(action)}" ${extra}>${label}</button>`;
const pill=(text,tone='flat')=>`<span class="ad__pill ad__pill--${({neutral:'flat',warning:'warn',success:'good',danger:'bad'}[tone]||tone)}">${e(text)}</span>`;
const panel=(title,body)=>C.panel.replace('__TITLE__',e(title)).replace('__CONTENT__',`<div class="preview-panel-body">${body}</div>`);
const dialog=document.getElementById('preview-dialog');
function open(title,body){document.getElementById('dialog-title').textContent=title;document.getElementById('dialog-body').innerHTML=body;if(!dialog.open)dialog.showModal();}
function close(){dialog.close();}
window.WDC_UI={escape:e,icon,button,pill,panel,open,close,role:()=>S.role};
function head(title,text){return `<div class="ad__head"><div><p class="eyebrow">Paper &amp; Pine · Fictional sample</p><h1>${title}</h1><p>${text}</p></div>${button('Explain this screen','explain')}</div>`;}
function overview(){return head(S.role==='studio'?'Keep client work moving':'Your work with WDC',S.role==='studio'?'See the next decision, the person responsible and the work waiting on it.':'Your next steps, shared work and recorded decisions in one place.')+`<div class="grid-3">${panel('Needs a decision','<p class="metric">'+window.WDC_SERVICES.summary().reviews+'</p><p>Sample social posts needing a decision</p>'+button('Review the posts','project','data-service="social" data-tab="review"'))}${panel('Waiting for content','<p class="metric">'+window.WDC_SERVICES.summary().requests+'</p><p>Sample website requests ? due 14 October</p>'+button('Open website','project','data-service="web"'))}${panel(S.role==='studio'?'Team handover':'Your next meeting',S.role==='studio'?'<p class="metric">1</p><p>Branding → Website needs acceptance</p>'+button('Read the handover','navigate','data-view="team"'):'<p class="metric">14 Oct</p><p>Sample review meeting · 10:00 · your timezone</p>'+button('Meeting details','meeting'))}</div>`+panel('Projects',`<div class="table-wrap"><table><thead><tr><th scope="col">Work</th><th scope="col">Next step</th><th scope="col">Responsible</th><th scope="col">Open</th></tr></thead><tbody>${Object.entries(names).map(([key,name])=>`<tr><th scope="row">${name}<small class="meta">${key==='ads'?'Additional campaign example':'Sample service workspace'}</small></th><td>${({social:'Review caption and visual',branding:'Choose a direction',web:'Supply photographs, test staging',apps:'Test build, review store release',software:'Accept milestone and evaluate AI',seo:'Review recommendations and report',ads:'Approve creative and spending limit'})[key]}</td><td>${key==='social'||key==='branding'?'Client reviewer':'Client and assigned lead'}</td><td>${button('Open work','project',`data-service="${key}"`)}</td></tr>`).join('')}</tbody></table></div>`)+panel('What the client sees','<p>Only deliberately shared work, client requests, decisions, billing and support. Internal drafts, team discussions and department handovers remain private.</p><div class="actions">'+button('Open inbox','navigate','data-view="inbox"')+(S.role==='studio'?button('See all communication flows','navigate','data-view="flows"'):'')+'</div>');}
const explanation={overview:['This is the starting page.','The cards show the next decisions and missing inputs. The projects table opens the same workspace for each service. One client keeps one portal, even when they buy several services. The numbers are fictional examples.','The studio sees team handovers. Clients see their shared work and meetings. A real implementation must check the user’s project role on the server.'],inbox:['This is the person’s action inbox.','Needs me shows decisions, replies and assignments. All activity keeps the history. Summaries group routine progress. Open a message to see the reason, deadline and next action. Mark read clears an action from the sample list.','Email is a pointer back to the record. Reading an email is not the same as approving work. Each person controls optional email preferences.'],team:['This is an internal team workspace.','A handover contains the approved files, past decision, open risk and next task. The receiving lead accepts it before dependent work starts. Assign to Jo shows named ownership. Complete sample task records completion.','Internal notes stay with the assigned team. Client update is a separate sharing action. In production, sharing must be explicit and permission checked.'],flows:['This is the full communication inventory.','Search by service, event or recipient. Exists means a source path was found; Partial means the flow is incomplete; Proposed means new work is needed. It does not mean a message reached someone’s inbox.','The table includes client updates, assignments, reviews, deadlines, billing, support, scheduling, releases, handovers, renewals and service-specific exceptions. Build durable events, correct recipients and safe retry before adding more emails.'],project:['This is the service workspace.','Overview gives the next step, responsibilities and scope. Work shows the deliverables this service actually needs. Review records a decision against an exact version, with notes that can be resolved or reopened. Handover records the final package, ownership, open items and continuation.','Approving version 2 does not approve version 3. A scope change has a separate cost and date decision. An advertising budget has separate approval from its creative. Testing and launch permission are separate. Every action here changes only this sample.']};
function explain(){const x=explanation[S.view]||explanation.overview;open('This screen, in plain English',`<p><strong>${x[0]}</strong></p><p>${x[1]}</p><p>${x[2]}</p>${panel('What is real, and what is proposed','<p>The frame, logo, colours, panels and icons come from the WDC dashboard. The new workflows and all records shown here are a design proposal. Source-audited email coverage is labelled individually. Nothing is sent, charged, scheduled or published.</p>')}<p>Use Studio and Client portal to compare responsibilities. Use the theme button to check the dark design. The same tables stay tables on a phone.</p>`);}
function project(){return C.profile.replace('__PROJECT_TITLE__',e(names[S.service]+' workspace')).replace('__PROJECT_LINES__','Paper &amp; Pine ? Fictional sample ? '+e(names[S.service])).replace('__PROJECT_ACTIONS__',button('Explain this screen','explain')).replace('__PROJECT_VISIBILITY__',S.role==='client'?'Shared work only':'Internal and shared').replace('__PROJECT_TRACK__','<div class="ad__stageTrack"><ol aria-label="Sample project progress"><li class="is-done"><span></span><small>Brief agreed</small></li><li class="is-now"><span></span><small>Work and review</small></li><li><span></span><small>Handover</small></li></ol></div>')+`<div class="service-tabs" aria-label="Service examples">${Object.entries(names).map(([key,label])=>button(label,'project',`data-service="${key}" aria-pressed="${S.service===key}"`)).join('')}</div><div class="work-tabs" aria-label="Project sections">${['overview','work','review','handover'].map(tab=>button(({overview:'Overview',work:'Work',review:'Review',handover:'Handover'})[tab],'tab',`data-tab="${tab}" aria-pressed="${S.tab===tab}"`)).join('')}</div><p class="meta">${pill('Proposed workflow','brand')} Sample permissions: ${S.role==='client'?'client reviewer — shared work only':'studio lead — internal and shared work'} · Actions are local to this preview.</p>`+window.WDC_SERVICES.render(S.service,S.tab);}
function render(){
const content=S.view==='project'?project():['inbox','team','flows'].includes(S.view)?window.WDC_COMMUNICATIONS.render(S.view):overview();
document.getElementById('app').innerHTML=(S.role==='client'?C.client:C.admin).replace('__PAGE__',C.demo+content).replace(/\bad-btn\b/g,'ad__btn');
const app=document.getElementById('app');
app.querySelectorAll('a').forEach(a=>{const href=a.getAttribute('href')||'';a.removeAttribute('href');a.setAttribute('role','button');a.tabIndex=0;a.dataset.action='navigate';a.dataset.view=href.includes('settings')||href.includes('email')?'flows':href.includes('projects')?'project':'overview';if(/money|blog|users|billing|support/.test(href)){a.dataset.action='existing-page';a.dataset.label=a.textContent.trim();}if(S.role==='client'&&a.dataset.view==='flows')a.dataset.view='inbox';});
app.querySelectorAll('.ad__topIcon,.ad__account,.ad__search').forEach(b=>{b.dataset.action=b.classList.contains('ad__themeBtn')?'theme':b.getAttribute('aria-label')==='Notifications'?'navigate':b.classList.contains('ad__search')?'search':'account';if(b.dataset.action==='navigate')b.dataset.view='inbox';});
app.querySelectorAll('[aria-label="Open the menu"],[aria-label="Collapse sidebar"],[aria-label="Expand sidebar"]').forEach(b=>{b.dataset.action='menu';if(b.getAttribute('aria-label')!=='Open the menu')b.disabled=true;}); const top=app.querySelector('.ad__topbar');if(top){const menu=document.createElement('button');menu.className='ad__iconButton preview-menu';menu.dataset.action='menu';menu.setAttribute('aria-label','Open navigation');menu.innerHTML=icon('Menu');top.prepend(menu);}
app.querySelectorAll('.adDrawer').forEach(d=>d.remove());
app.querySelectorAll('.ad__sideFoot button').forEach(b=>b.disabled=true);
const title=app.querySelector('.ad__topTitle');if(title)title.textContent=S.role==='client'?'Client portal':'Studio workspace';
document.getElementById('theme-toggle').innerHTML=icon(S.dark?'Sun':'Moon');document.getElementById('help-toggle').innerHTML=icon('Info');
document.querySelectorAll('.preview-controls [data-action^="role-"]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.action==='role-'+S.role));
if(S.role==='studio'){const main=app.querySelector('main');main.insertAdjacentHTML('afterbegin',`<div class="work-tabs" aria-label="Studio workspace sections">${[['overview','Overview'],['inbox','Inbox'],['team','Team & handovers'],['flows','Communication coverage']].map(([v,l])=>button(l,'navigate',`data-view="${v}" aria-pressed="${S.view===v}"`)).join('')}</div>`);}
}
let toastTimer;function toast(text){clearTimeout(toastTimer);document.getElementById('toast').textContent=text;toastTimer=setTimeout(()=>document.getElementById('toast').textContent='',3200);}
function action(el){const a=el.dataset.action;if(!a||el.disabled)return;
if(a==='theme'){S.dark=!S.dark;document.documentElement.classList.toggle('dark',S.dark);render();return;}
if(a==='explain'){explain();return;}if(a==='close-dialog'){close();return;}
if(a==='role-studio'||a==='role-client'){S.role=a.slice(5);S.view='overview';S.tab='overview';close();render();window.scrollTo({top:0,behavior:'instant'});return;}
if(a==='navigate'){S.view=el.dataset.view||'overview';if(el.dataset.service){S.view='project';S.service=el.dataset.service;S.tab=el.dataset.tab||'overview';}if(S.role==='client'&&['team','flows'].includes(S.view))S.view='inbox';close();render();window.scrollTo({top:0,behavior:'instant'});return;}
if(a==='project'){S.service=el.dataset.service||S.service;S.tab=el.dataset.tab||'overview';S.view='project';close();render();window.scrollTo({top:0,behavior:'instant'});return;}
if(a==='tab'){S.tab=el.dataset.tab;render();return;}
if(a==='menu'){const side=document.querySelector('.ad__side');open('Navigation',side?side.innerHTML:'');document.getElementById('dialog-body').querySelectorAll('a').forEach(x=>x.dataset.action='navigate');return;}
if(a==='meeting'){open('Sample review meeting','<p>14 October · 10:00 · your timezone</p><p>Review the approved brief and remaining decisions. Booking, cancellation and rescheduling would use the existing Cal.com integration. This preview makes no booking.</p>');return;}
if(a==='search'){S.view='flows';if(S.role==='client')S.view='project';render();return;}
if(a==='existing-page'){open(el.dataset.label,'<p>This existing page is outside the interactive proposal. The preview covers client work, service-specific reviews, team handovers and communications. Use the workspace sections to inspect those changes.</p>');return;}if(a==='account'){open('Sample account','<p>This is a fictional review session. Use the top controls to switch between the studio and client view. It does not grant access to any real account.</p>');return;}

const result=a.startsWith('comm-')?window.WDC_COMMUNICATIONS.handle(a,el):a.startsWith('service-')?window.WDC_SERVICES.handle(a,el):null;
if(result){const active=document.activeElement,id=active?.id,start=active?.selectionStart;render();if(id&&document.getElementById(id)){document.getElementById(id).focus();if(typeof start==='number'&&id==='comm-search')document.getElementById(id).setSelectionRange(start,start);}if(a==='comm-pref-save')toast('Saved in this preview');else if(/accept|assign|complete|save-note|supply|approve|resolve|handover|renewal|retry-post|pass-test|grant-launch|comm-note/.test(a))toast('Updated in this preview');}
}
document.addEventListener('click',ev=>{const el=ev.target.closest('[data-action]');if(el&&!el.matches('input,textarea')){ev.preventDefault();action(el);}});
document.addEventListener('input',ev=>{if(ev.target.dataset.action==='comm-search')action(ev.target);});
document.addEventListener('change',ev=>{if(ev.target.type==='checkbox'&&ev.target.dataset.action)action(ev.target);});
document.addEventListener('keydown',ev=>{if(ev.key==='Enter'&&ev.target.matches('a[role="button"]'))action(ev.target);});
render();
})();
