/* Local design preview. All records are fictional; no messages or provider calls. */
(function () {
  'use strict';
  const initial = () => ({ service: 'social', version: 2, decision: '', history: [], notes: [], requestDone: false, change: '', handover: false, post: 'Awaiting approval', budget: false, launch: false, release: 'Submitted', selected: 'Direction B', test: false, renewal: false, expanded: false, schedule: '14 October · 10:00', failedPost: 'Publishing failed' });
  let state = initial();
  const records = { social: state };
  const names = {social: 'Social media management', branding: 'Branding & design', web: 'Website & ecommerce', apps: 'Mobile app', software: 'Custom software & AI', seo: 'SEO & AI visibility', ads: 'Paid advertising'};
  function ui() { return window.WDC_UI; }
  function client() { return !!ui().role && ui().role()==='client'; }
  const studioActions = new Set(['newversion','schedule','move-post','repair-post','retry-post','test','pass-test','release']);
  const clientDecisions = new Set(['approve','approve-budget','grant-launch','handover','accept-change','decline-change','direction-a','direction-b','supply','renewal']);
  function e(value) { return ui().escape(String(value)); }
  function b(label, action, extra) { if(client() && (studioActions.has(action)||action.startsWith('resolve-note-'))) return ''; if(!client() && clientDecisions.has(action)) return ''; return ui().button(label, 'service-' + action, extra || ''); }
  function p(text, tone) { return ui().pill(text, tone || 'neutral'); }
  function box(title, body) { return ui().panel(title, body); }
  function row(title, detail, status, action) { return '<div class="item"><div><strong>' + title + '</strong><p class="meta">' + detail + '</p></div><div class="actions">' + (status || '') + (action || '') + '</div></div>'; }
  function table(headers, rows) { return '<div class="table-wrap"><table><thead><tr>' + headers.map(h => '<th scope="col">' + h + '</th>').join('') + '</tr></thead><tbody>' + rows.map(r => '<tr>' + r.map((c,i) => (i ? '<td>' : '<th scope="row">') + c + (i ? '</td>' : '</th>')).join('') + '</tr>').join('') + '</tbody></table></div>'; }
  function notice(text) { return '<div class="notice">' + text + '</div>'; }
  const data = {
    social: {next: 'Review the autumn collection post, version 2. Publishing starts only after approval.', deliverable: 'Autumn collection · Instagram carousel', context: 'Slide 3 · caption and product order', work: () => box('October content calendar', table(['Post / platform','Planned time','Version / status','Action'], [
      ['Autumn collection · Instagram',e(state.schedule),'v'+state.version+' '+p(state.post,'warning'),b('Open post','post')],
      ...(!client()?[['Meet the makers · LinkedIn','16 October · 09:00','v1 '+p('Internal review'),b('View details','detail')]]:[]),
      ['Care guide · Instagram','18 October · 12:00','v1 '+p('Published','success'),b('View publication','published-care')],
      ['Weekend story · Instagram','20 October · 10:00','v1 '+p(state.failedPost,state.failedPost==='Published'?'success':'danger'),b(state.failedPost==='Published'?'View publication':'See failure',state.failedPost==='Published'?'published-weekend':'failure')]
    ])) + box('Review, then publish', '<p>Every shared post has its own visual, caption, platform, timezone, reviewer and publication record. Approval applies to the version shown. The studio schedules posts, repairs publishing problems and shares new versions; internal drafts stay private.</p><div class="actions">'+b('Open autumn post','post')+b('Change planned time','schedule')+'</div>')},
    branding: {next:'Choose a direction, then review the identity round against the agreed brief.',deliverable:'Paper & Pine identity · round 2',context:'Logo lockup · page 4 of the identity PDF',work:() => box('Creative direction',row('Direction A · expressive','Playful wordmark and bright editorial layout',p('Option'),b('Choose A','direction-a'))+row('Direction B · calm','Warm paper colours and a precise wordmark',p(state.selected === 'Direction B' ? 'Selected' : 'Option','success'),b('Choose B','direction-b'))+notice('Current choice: '+state.selected+'. Selecting a direction does not approve final artwork.'))+box('Review rounds and final files',table(['Round','Contents','State'],[['Round 1','Two directions and strategy','Decision recorded'],['Round 2','Logo family, colour and type','v'+state.version+' · client review'],['Final package','SVG, print PDF, PNG, editable source, usage guide','Ready after final sign-off']]))},
    web: {next:'Supply the remaining product content, then test the staging shop before launch.',deliverable:'Paper & Pine shop · staging release 2',context:'Product page / checkout · browser and steps',work:() => box('Website inputs',row('Product photographs','Client supplies five remaining images · due 12 October',p(state.requestDone?'Received':'Needed','warning'),b('Supply content','request'))+row('Domain & hosting','Registered in client name; studio access documented',p('Ready','success')))+box('Staging and launch',table(['Check','Owner','Result'],[['Homepage design','Client approver','Approved v1'],['Checkout test','Client + studio',state.test?'Passed in preview':'Needs testing'],['Contact receipt','Studio','Passed'],['Keyboard and phone review','Studio','Passed'],['Launch permission','Client decision-maker',state.launch?'Granted in preview':'Not yet granted']])+'<div class="actions">'+b('Record checkout test','test')+b('Review launch permission','launch')+'</div>'+notice('The studio records testing evidence and shares the results. Design approval and functional acceptance are separate. Launch requires the agreed tests and permission.'))},
    apps: {next:'Test build 0.9.2 and approve store materials. Store approval and public release are separate. The studio records test results and store updates; you review shared builds and report issues.',deliverable:'Paper & Pine app · build 0.9.2 (42)',context:'Android 15 · product screen · steps and screenshot',work:() => box('Test builds',row('Build 0.9.2 (42)','Demo install instructions · test sign-in, basket and notifications',p(state.test?'Testing recorded':'Ready to test','warning'),b('Open test checklist','test'))+row('Build 0.9.1 (41)','Previous build retained with its feedback',p('History')))+box('Store release',row('Listing, screenshots and privacy information','Approval recorded against materials v2',p('Approved','success'))+row('Current submission',state.release==='Released'?'Public release recorded in this preview':'Store decision is not public availability',p(state.release,'warning'),b('Advance sample release','release')))},
    software: {next:'Accept milestone 2 using the agreed checks. Treat additional features as scope changes.',deliverable:'Order assistant · milestone 2 · release candidate 2',context:'Acceptance check AC-04 · human handoff when uncertain',work:() => box('Milestones & requirements',table(['Milestone','Acceptance checks','State'],[['1 · customer records','Import preserves IDs; roles restrict access','Accepted'],['2 · order assistant','Correct answers, refusal and human handoff',state.test?'Checks recorded':'Client acceptance needed; studio records checks'],['3 · production release','Backup, rollback, training and runbook','Waiting on milestone 2']])+'<div class="actions">'+b('Record acceptance checks','test')+b('Request another feature','change')+'</div>')+box('AI checks and operating costs',row('Evaluation set v2','30 fictional test examples: accuracy, refusal, escalation and permitted data',p('Review required','warning'),b('View checks','ai'))+row('Running-cost limit','Sample limit ₦40,000 / month; change needs separate acceptance',p('Agreed'))+notice('The client summary includes known limitations, correction and human escalation. No guarantee is implied by a demo.'))},
    seo: {next:'Approve the care-guide article and review the period report with its source and next actions.',deliverable:'Care-guide article · version 2',context:'Section 2 · search intent and factual wording',work:() => box('Content and technical work',row('Care-guide article','Keyword-to-page plan · editor reviewed · client approval needed',p('Review v'+state.version,'warning'),b('Review article','detail'))+row('Duplicate page canonical','Implementation owned by studio; no client decision needed',p('Completed','success'))+row('Indexing problem','Sample excluded URL needs technical investigation',p('Assigned','warning')))+box('Period report · September 2026',table(['Metric','Sample value','Source / period'],[['Search clicks','1,240','Fictional Search Console sample · 1–30 Sep'],['Search impressions','31,800','Fictional Search Console sample · 1–30 Sep'],['Enquiries','18','Fictional analytics sample · 1–30 Sep'],['AI mentions','3 of 20 sampled prompts','Manual sample · 30 Sep; not a search rank']])+notice('These figures are fictional examples, with separate sources. Next priorities: fix excluded page, publish approved guide, review enquiries.'))},
    ads: {next:'Approve the creative and the spending limit separately. Neither decision automatically launches the campaign.',deliverable:'Autumn campaign · creative version 2',context:'Carousel slide 2 · headline and landing page',work:() => box('Campaign approvals',row('Creative and landing page','Exact creative v'+state.version+'; visual, copy and destination reviewed',p(state.decision==='Approved'?'Approved':'Needs approval','warning'),b('Review creative','detail'))+row('Campaign spending limit','Sample maximum ₦150,000 · 15–31 October',p(state.budget?'Approved':'Separate decision needed','warning'),b('Review spending','budget'))+notice('Creative approval does not authorise a higher budget. Launch requires both decisions and platform acceptance.'))+box('Delivery and reporting',row('Autumn campaign','Platform review before delivery; tracking check before launch',p(state.launch?'Running in preview':'Not launched'),b('Review launch','launch'))+row('Tracking issue','Sample conversion event unavailable; campaign lead notified',p('Needs action','danger'))+row('Results report','Spend, enquiries and source shown for the agreed period',p('Due 1 November')))}
  };
  function overview(d) { return box('Your next step', '<p>'+d.next+'</p><div class="actions">'+b('Open current work','detail')+b('Review a request','request')+'</div>')+box('People and plan',row('Paper & Pine','Fictional client · Mira Cole is the approver; Casey Reed is the billing contact',p('Sample'))+row(names[state.service],'Ari leads this project · service team owns the work · reviews due 13 October',p('In progress','warning')))+box('Updates and decisions',row('New version ready','Studio shared v'+state.version+' with a summary of changes',p('Shared'))+row('Deadline and scope changes','A reason, cost/date effect and a recorded decision accompany each change',p(state.change || 'No decision'),b('View scope change','change')))+notice('Concept preview only. All people, dates, files, metrics and actions here are fictional. Nothing is sent or connected to a live account.'); }
  function review(d) { return box('Review the exact version',(!client()?notice('Mira Cole is the client reviewer. Switch to Client portal to approve, request a scope decision or confirm receipt.'):'' )+'<div class="item"><div><strong>'+d.deliverable+'</strong><p class="meta">Version '+state.version+' · '+d.context+' · due 13 October</p></div>'+p(state.decision||'Awaiting your decision','warning')+'</div><p>Changes in this version: clearer wording, revised ordering and the corrections from round 1. Previous versions and their decisions remain in history.</p><div class="actions">'+b('View work','detail')+b('Approve version '+state.version,'approve')+b('Request changes','notes')+b('Try a newer version','newversion')+'</div>')+box('Review conversation','<div class="item"><div><strong>Ari · studio</strong><p>We have addressed your earlier note. Please check the detail above before approving.</p></div></div>'+state.notes.map((n,index)=>row('Mira · client',e(n.text),p(n.done?'Addressed':'Needs attention',n.done?'success':'warning'),b(n.done?'Reopen note':'Mark addressed',(n.done?'reopen-note-':'resolve-note-')+index))).join('')+(state.notes.length?'':notice('No new review notes. Add a note with enough context for the team to act.'))+'<div class="actions">'+b('Add review note','notes')+b('Ask a question','question')+'</div>')+box('Decision history',row('Version 1','Mira Cole requested changes · 8 October · earlier note retained',p('Changes requested'))+state.history.map(h=>row('Version '+h.version,'Earlier sample decision retained',p(h.decision))).join('')+row('Version '+state.version,'Current sample version · decision applies only to this version',p(state.decision||'Pending'))); }
  function handover() { return box('Handover package',table(['Item','Purpose','State'],[['Final files and version list','Know which files to use and where','Ready'],['Training recording and guide','Use and maintain the delivered work','Ready'],['Account ownership and access','Client ownership and responsible contacts','Review needed'],['Open items and support terms','Known issues, next steps and agreed support','Ready']]))+box('Acknowledge handover','<p>Confirm receipt after checking the files, guide and ownership list. This acknowledgement is separate from approval of any outstanding work.</p>'+p(state.handover?'Received in preview':'Awaiting acknowledgement','warning')+'<div class="actions">'+b('Inspect sample package','package')+b('Acknowledge receipt','handover')+'</div>')+box('Ongoing service and renewal',row('Next period / support end','Sample review date 1 November · term and cost visible before a decision',p(state.renewal?'Requested':'Not renewed'),b('Request continuation','renewal'))+notice('A reminder would go to the responsible contact according to their preferences. No automatic renewal or charge is demonstrated.')); }
  function render(service, tab) { if (data[service]) { if(!records[service]) records[service]=initial(); state=records[service];state.service=service; } const d=data[state.service]; return '<div class="stack service-workspace">'+(tab==='work'?d.work():tab==='review'?review(d):tab==='handover'?handover():overview(d))+(state.expanded?box(e(state.expanded.title),state.expanded.body):'')+'</div>'; }
  function open(title, body) { if(ui().open) ui().open(title, body); else state.expanded={title,body}; }
  function detailBody() {
    const content={
      social:'<div class="sample-art"><strong>Paper &amp; Pine</strong><p>Thoughtfully made, every day.</p><small>Fictional autumn collection carousel · 4 slides</small></div><p><strong>Caption:</strong> A closer look at the pieces made for everyday moments. Explore the autumn collection.</p>'+table(['Publication field','Sample value'],[['Platform','Instagram · feed carousel'],['Visuals','Cover, collection, product detail, closing slide'],['Planned time',e(state.schedule)+' · Africa/Lagos'],['Reviewer','Mira Cole'],['Publication','Not scheduled until the exact version is approved']]),
      branding:'<div class="sample-art"><strong>Paper &amp; Pine</strong><p>Identity direction B · calm and precise.</p><small>Fictional logo and identity presentation</small></div>'+table(['Identity item','Review point'],[['Logo family','Wordmark, symbol, horizontal and stacked lockups'],['Colour palette','Paper cream, forest green and dark ink; print and screen values included'],['Typography','Display serif with a clear body sans serif'],['Application examples','Packaging label, stationery and profile image'],['Feedback context','Identify the page and lockup; direction choice is separate from final sign-off']]),
      web:'<div class="sample-art"><strong>Paper &amp; Pine shop</strong><p>Homepage · product · basket · checkout</p><small>Fictional staging-page preview; no live destination</small></div>'+table(['Staging check','What the client reviews'],[['Homepage','Navigation, message, images and layout'],['Product page','Product information, image gallery and stock wording'],['Checkout','Delivery choice, total, payment outcome and receipt'],['Contact form','Submission acknowledgement and message receipt'],['Review context','Page, browser, steps, expected result and screenshot']])+'<p>Design approval does not record functional acceptance. The studio maintains test evidence; the client grants launch permission after reviewing results.</p>',
      apps:'<div class="sample-art"><strong>App build 0.9.2 (42)</strong><p>Sign-in · browse · basket · notifications</p><small>Fictional device-screen and test-build preview</small></div>'+table(['Build field','Sample detail'],[['Platforms','Android 15 and iOS 18 test devices'],['Install instructions','Studio-issued test invitation; accept it on the intended device and install build 42'],['Changed in this build','Basket total correction and clearer notification wording'],['Test checklist','Sign in, add/remove a product, restore basket and check notifications'],['Bug report','Device, operating system, build number, steps and evidence'],['Release state',state.release+'; store approval is separate from public release']]),
      software:'<div class="sample-art"><strong>Order assistant · milestone 2</strong><p>Customer lookup · permitted answers · human handoff</p><small>Fictional acceptance-review preview</small></div>'+table(['Acceptance criterion','Required result'],[['AC-01 · customer records','Existing record IDs survive import'],['AC-02 · permissions','Unauthorised staff cannot view private customer data'],['AC-03 · factual answers','Use approved product data; ask when information is missing'],['AC-04 · human escalation','Uncertain requests reach a responsible person'],['AC-05 · operations','Running-cost limit, monitoring and recovery owner recorded']])+'<p>A failed agreed check is a defect. An additional feature is a change request with price/date effects. Approval records the exact release candidate, not just that a demo was viewed.</p>',
      seo:'<div class="sample-art"><strong>How to care for everyday pieces</strong><p>Article outline · client review version '+state.version+'</p><small>Fictional editorial preview</small></div>'+table(['Article section','Review point'],[['Introduction','Answer the reader’s care question directly'],['Daily care','Confirm factual instructions against approved product guidance'],['Cleaning and storage','Avoid unsupported claims or guarantees'],['Frequently asked questions','Use real client questions and clear answers'],['Page plan','Care guide page; descriptive title, internal links and useful images'],['Checks before publishing','Client facts, editorial review and separate technical checks']])+'<p>This is a content decision. Period results retain their own source and date range; approving an article does not promise rankings or AI mentions.</p>',
      ads:'<div class="sample-art"><strong>Autumn collection</strong><p>Discover pieces for everyday moments.</p><small>Fictional campaign carousel and headline</small></div>'+table(['Campaign field','Sample detail'],[['Audience','People interested in home accessories; agreed region and exclusions recorded'],['Creative','Four-slide carousel, headline and primary text · exact version shown'],['Destination','Sample collection landing-page preview; no live URL'],['Platform checks','Creative policy review and conversion tracking'],['Spending decision','Separate maximum '+(state.budget?'approved':'awaiting approval')+' · ₦150,000 · 15–31 October']])+'<p>Approving this creative does not authorise spending, increase the limit or launch the campaign.</p><div class="actions">'+b('Review spending separately','budget')+'</div>'
    };
    return content[state.service]+'<p class="meta">Client reviewer: Mira Cole · studio reviewer: Ari. Feedback and decisions are attached to this exact version.</p><div class="actions">'+b('Approve this version','approve')+b('Request changes','notes')+'</div>';
  }
  const requests = {
    social: ['Campaign assets and account invitation','Supply the approved autumn campaign assets and invite the studio through the platform’s business-access tools.'],
    branding: ['Existing assets and naming confirmation','Supply any existing editable logo or guidance and confirm the exact approved business name and wording.'],
    web: ['Five product photographs','Supply five remaining product photographs by 14 October, with the matching product names and usage permission.'],
    apps: ['Test account and store information','Provide an authorised test-account invitation and the approved store description, support contact and screenshots.'],
    software: ['Integration access and permitted sample data','Invite the studio to the agreed integration workspace and supply a small authorised sample dataset with its permitted use.'],
    seo: ['Search Console invitation and factual guidance','Grant the agreed Search Console access by invitation and confirm product-care facts for the article review.'],
    ads: ['Advertising-platform invitation and destination','Invite the studio to the advertising account with agreed permissions and confirm the campaign landing-page destination.']
  };
  const changes = {
    social: 'Add a separate LinkedIn campaign with four new posts',
    branding: 'Add packaging-label designs to the identity package',
    web: 'Add a separate product collection and supporting pages',
    apps: 'Add saved wishlists to the mobile app',
    software: 'Add a supplier integration outside the agreed milestone',
    seo: 'Add three editorial guides to the agreed content plan',
    ads: 'Add a second audience campaign with a separate creative set'
  };
  function handle(action) {
    if(!action.startsWith('service-')) return null;
    const a=action.slice(8), d=data[state.service];
    if(!client() && clientDecisions.has(a)) { open('Decision belongs to the client','<p>Mira Cole records this decision. Switch to Client portal to try it. The studio can prepare the work and review evidence; it cannot approve as the client.</p>');return true; }
    if(client() && (studioActions.has(a)||a.startsWith('resolve-note-'))) { open('Managed by the studio','<p>The responsible studio team performs this action. You can review shared work, supply requested content, add feedback and grant launch permission.</p>');return true; }
    if(a==='detail'||a==='post') open(d.deliverable,'<p><strong>Version '+state.version+'</strong> · '+d.context+'</p>'+detailBody());
    else if(a==='approve'){state.decision='Approved';if(state.service==='social')state.post='Approved';open('Version '+state.version+' approved','<p>The sample decision records Mira Cole, this version and the time. The responsible team would be notified. A newer version needs a new decision.</p>');}
    else if(a==='notes'||a==='question') open('Add a review note','<label class="field">Your note<textarea id="service-note" rows="4" placeholder="Tell us what to change, and where."></textarea></label><p class="meta">Attached to version '+state.version+' · '+d.context+'</p>'+b('Save note in preview','save-note'));
    else if(a==='save-note'){const field=document.getElementById('service-note');if(!field||!field.value.trim()){if(field){field.setAttribute('aria-invalid','true');field.focus();}return true;}state.notes.push({text:field.value.trim(),done:false,author:client()?'Mira Cole ? client':'Ari ? studio'});state.decision='Changes requested';if(state.service==='social')state.post='Changes requested';if(ui().close)ui().close();}
    else if(a.startsWith('resolve-note-')){const n=state.notes[Number(a.slice(13))];if(n)n.done=true;}
    else if(a.startsWith('reopen-note-')){const n=state.notes[Number(a.slice(12))];if(n)n.done=false;}
    else if(a==='newversion'){state.history.push({version:state.version,decision:state.decision||'No decision'});state.version++;state.decision='';state.post='Awaiting approval';open('New version needs approval','<p>Your earlier decision is retained in history. Version '+state.version+' has a fresh review request; publishing stays paused.</p>');}
    else if(a==='request')open(requests[state.service][0],'<p>'+requests[state.service][1]+'</p><p>Mira Cole is responsible; Ari reviews the response. Access is granted by invitation through the provider, never by pasting a password or private key into a message.</p><label class="field">Response<textarea id="service-request" rows="3" placeholder="Describe what you have supplied or what you need help with."></textarea></label>'+b('Record supplied in preview','supply'));
    else if(a==='supply'){const f=document.getElementById('service-request');if(!f||!f.value.trim()){if(f){f.setAttribute('aria-invalid','true');f.focus();}return true;}state.requestDone=true;if(ui().close)ui().close();}
    else if(a==='change')open('Scope change · '+names[state.service],'<p><strong>Requested change:</strong> '+changes[state.service]+'.</p><p><strong>Fictional sample impact:</strong> ₦45,000 additional work; delivery moves from 23 to 27 October. Existing agreed work continues until a decision is recorded.</p><p>Client decision-maker: Mira Cole · studio lead: Ari · affected team and billing contact receive the outcome.</p>'+p(state.change||'Awaiting decision')+'<div class="actions">'+b('Accept change','accept-change')+b('Decline change','decline-change')+'</div>');
    else if(a==='accept-change'||a==='decline-change'){state.change=a==='accept-change'?'Accepted':'Declined';if(ui().close)ui().close();}
    else if(a==='direction-a'||a==='direction-b')state.selected=a==='direction-a'?'Direction A':'Direction B';
    else if(a==='budget')open('Approve a spending limit','<p>Sample campaign limit: <strong>₦150,000</strong>, 15–31 October. Creative approval is recorded separately. A higher limit needs a fresh decision.</p>'+b('Approve this limit','approve-budget'));
    else if(a==='approve-budget'){state.budget=true;if(ui().close)ui().close();}
    else if(a==='launch'){const ready=state.service==='ads'?state.budget&&state.decision==='Approved':state.test;open('Launch permission',ready?'<p>The sample prerequisites are met. Give explicit permission to proceed; this demo cannot publish anything.</p>'+b('Grant sample permission','grant-launch'):'<p>Permission is blocked until '+(state.service==='ads'?'creative and spending approvals are both recorded.':'functional testing is recorded.')+'</p>');}
    else if(a==='grant-launch'){state.launch=true;if(ui().close)ui().close();}
    else if(a==='test')open('Acceptance checklist','<p>Sample test: follow the agreed steps, record the actual result and attach evidence. Failed checks stay open; new requirements are handled as scope changes.</p><div class="item">Sign-in and permissions · passed</div><div class="item">Core user journey · ready to test</div>'+b('Record sample checks passed','pass-test'));
    else if(a==='pass-test'){state.test=true;if(ui().close)ui().close();}
    else if(a==='release')state.release=state.release==='Submitted'?'Store approved':state.release==='Store approved'?'Released':'Submitted';
    else if(a==='schedule')open('Move the planned post','<p>Current: '+e(state.schedule)+' · Africa/Lagos. Changing the time does not approve the creative.</p><div class="actions">'+b('15 October · 10:00','move-post')+'</div>');
    else if(a==='move-post'){state.schedule='15 October · 10:00';if(ui().close)ui().close();}
    else if(a==='failure')open('Publishing failed','<p>The sample account connection expired. The post is not published. The responsible social lead would receive the exception.</p><p>Reconnect through the approved account-access flow, then retry only the failed publication. Keep the original attempt in history.</p>'+b('Simulate connection repaired','repair-post'));
    else if(a==='repair-post')open('Retry ready','<p>Connection repaired in this demo. The failed post remains separate from approved and published posts.</p>'+b('Simulate successful retry','retry-post'));
    else if(a==='retry-post'){state.failedPost='Published';open('Publication recorded','<p>Sample retry completed. A real record needs provider confirmation, publication time and a live-post link.</p>');}
    else if(a==='published-care'||a==='published-weekend')open('Publication evidence','<p>'+(a==='published-weekend'?'Weekend story · fictional Instagram post · published after the sample retry on 20 October at 10:05.':'Care guide · fictional Instagram post · published 18 October at 12:02.')+' Creative v1 and provider confirmation belong to this record.</p>');
    else if(a==='ai')open('AI evaluation v2','<p>Sample checks cover authorised data, correct answers, uncertain answers, refusal, human escalation and cost limits.</p>'+table(['Example','Expected result','Sample outcome'],[['Unknown product claim','Ask a person; do not invent','Passed'],['Private customer data','Refuse unauthorised disclosure','Passed'],['Unclear order request','Clarify before changing an order','Needs review']])+notice('Known limitation: the assistant cannot authorise refunds. A responsible person owns escalation.'));
    else if(a==='package')open('Final package','<p>Organised folders: final exports; editable source where agreed; guides; training; account ownership; open items; support contacts. Sample filenames and checksums would be shown beside each version.</p>');
    else if(a==='handover')state.handover=true;
    else if(a==='renewal'){state.renewal=true;open('Continuation requested','<p>Your sample request is recorded. The studio would prepare the term, scope and price for acceptance. No charge or renewal has occurred.</p>');}
    else return null;
    return true;
  }
  window.WDC_SERVICES={render,handle,summary(){return {reviews:records.social.post==='Awaiting approval'?1:0,requests:records.web && records.web.requestDone?0:1};}};
})();
