/* eslint-disable @typescript-eslint/no-require-imports -- Native CommonJS loader tests real TypeScript without framework or provider dependencies. */
// Database/provider-free boundary check: node tests/currency.check.cjs
const fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),assert=require('node:assert/strict'),ts=require('typescript');
const cache=new Map();function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file).exports;const m=new Module(file);cache.set(file,m);m.paths=Module._nodeModulePaths(path.dirname(file));const native=m.require.bind(m);m.require=name=>name.startsWith('@/')?load(path.resolve(name.slice(2)+'.ts')):name.startsWith('.')?load(path.resolve(path.dirname(file),name+'.ts')):native(name);m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);return m.exports;}
const currency=load('lib/money/currency.ts'),store=load('lib/admin/store.ts');
assert.equal(currency.currencyOf({}),'NGN');assert.match(currency.money(12500,'USD'),/125\.00/);assert.deepEqual(currency.parseCurrencies('["USD"]'),['NGN','USD']);assert.throws(()=>currency.parseCurrencies('["BTC"]'));
const account={id:'usd',label:'USD account',currency:'USD',bankName:'Bank',accountName:'Studio',accountNumber:'123'};assert.throws(()=>currency.parsePaymentAccounts(JSON.stringify([account,account])));
const base={clientId:'c',projectId:null,issued:'2026-10-10',due:'2026-11-10',vatRate:0,lines:[{description:'Service',qty:1,unit:10000}],status:'Draft'};
const draft=store.addInvoice(base);assert.equal(store.patchInvoice(draft.id,{currency:'USD',paymentAccount:account}).ok,true);store.sendInvoice(draft.id);assert.equal(store.patchInvoice(draft.id,{currency:'NGN'}).ok,false);
assert.equal(store.applyPayment({invoiceId:draft.id,amount:10000,method:'Paystack',mode:'live',reference:'wrong-provider'}).ok,false);
const payment=store.applyPayment({invoiceId:draft.id,amount:12000,method:'Bank transfer',reference:'usd-payment'});assert.equal(payment.ok,true);assert.equal(payment.payment.currency,'USD');
const refund=store.refundPayment({paymentId:payment.payment.id,amount:2000,reason:'Overpayment held',toCredit:true,actor:'Owner'});assert.equal(refund.ok,true);assert.equal(refund.credit.currency,'USD');assert.equal(store.creditBalance('c'),0);assert.equal(store.creditBalance('c','USD'),2000);
const ngn=store.addInvoice({...base,status:'Sent',lines:[{description:'Service',qty:1,unit:30000}]});assert.equal(store.applyCredit(refund.credit.id,ngn.id).ok,false);assert.equal(store.applyCreditsTo(ngn.id).applied,0);
const usd=store.addInvoice({...base,currency:'USD',status:'Sent'});assert.equal(store.applyCreditsTo(usd.id).applied,2000);
const estimate=store.addEstimate({clientId:'c',projectId:null,issued:'2026-10-10',expires:'2026-11-10',vatRate:0,lines:base.lines,state:'Sent',currency:'USD',paymentAccount:account});const accepted=store.answerEstimate({id:estimate.id,accepted:true,by:'Client'});assert.equal(accepted.invoice.currency,'USD');assert.deepEqual(accepted.invoice.paymentAccount,account);
const totals=store.currencyTotals(store.getInvoices());assert.equal(totals.find(row=>row.currency==='NGN').invoiced,30000);assert.equal(totals.find(row=>row.currency==='USD').invoiced,30000);assert.equal(store.getSummary().invoiced,30000);assert.equal(store.duplicateInvoice(draft.id).currency,'USD');assert.equal(store.duplicateEstimate(estimate.id).currency,'USD');
console.log('Currency, payment, credit, issued-copy and quote inheritance checks passed; no database or provider writes.');
