"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, CalendarDays, RefreshCw } from "lucide-react";
import { Panel } from "@/components/admin/bits";
import { Dialog } from "@/components/admin/dialog";
import { DateTimeInput } from "@/components/admin/pick";
import { ask } from "@/components/admin/confirm";
import { toast } from "@/components/admin/toast";
import { RowMenu } from "@/components/admin/row-menu";
import { RowPick, PickAll, BulkBar } from "@/components/admin/bulk";
import { Pager, readPer } from "@/components/admin/pager";
import { CalendarPeriod, MonthCalendar } from "./calendar";
import { meetingCommand, meetingRequest } from "./client";
import { safeJoinUrl } from "./links";
import type { Booking } from "@/lib/meetings/cal";
import "./meetings.css";

const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const localInput=(value:string)=>{const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const status=(booking:Booking)=>booking.status.toLowerCase();
const time=(start:string)=>new Intl.DateTimeFormat("en",{hour:"2-digit",minute:"2-digit"}).format(new Date(start));
export function MeetingsAdmin({owner,query={}}:{owner:boolean;query?:Record<string,string|undefined>}){
  const [date,setDate]=useState(()=>/^\d{4}-\d{2}-\d{2}$/.test(query.date||"")?query.date!:today()),[view,setView]=useState(query.mode||"Agenda"),[tab,setTab]=useState(query.tab||"Calendar"),[meetings,setMeetings]=useState<Booking[]>([]),[selected,setSelected]=useState<Booking|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[rescheduling,setRescheduling]=useState(false);
  const month=date.slice(0,7);
  const load=useCallback(async()=>{
    setLoading(true);setError("");
    const [y,m]=month.split("-").map(Number);const start=new Date(y,m-1,1).toISOString(),end=new Date(y,m,1).toISOString();
    try{const response=await fetch(`/api/meetings?${new URLSearchParams({view:"admin",start,end})}`);const body=await response.json();if(!response.ok)throw new Error(body.error);setMeetings(body.meetings)}catch(e){setError(e instanceof Error?e.message:"Meetings could not be loaded.")}finally{setLoading(false)}
  },[month]);
  useEffect(()=>{void load()},[load]);
  const next=meetings.find(b=>Date.parse(b.start)>Date.now()&&["accepted","confirmed"].includes(status(b)));
  const dateKey=(start:string)=>{const d=new Date(start);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
  const shown=meetings.filter(b=>tab==="Requests"?status(b)==="pending":tab==="History"?["cancelled","rejected"].includes(status(b))||Date.parse(b.end)<Date.now():view==="Day"?dateKey(b.start)===date:view==="Week"?Math.abs(Date.parse(dateKey(b.start))-Date.parse(date))<7*86400000:!['cancelled','rejected'].includes(status(b)));
  const per=readPer(query.per),page=Math.max(1,Math.min(Number(query.page)||1,Math.ceil(shown.length/per)||1));
  const paged=shown.slice((page-1)*per,page*per);
  async function bulk(kind:string,ids:string[]){
    const outcomes=[];
    for(const uid of ids){try{await meetingCommand({action:kind,uid,reason:"Updated by the studio in bulk"},setNotice);outcomes.push({id:uid,label:meetings.find(b=>b.uid===uid)?.title||uid,ok:true,message:"Updated"})}catch(e){outcomes.push({id:uid,label:meetings.find(b=>b.uid===uid)?.title||uid,ok:false,message:e instanceof Error?e.message:"Check Cal.com before continuing."})}}
    await load();const done=outcomes.filter(row=>row.ok).length;
    return{ok:done===ids.length,message:`${done} of ${ids.length} meetings updated.`,outcomes};
  }
  function table(){return <div id="meetings-list"><BulkBar target="meetings-list" noun="meetings" onRun={bulk} actions={[{kind:"confirm",label:"Approve",icon:"check",confirm:"Approve the selected meeting requests?"}]} more={[{kind:"cancel",label:"Cancel meetings",danger:true,confirm:"Cancel the selected meetings? Cal.com manages the calendar change notices."}]}/><div className="ad__scroll" data-lenis-prevent><table className="ad__table meetTable"><thead><tr><th><PickAll/> Meeting</th><th>Date and time</th><th>Attendee</th><th>Status</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{paged.map(b=><tr key={b.uid}><td><RowPick id={b.uid} label={b.title}/><button className="meetTableTitle" onClick={()=>setSelected(b)}>{b.title}</button></td><td>{new Intl.DateTimeFormat("en",{dateStyle:"medium",timeStyle:"short"}).format(new Date(b.start))}</td><td>{b.attendees?.[0]?.name||"Meeting attendee"}</td><td><span className={`ad__pill ad__pill--${status(b)==="pending"?"warn":['cancelled','rejected'].includes(status(b))?"flat":"good"}`}>{b.status}</span></td><td><RowMenu label={b.title} items={[{kind:"dialog",label:"View meeting",title:b.title,render:close=><><p>View the details and available actions for this meeting.</p><button className="ad__btn" onClick={()=>{close();setSelected(b)}}>Open meeting details</button></>}]}/></td></tr>)}</tbody></table></div><Pager label="Meeting pages" noun="meetings" total={shown.length} page={page} per={per} href={patch=>`/admin/meetings?${new URLSearchParams({date,mode:view,tab,page:String(patch.page||1),per:String(patch.per||per)})}`}/></div>}
  async function change(action:string,start?:string){if(!selected)return;if(!await ask(`${action[0].toUpperCase()+action.slice(1)} this meeting? Cal.com manages the calendar change notice. Delivery is shown only when evidence exists.`,{verb:action==="confirm"?"Approve":action[0].toUpperCase()+action.slice(1)}))return;setBusy(true);setError("");try{const result=await meetingCommand({action,uid:selected.uid,start,reason:"Updated by the studio"},setNotice);setSelected(result.booking);setNotice(result.notices);toast("Meeting updated");setRescheduling(false);await load()}catch(e){const message=e instanceof Error?e.message:"The meeting could not be updated.";setError(message);toast(message,"bad")}finally{setBusy(false)}}
  async function sync(){setBusy(true);try{const result=await meetingRequest({action:"sync"});setNotice(result.message);toast(result.message)}catch(e){toast(e instanceof Error?e.message:"Refresh failed.","bad")}finally{setBusy(false)}}
  function row(booking:Booking){return <button className="meetRow" key={booking.uid} onClick={()=>{setSelected(booking);setRescheduling(false)}}><span><strong>{time(booking.start)}</strong><small>{new Intl.DateTimeFormat("en",{month:"short",day:"numeric"}).format(new Date(booking.start))}</small></span><span><strong>{booking.title}</strong><small>{booking.attendees?.[0]?.name||"Meeting attendee"}</small><span className={`ad__pill ad__pill--${status(booking)==="pending"?"warn":['cancelled','rejected'].includes(status(booking))?"flat":"good"}`}>{booking.status}</span></span><ArrowRight aria-hidden="true"/></button>}
  return <div className="meetWrap"><div className="ad__head"><div><h1>Meetings</h1><p>Your calendar, requests and next conversation.</p></div><div className="meetActions"><button className="ad__btn ad__btn--plain" disabled={busy} onClick={()=>void sync()}><RefreshCw aria-hidden="true"/> Refresh from Cal.com</button>{owner?<Link className="ad__btn" href="/admin/settings/meetings">Scheduling settings</Link>:null}</div></div>
    {notice?<p className="meetHint" role="status">{notice} <button className="ad__btn ad__btn--plain" onClick={()=>void load()}>Reload calendar</button></p>:null}
    {error?<div className="meetEmpty" role="alert"><p>{error}</p><button className="ad__btn" onClick={()=>void load()}>Try again</button>{owner?<Link href="/admin/settings/system">Check migrations and system health</Link>:null}</div>:null}
    {next?<section className="ad__panel meetNext"><div><small>NEXT CONVERSATION</small><h2>{next.title}</h2><p>{new Intl.DateTimeFormat("en",{dateStyle:"medium"}).format(new Date(next.start))} · {next.attendees?.[0]?.name}</p></div><strong className="meetNextTime">{time(next.start)}</strong><div className="meetActions"><button className="ad__btn" onClick={()=>setSelected(next)}><CalendarDays aria-hidden="true"/> View meeting</button><button className="ad__btn ad__btn--plain" onClick={()=>{void navigator.clipboard.writeText(`${location.origin}/meet`).then(()=>toast("Booking link copied")).catch(()=>toast("Copy could not be completed. Use the booking page link.","bad"))}}>Copy booking link</button></div></section>:null}
    <Panel title="Calendar" action={<div className="meetActions">{["Calendar","Requests","History"].map(value=><button key={value} className={`ad__btn${tab===value?"":" ad__btn--plain"}`} aria-pressed={tab===value} onClick={()=>setTab(value)}>{value}</button>)}</div>}><div className="meetBody"><div className="meetToolbar"><CalendarPeriod value={date} onChange={setDate}/><div className="meetActions">{["Agenda","Day","Week","Month"].map(value=><button key={value} className={`ad__btn${view===value?"":" ad__btn--plain"}`} aria-pressed={view===value} onClick={()=>setView(value)}>{value}</button>)}</div></div><p className="meetHint">Times shown in {Intl.DateTimeFormat().resolvedOptions().timeZone}. Calendar notices are managed by Cal.com.</p>
      {loading?<p className="meetBusy" role="status">Loading meetings…</p>:!error?<>{view==="Month"&&tab==="Calendar"?<><div className="meetCalendar--desktop"><MonthCalendar value={date} onChange={setDate}>{day=>meetings.filter(b=>dateKey(b.start)===day&&!['cancelled','rejected'].includes(status(b))).map(b=><button className={`meetEvent meetStatus${status(b)==="pending"?" meetStatus--pending":""}`} key={b.uid} onClick={()=>setSelected(b)} title={`${time(b.start)} ${b.title}`}><time>{time(b.start)}</time><span>{b.title}</span></button>)}</MonthCalendar></div><div className="meetMobileAgenda"><MonthCalendar value={date} onChange={setDate}/><div className="meetAgenda"><h3>Meetings on this day</h3>{meetings.filter(b=>dateKey(b.start)===date).map(row)}</div></div></>:shown.length?table():<div className="meetEmpty"><CalendarDays aria-hidden="true"/><strong>{tab==="Requests"?"No requests awaiting approval":tab==="History"?"Nothing here yet":"No meetings in this period"}</strong><p>{tab==="History"?"Past and cancelled meetings appear here.":"Choose a different period or share your booking page."}</p><div className="meetActions"><button className="ad__btn ad__btn--plain" onClick={()=>{setTab("Calendar");setView("Agenda")}}>View calendar</button><Link className="ad__btn" href="/meet">Open booking page</Link></div></div>}</>:null}
    </div></Panel>
    <Dialog open={!!selected} onClose={()=>{if(!busy)setSelected(null)}} title="Meeting details">{selected?<><h3>{selected.title}</h3><p>{new Intl.DateTimeFormat("en",{dateStyle:"full",timeStyle:"short"}).format(new Date(selected.start))}</p><p>Status: <strong>{selected.status}</strong></p><p>{selected.attendees?.map(a=>`${a.name} · ${a.email}`).join(", ")}</p>{safeJoinUrl(selected.meetingUrl)?<p><a className="ad__btn" target="_blank" rel="noopener noreferrer" href={safeJoinUrl(selected.meetingUrl)!}>Join meeting</a></p>:<p className="meetHint">The meeting link has not been supplied by the provider yet.</p>}{notice?<p role="status" className="meetHint">{notice}</p>:null}{error?<p role="alert" className="meetError">{error}</p>:null}{rescheduling?<form onSubmit={e=>{e.preventDefault();const start=new FormData(e.currentTarget).get("start");if(typeof start==="string")void change("reschedule",new Date(start).toISOString())}}><label className="meetField">New date and time<DateTimeInput name="start" defaultValue={localInput(selected.start)} min={localInput(new Date().toISOString())}/></label><p className="meetHint">Cal.com checks availability before changing the meeting. Times here use your browser’s time zone.</p><button className="ad__btn" disabled={busy}>Confirm new time</button></form>:<div className="meetActions">{status(selected)==="pending"?<><button className="ad__btn" disabled={busy} onClick={()=>void change("confirm")}>Approve request</button><button className="ad__btn ad__btn--plain" disabled={busy} onClick={()=>void change("decline")}>Decline request</button></>:null}{!['cancelled','rejected'].includes(status(selected))?<><button className="ad__btn ad__btn--plain" disabled={busy} onClick={()=>setRescheduling(true)}>Reschedule</button><button className="ad__btn ad__btn--plain" disabled={busy} onClick={()=>void change("cancel")}>Cancel meeting</button></>:null}</div>}<p className="meetHint">Optional reminders are off. Calendar confirmations and changes are managed by Cal.com; enabled does not mean delivered.</p></>:null}</Dialog>
  </div>
}
