"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { CalendarDays, Plus, Trash2 } from "lucide-react";
import { Panel } from "@/components/admin/bits";
import { SettingsForm, Switch, Text, Row, useDirtyPing } from "@/components/admin/settings/kit";
import { Pick, DateInput } from "@/components/admin/pick";
import { toast } from "@/components/admin/toast";
import { meetingCommand } from "./client";
import type { ActionState } from "@/lib/admin/validate";
import type { Schedule, MeetingType } from "@/lib/meetings/cal";
import "./meetings.css";

type Setup={config:{enabled:boolean;event_type_id:number|null;schedule_id:number|null;settings:Record<string,unknown>};types:MeetingType[];schedules:Schedule[];calendarConnected:boolean;googleMeetConnected:boolean;webhookConfigured:boolean;reminders:{available:boolean;reason:string}};
const DAYS=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
const TIMES=Array.from({length:96},(_,i)=>{const value=`${String(Math.floor(i/4)).padStart(2,"0")}:${String(i%4*15).padStart(2,"0")}`;return {value,label:value}});
export function MeetingSettings(){
  const [data,setData]=useState<Setup|null>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[tab,setTab]=useState("Availability"),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{const response=await fetch("/api/meetings?view=setup");const value=await response.json();if(!response.ok)throw new Error(value.error);setData(value);setError("")}catch(e){setError(e instanceof Error?e.message:"Meeting settings could not be loaded.")}},[]);
  useEffect(()=>{void Promise.resolve().then(load)},[load]);
  async function setup(){setBusy(true);try{const value=await meetingCommand({action:"setup"},setMessage);setMessage(value.message);toast(value.message);await load()}catch(e){setError(e instanceof Error?e.message:"Setup could not be completed.");toast("Setup needs attention","bad")}finally{setBusy(false)}}
  async function saveSettings(_previous:ActionState,fd:FormData):Promise<ActionState>{try{const result=await meetingCommand({action:"settings",enabled:fd.get("enabled")==="1",duration:Number(fd.get("duration")),notice:Number(fd.get("notice")),buffer:Number(fd.get("buffer"))},setMessage);await load();return {ok:true,message:result.message}}catch(e){return{ok:false,message:e instanceof Error?e.message:"Settings could not be saved."}}}
  async function saveAvailability(_previous:ActionState,fd:FormData):Promise<ActionState>{try{const schedule=JSON.parse(String(fd.get("schedule")));const result=await meetingCommand({action:"availability",schedule},setMessage);await load();return{ok:true,message:result.message}}catch(e){return{ok:false,message:e instanceof Error?e.message:"Availability could not be saved."}}}
  const schedule=data?.schedules.find(s=>String(s.id)===String(data.config.schedule_id));
  return <div className="meetWrap meetSettings"><div className="ad__head"><div><h1>Scheduling settings</h1><p>Your availability and how people book a conversation.</p></div><Link className="ad__btn ad__btn--plain" href="/admin/meetings">View meetings</Link></div>{error?<div className="meetEmpty" role="alert"><p>{error}</p><button className="ad__btn" onClick={()=>void load()}>Check again</button><Link href="/admin/settings/system">Check the Meetings migration in System</Link></div>:null}{message?<p role="status" className="meetHint">{message}</p>:null}{!data&&!error?<p className="meetBusy" role="status">Checking scheduling configuration…</p>:null}{data?<>
    {!data.config.event_type_id?<Panel title="Connect your booking flow"><div className="meetBody"><CalendarDays aria-hidden="true"/><p>Your Cal.com key is connected. Create a private WDC meeting type, then review its calendar and availability before publishing.</p><div className="meetActions"><button className="ad__btn" disabled={busy} onClick={()=>void setup()}>{busy?"Checking setup…":"Create meeting type"}</button><a className="ad__btn ad__btn--plain" href="https://app.cal.com/event-types" target="_blank" rel="noopener noreferrer">Open Cal.com</a></div></div></Panel>:null}
    <div className="meetActions" aria-label="Scheduling sections">{["Availability","Booking rules","Reminders","Connections"].map(value=><button key={value} className={`ad__btn${tab===value?"":" ad__btn--plain"}`} aria-pressed={tab===value} onClick={()=>setTab(value)}>{value}</button>)}</div>
    {tab==="Availability"?<Panel title="Your working hours"><div className="meetBody">{schedule?<SettingsForm action={saveAvailability}><ScheduleEditor key={`${schedule.id}-${JSON.stringify(schedule.availability)}-${JSON.stringify(schedule.overrides)}`} schedule={schedule}/></SettingsForm>:<div className="meetEmpty"><p>Create the meeting type first to use your existing Cal.com working-hours schedule.</p><button className="ad__btn" disabled={busy} onClick={()=>void setup()}>Set up scheduling</button></div>}</div></Panel>:null}
    {tab==="Booking rules"?<Panel title="How meetings are booked"><div className="meetBody"><SettingsForm action={saveSettings}><Switch name="enabled" label="Accept new meeting bookings" note="Publish only after you have reviewed the schedule, calendar connections and webhook setup." defaultChecked={data.config.enabled} disabled={!data.config.event_type_id||!data.calendarConnected||!data.googleMeetConnected||!data.webhookConfigured}/>{!data.calendarConnected||!data.googleMeetConnected||!data.webhookConfigured?<p className="meetHint">Finish the required connections below before enabling booking. <button type="button" className="ad__btn ad__btn--plain" onClick={()=>setTab("Connections")}>View setup steps</button></p>:null}<Row label="Meeting duration"><Pick name="duration" label="Meeting duration" defaultValue={String(data.config.settings.lengthInMinutes||30)} options={[15,30,45,60].map(n=>({value:String(n),label:`${n} minutes`}))}/></Row><Text name="notice" label="Minimum notice, in minutes" type="number" min={60} max={43200} defaultValue={Number(data.config.settings.minimumBookingNotice||1440)} hint="1440 minutes is one day. Times inside this window are not offered."/><Text name="buffer" label="Buffer before and after, in minutes" type="number" min={0} max={120} defaultValue={Number(data.config.settings.beforeEventBuffer??15)} hint="Time kept free around each conversation."/></SettingsForm></div></Panel>:null}
    {tab==="Reminders"?<Panel title="Meeting notices and reminders"><div className="meetBody"><strong>One notification owner: Cal.com</strong><p className="meetHint">Calendar confirmations, rescheduling and cancellation notices are managed by Cal.com. WDC does not send duplicates.</p><Row label="Optional attendee reminders" note={data.reminders.reason}><button className="ad__btn ad__btn--plain" disabled>Off · setup required</button></Row><p className="meetHint">24-hour and 1-hour reminders will only be enabled after their workflow, individual opt-out and suppression on changes are verified. We do not claim an email was delivered without delivery evidence.</p><Row label="SMS and WhatsApp" note="Keep off until provider support, charges and explicit recipient consent are verified."><button className="ad__btn ad__btn--plain" disabled>Off</button></Row><div className="meetActions"><a className="ad__btn" href="https://app.cal.com/workflows" target="_blank" rel="noopener noreferrer">Review Cal.com workflows</a><button className="ad__btn ad__btn--plain" onClick={()=>setTab("Connections")}>Check setup</button></div></div></Panel>:null}
    {tab==="Connections"?<Panel title="Connections and recovery"><div className="meetBody"><p>Calendar: <strong>{data.calendarConnected?"Connected with a destination calendar":"Connection required"}</strong></p><p>Google Meet: <strong>{data.googleMeetConnected?"Connected":"Connection required"}</strong></p><p>Signed production webhook: <strong>{data.webhookConfigured?"Registered and checked":"Required before publishing"}</strong></p><p className="meetHint">Calendar access is separate from signing in to WDC with Google. Google and Apple calendars are configured in your Cal.com account; WDC never stores their passwords.</p><div className="meetActions"><a className="ad__btn" href="https://app.cal.com/settings/my-account/calendars" target="_blank" rel="noopener noreferrer">Manage calendars</a><a className="ad__btn ad__btn--plain" href="https://app.cal.com/apps" target="_blank" rel="noopener noreferrer">Manage video apps</a></div><p className="meetHint">Register the signed endpoint <code>/api/meetings/webhook</code> in Cal.com using the environment’s CAL_WEBHOOK_SECRET. Recovery retains received changes and pending commands if a worker stops; uncertain provider changes need checking before retry.</p><Link href="/admin/meetings">Refresh and check meetings</Link></div></Panel>:null}
  </>:null}</div>;
}
function ScheduleEditor({schedule}:{schedule:Schedule}){
  const ping=useDirtyPing(),root=useRef<HTMLDivElement>(null);
  const independent=useCallback(()=>({...schedule,availability:schedule.availability.flatMap(row=>row.days.map(day=>({...row,days:[day]})))}),[schedule]);
  const [value,setValue]=useState(independent);
  useEffect(()=>{const form=root.current?.closest("form");const reset=()=>setValue(independent());form?.addEventListener("reset",reset);return()=>form?.removeEventListener("reset",reset)},[schedule,independent]);
  function update(next:Schedule){setValue(next);ping()}
  function range(index:number,key:"startTime"|"endTime",time:string){update({...value,availability:value.availability.map((r,i)=>i===index?{...r,[key]:time}:r)})}
  const timePick=(current:string,label:string,onChange:(value:string)=>void)=><Pick value={current} label={label} search options={TIMES.some(t=>t.value===current)?TIMES:[{value:current,label:current},...TIMES]} onChange={onChange}/>;
  return <div ref={root}><input type="hidden" name="schedule" value={JSON.stringify({timeZone:value.timeZone,availability:value.availability,overrides:value.overrides})}/><Row label="Schedule time zone"><Pick value={value.timeZone} label="Schedule time zone" options={Array.from(new Set([value.timeZone,...Intl.supportedValuesOf("timeZone"),"UTC"])).map(z=>({value:z,label:z}))} search onChange={timeZone=>update({...value,timeZone})}/></Row><p className="meetHint">Multiple ranges per day are supported. Set your weekly hours here; date exceptions replace that day’s regular hours.</p>{DAYS.map(day=><div className="meetHours" key={day}><strong>{day}</strong><div className="meetHoursRanges">{value.availability.map((r,i)=>r.days.includes(day)?<div className="meetHoursRange" key={i}>{timePick(r.startTime,`${day} start`,time=>range(i,"startTime",time))}<span>to</span>{timePick(r.endTime,`${day} end`,time=>range(i,"endTime",time))}<button type="button" className="ad__iconButton" aria-label={`Remove ${day} time range`} onClick={()=>update({...value,availability:value.availability.flatMap((row,n)=>n!==i?[row]:row.days.length>1?[{...row,days:row.days.filter(d=>d!==day)}]:[])})}><Trash2 aria-hidden="true"/></button></div>:null)}{!value.availability.some(r=>r.days.includes(day))?<span>Unavailable</span>:null}</div><button type="button" className="ad__iconButton" aria-label={`Add ${day} time range`} onClick={()=>update({...value,availability:[...value.availability,{days:[day],startTime:"09:00",endTime:"17:00"}]})}><Plus aria-hidden="true"/></button></div>)}<h3>Date exceptions</h3>{value.overrides.map((row,i)=><div key={i} className="meetOverride"><DateInput value={row.date} onChange={date=>update({...value,overrides:value.overrides.map((r,n)=>n===i?{...r,date}:r)})}/>{timePick(row.startTime,"Exception start",startTime=>update({...value,overrides:value.overrides.map((r,n)=>n===i?{...r,startTime}:r)}))}<span>to</span>{timePick(row.endTime,"Exception end",endTime=>update({...value,overrides:value.overrides.map((r,n)=>n===i?{...r,endTime}:r)}))}<button type="button" className="ad__iconButton" aria-label={`Remove exception ${row.date}`} onClick={()=>update({...value,overrides:value.overrides.filter((_,n)=>n!==i)})}><Trash2 aria-hidden="true"/></button></div>)}<button type="button" className="ad__btn ad__btn--plain" onClick={()=>update({...value,overrides:[...value.overrides,{date:new Date().toISOString().slice(0,10),startTime:"09:00",endTime:"17:00"}]})}><Plus aria-hidden="true"/> Add a date exception</button><p className="meetHint">To block a longer time away, use Cal.com’s Out of Office controls. Existing calendar conflicts are also excluded automatically.</p><a href="https://app.cal.com/settings/my-account/out-of-office" target="_blank" rel="noopener noreferrer">Manage time away</a></div>;
}
