/**
 * The database, as Drizzle declares it for CockroachDB over the Postgres wire.
 *
 * THIS FILE IS THE TARGET, AND NOTHING IMPORTS IT YET. The admin screens read
 * through lib/admin/store.ts, whose in-memory implementation satisfies the
 * same types in lib/admin/types.ts. That is deliberate: the whole admin can be
 * built, reviewed and corrected without a database existing, and the swap is
 * one module rewriting its four functions against these tables. The compiler
 * checks that the replacement still returns the shapes every screen reads.
 *
 * CONVENTIONS, and why each one:
 *
 *   UUID primary keys, generated by the database. Sequential integers leak
 *   how many clients we have to anyone who can see a URL, and they collide
 *   the moment anything is imported or merged.
 *
 *   MONEY AS `bigint` OF KOBO, never `numeric` and never a float. An invoice
 *   total that is out by a thousandth of a naira is an invoice that does not
 *   reconcile, and floating point makes that inevitable rather than unlikely.
 *   Totals are NOT stored at all: they are a function of the lines, so storing
 *   them invites the two to disagree.
 *
 *   `deleted_at` rather than DELETE. A removed client still owns invoices that
 *   have to keep balancing, and the most common reason a row disappears is
 *   somebody pressing the wrong button.
 *
 *   SOFT REFERENCES, not hard foreign keys, on everything that crosses an
 *   aggregate. CockroachDB enforces FK checks across ranges, which is a
 *   distributed transaction on every insert; the integrity that matters here
 *   is enforced in one place in the application instead.
 */
import {
  bigint, boolean, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uuid, varchar,
} from "drizzle-orm/pg-core";

export const serviceEnum = pgEnum("service", [
  "branding", "seo", "web", "apps", "software", "social",
]);

export const stageEnum = pgEnum("stage", [
  "Onboarding", "Discovery", "In progress", "Review", "Revisions", "Delivered",
]);

export const invoiceStatusEnum = pgEnum("invoice_status", [
  "Draft", "Sent", "Part paid", "Paid", "Overdue",
]);

/* A description, not the enforcement: the live column is a STRING held to these
   three by `user_role_check` (migration 0019), not a Postgres enum. */
export const roleEnum = pgEnum("role", ["owner", "staff", "client"]);

/* -------------------------------------------------------------------- auth */

export const users = pgTable("users", {
  id: uuid("id").defaultRandom().primaryKey(),
  email: varchar("email", { length: 320 }).notNull().unique(),
  name: text("name").notNull(),
  role: roleEnum("role").notNull().default("client"),
  /* Set when a client user is bound to a client record. Null for staff. */
  clientId: uuid("client_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
});

/* ----------------------------------------------------------------- clients */

export const clients = pgTable("clients", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: text("name").notNull(),
  company: text("company").notNull(),
  email: varchar("email", { length: 320 }).notNull(),
  phone: varchar("phone", { length: 32 }).notNull(),
  /* An array rather than a join table: a client's services are read on every
     screen that shows a client and are never queried independently. */
  services: serviceEnum("services").array().notNull().default([]),
  sector: text("sector").notNull().default(""),
  since: timestamp("since", { withTimezone: true }).defaultNow().notNull(),
  notes: text("notes"),
  archived: boolean("archived").notNull().default(false),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
}, (t) => [index("clients_company_idx").on(t.company)]);

/* ---------------------------------------------------------------- projects */

export const projects = pgTable("projects", {
  id: uuid("id").defaultRandom().primaryKey(),
  clientId: uuid("client_id").notNull(),
  title: text("title").notNull(),
  service: serviceEnum("service").notNull(),
  stage: stageEnum("stage").notNull().default("Onboarding"),
  due: timestamp("due", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
}, (t) => [index("projects_client_idx").on(t.clientId)]);

/* Append-only. A project's history is evidence, so nothing here is updated. */
export const projectEvents = pgTable("project_events", {
  id: uuid("id").defaultRandom().primaryKey(),
  projectId: uuid("project_id").notNull(),
  at: timestamp("at", { withTimezone: true }).defaultNow().notNull(),
  text: text("text").notNull(),
  /* Who caused it. Null for anything the system did on its own. */
  actorId: uuid("actor_id"),
}, (t) => [index("project_events_project_idx").on(t.projectId)]);

/* ------------------------------------------------------------------- money */

export const invoices = pgTable("invoices", {
  id: uuid("id").defaultRandom().primaryKey(),
  /* INV-YYYY-NNN. Unique because an accountant needs it to be, and because a
     reused number is a reconciliation nobody can finish. */
  number: varchar("number", { length: 16 }).notNull().unique(),
  clientId: uuid("client_id").notNull(),
  projectId: uuid("project_id"),
  status: invoiceStatusEnum("status").notNull().default("Draft"),
  issued: timestamp("issued", { withTimezone: true }).defaultNow().notNull(),
  due: timestamp("due", { withTimezone: true }).notNull(),
  /* The lines as JSONB. They are read and written whole, never queried
     individually, and keeping them together means an invoice is one row and
     one read. */
  lines: jsonb("lines").$type<{ description: string; qty: number; unit: number }[]>().notNull().default([]),
  vatRate: integer("vat_rate").notNull().default(0),
  /* Kobo received. Maintained ONLY by the payment path below. */
  paid: bigint("paid", { mode: "number" }).notNull().default(0),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
}, (t) => [index("invoices_client_idx").on(t.clientId)]);

export const payments = pgTable("payments", {
  id: uuid("id").defaultRandom().primaryKey(),
  invoiceId: uuid("invoice_id").notNull(),
  at: timestamp("at", { withTimezone: true }).defaultNow().notNull(),
  amount: bigint("amount", { mode: "number" }).notNull(),
  method: text("method").notNull(),
  /* THE IDEMPOTENCY KEY. Paystack sends a webhook, the browser comes back
     through a callback, and a human can mark an invoice paid by hand -- three
     paths to the same event. Unique on the provider's reference means all
     three can fire and the money is still counted once. */
  reference: varchar("reference", { length: 128 }).notNull().unique(),
}, (t) => [index("payments_invoice_idx").on(t.invoiceId)]);

export const expenses = pgTable("expenses", {
  id: uuid("id").defaultRandom().primaryKey(),
  at: timestamp("at", { withTimezone: true }).defaultNow().notNull(),
  description: text("description").notNull(),
  category: text("category").notNull(),
  amount: bigint("amount", { mode: "number" }).notNull(),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
});

/* ------------------------------------------------------------------- forms */

export const submissions = pgTable("submissions", {
  id: uuid("id").defaultRandom().primaryKey(),
  clientId: uuid("client_id"),
  service: serviceEnum("service").notNull(),
  status: text("status").notNull().default("In progress"),
  startedAt: timestamp("started_at", { withTimezone: true }).defaultNow().notNull(),
  submittedAt: timestamp("submitted_at", { withTimezone: true }),
  /* The flat answer map the onboarding form already produces. It is JSONB
     because the questions change and a column per question would mean a
     migration every time somebody rewords one. */
  answers: jsonb("answers").$type<Record<string, string | string[]>>().notNull().default({}),
}, (t) => [index("submissions_client_idx").on(t.clientId)]);

/**
 * A half-finished onboarding form, resumable from any device.
 *
 * THIS IS WHAT LOCAL STORAGE CANNOT DO. The draft in a browser is one browser
 * on one machine and it dies with a cleared cache; this row is what a link in
 * an email resolves to. The token is the secret, so it is stored hashed and
 * compared by hash: a leaked database should not hand somebody every client's
 * half-written brief.
 */
export const resumeTokens = pgTable("resume_tokens", {
  id: uuid("id").defaultRandom().primaryKey(),
  submissionId: uuid("submission_id").notNull(),
  tokenHash: varchar("token_hash", { length: 64 }).notNull().unique(),
  email: varchar("email", { length: 320 }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  usedAt: timestamp("used_at", { withTimezone: true }),
});

/* ---------------------------------------------------------------- content */

/**
 * Editable content, merged by key over what is in git.
 *
 * THE SAFE PATTERN, and the reason for it: the site's copy lives in TypeScript
 * literals with derivation chains hanging off them -- WORK_CATEGORIES is
 * computed from SERVICES, the sitemap from WORK_CATEGORIES, the embed
 * allowlist from PROJECTS. Making those dynamic carelessly means one bad edit
 * empties a page. Overriding by key instead means the worst an edit can do is
 * change one value, and deleting the row restores what shipped.
 */
export const settings = pgTable("settings", {
  key: varchar("key", { length: 64 }).primaryKey(),
  value: jsonb("value").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});
