import { naira } from "@/lib/admin/types";
import { qrSvg } from "@/lib/qr";
import {
  COMPANY_NAME, CONTACT_EMAIL, REGISTERED_NAME, REGISTRAR, REGISTRATION_NO, SITE_URL,
} from "@/lib/site";

/**
 * THE TRANSACTIONAL EMAIL SET.
 *
 * Ten messages over one shell, so the studio's mail looks like one company
 * rather than ten afternoons. Every builder returns a complete `Email` --
 * subject, plain text, full HTML document -- and nothing here sends anything:
 * `sendMail()` in lib/email.ts is the only thing that talks to a mail server,
 * and every one of these is composed before it is called.
 *
 * WHY TABLES AND INLINE STYLES, in 2026. Outlook on Windows still renders mail
 * through Word's HTML engine, which has no flexbox, no grid, no `max-width`
 * worth the name and drops most of a `<style>` block. A table with widths on
 * the cells is the only layout every client agrees about. The `<style>` block
 * that IS here carries one media query for phones and nothing load-bearing:
 * remove it and the mail still reads.
 *
 * WHY A FULL DOCUMENT AND NOT A `<div>`. Every message this project sent
 * before this file existed was a bare `<div>`. A fragment has no charset, no
 * language, no viewport and no title, so Gmail guesses the encoding, iOS
 * shrinks the whole thing to fit a 980px page, and a screen reader announces
 * the message with no name. Filters also score a document-shaped message above
 * a fragment, which matters here more than usual -- see
 * plans/email-deliverability.md for why our reputation has no slack in it.
 *
 * WHY THE PLAIN TEXT IS WRITTEN, NOT STRIPPED. A `text` part generated by
 * pulling the tags off the HTML reads like a ransom note and every filter
 * knows what one looks like; a missing one is worse still, because Gmail
 * treats HTML-only mail as a bulk signal. So each message below writes its
 * text part as prose -- the same message, said the way you would say it in a
 * plain reply -- and it is the version a watch, a screen reader and a
 * text-only client actually get.
 *
 * WHY BLACK LABELS ON THE ORANGE BUTTON. The same measurement that governs the
 * site: white on #ff6500 is 2.95:1 and fails even the 3:1 WCAG allows large
 * text, black is 7.11:1. Pinned for the site by tests/button-colours.spec.ts
 * and for these by tests/email-templates.spec.ts.
 *
 * NO `server-only` HERE ON PURPOSE. This module builds strings: it holds no
 * credential, opens no connection and reads no environment beyond the public
 * site URL. Leaving the guard off is what lets the spec import it directly and
 * assert on the real output rather than on a copy of it.
 */

/* ------------------------------------------------------------------ tokens */

const NAVY = "#000065";
const ORANGE = "#ff6500";
const INK = "#0e0e2c";
const MUTED = "#666680";
const HAIRLINE = "#e7e7ef";
const PAGE = "#f4f4f8";
const CARD = "#ffffff";

/* The brand faces are named first for the handful of clients that have them
   installed locally, then the stack every other client will actually use. A
   webfont is not an option: Gmail strips `@font-face` outright. */
const DISPLAY = "'Space Grotesk','Segoe UI',Helvetica,Arial,sans-serif";
const BODY = "'Outfit','Segoe UI',Helvetica,Arial,sans-serif";

/** The content column. 600px is the width every client renders without help. */
const WIDTH = 600;

export type EmailAttachment = {
  filename: string;
  content: string;
  contentType: string;
  /** Referenced from the HTML as `cid:<id>`. */
  cid: string;
};

export type Email = {
  subject: string;
  text: string;
  html: string;
  attachments?: EmailAttachment[];
  /**
   * True for anything the recipient did not individually ask us to send. It
   * puts an unsubscribe line in the footer AND makes `sendMail()` set
   * `List-Unsubscribe`; the two must agree, which is why one flag drives both.
   */
  unsubscribe?: boolean;
};

/* ---------------------------------------------------------------- escaping */

/**
 * Everything interpolated into an HTML part goes through this.
 *
 * It lives here rather than in lib/email.ts because this is the module that
 * builds HTML; lib/email.ts re-exports it so its existing call sites are
 * unchanged. A client's company name is attacker-supplied text as surely as
 * anything on the web is -- somebody typed it into a form.
 */
export function escapeHtml(value: string) {
  return value.replace(/[&<>"']/g, (char) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;",
  })[char]!);
}

/**
 * A URL is only allowed into an `href` if it is one we could have made.
 *
 * `javascript:` in an anchor is mostly a browser problem rather than a mail
 * one, but these builders are also what the admin will preview in a browser,
 * and a rejected link that renders as our own site is a better failure than a
 * link that runs something.
 */
function resolveUrl(value: string) {
  return /^https?:\/\//i.test(value) ? value : SITE_URL;
}

function safeUrl(value: string) {
  return escapeHtml(resolveUrl(value));
}

/* -------------------------------------------------------------- formatting */

/**
 * One day, one spelling, one timezone.
 *
 * Lagos explicitly: a due date rendered from the server's own clock says the
 * 14th to a reader in Lagos and the 13th to the same invoice opened from a US
 * region, and an invoice that disagrees with itself about its due date is an
 * invoice somebody argues about.
 */
export function emailDate(value: Date) {
  return new Intl.DateTimeFormat("en-GB", {
    day: "numeric", month: "long", year: "numeric", timeZone: "Africa/Lagos",
  }).format(value);
}

function emailDateTime(value: Date) {
  return new Intl.DateTimeFormat("en-GB", {
    day: "numeric", month: "long", year: "numeric",
    hour: "2-digit", minute: "2-digit", timeZone: "Africa/Lagos",
  }).format(value);
}

/* ------------------------------------------------------------------ blocks */

/** A paragraph. Its argument is already-escaped markup, not raw user text. */
function p(html: string) {
  return `<p style="margin:0 0 16px;font-family:${BODY};font-size:16px;line-height:1.65;color:${INK}">${html}</p>`;
}

function small(html: string) {
  return `<p style="margin:0 0 16px;font-family:${BODY};font-size:13px;line-height:1.6;color:${MUTED}">${html}</p>`;
}

/**
 * The call to action.
 *
 * A table with a background on the cell rather than a styled anchor, because
 * Outlook ignores padding on an inline element and would render the button as
 * underlined text on a coloured word. The anchor still fills the cell, so the
 * whole shape is the target -- and it clears 44px, which is the same touch
 * target the site holds itself to.
 */
function action(label: string, href: string) {
  return (
    `<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:8px 0 20px">` +
    `<tr><td bgcolor="${ORANGE}" style="border-radius:10px">` +
    `<a href="${safeUrl(href)}" style="display:inline-block;padding:14px 26px;font-family:${BODY};font-size:16px;` +
    /* BLACK, measured. See the note at the top of this file. */
    `font-weight:700;color:#000000;text-decoration:none;border-radius:10px">${escapeHtml(label)}</a>` +
    `</td></tr></table>`
  );
}

/**
 * A quiet secondary copy of the link, for a client that ate the button.
 *
 * The visible text is the RESOLVED url, not the one that was passed in. A
 * rejected `javascript:` href that still printed itself as the link's label
 * would be a safe anchor under a line of text telling the reader to paste an
 * attack into their own address bar.
 */
function fallbackLink(href: string) {
  return small(
    `If the button does not work, copy this address into your browser:<br>` +
    `<a href="${safeUrl(href)}" style="color:${NAVY}">${safeUrl(href)}</a>`,
  );
}

/** A label/value panel: the facts of the message, set apart from the prose. */
function panel(rows: [string, string][]) {
  const cells = rows.map(([label, value], index) => {
    const top = index ? "10px" : "0";
    return (
      `<tr>` +
      `<td style="padding:${top} 0 0;font-family:${BODY};font-size:13px;color:${MUTED};width:42%;vertical-align:top">${escapeHtml(label)}</td>` +
      `<td style="padding:${top} 0 0;font-family:${BODY};font-size:15px;color:${INK};font-weight:600;vertical-align:top">${escapeHtml(value)}</td>` +
      `</tr>`
    );
  }).join("");
  return (
    `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" ` +
    `style="margin:0 0 20px;background:${PAGE};border:1px solid ${HAIRLINE};border-radius:12px">` +
    `<tr><td style="padding:18px 20px">` +
    `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">${cells}</table>` +
    `</td></tr></table>`
  );
}

export type MoneyLine = { description: string; qty: number; unit: number };
export type MoneyTotals = { subtotal: number; vat: number; vatRate: number; total: number };

/**
 * The lines of a quote or an invoice, and their totals.
 *
 * THE TOTALS ARE PASSED IN, NOT COMPUTED HERE. An email that does its own
 * arithmetic is a second opinion about what somebody owes, and the day it
 * disagrees with the invoice screen there is no way to tell which one is
 * right. The caller computes once, with `invoiceTotals()`, and hands the
 * answer over; this only renders it.
 */
function moneyTable(lines: MoneyLine[], totals: MoneyTotals) {
  const th = `padding:0 0 8px;font-family:${BODY};font-size:12px;letter-spacing:.08em;text-transform:uppercase;color:${MUTED};font-weight:600;border-bottom:1px solid ${HAIRLINE}`;
  const head =
    `<tr>` +
    `<th align="left" style="${th}">Item</th>` +
    `<th align="right" style="${th}">Qty</th>` +
    `<th align="right" style="${th}">Amount</th>` +
    `</tr>`;
  const body = lines.map((line) =>
    `<tr>` +
    `<td align="left" style="padding:12px 0;font-family:${BODY};font-size:15px;color:${INK};border-bottom:1px solid ${HAIRLINE}">${escapeHtml(line.description)}</td>` +
    `<td align="right" style="padding:12px 0 12px 12px;font-family:${BODY};font-size:15px;color:${MUTED};border-bottom:1px solid ${HAIRLINE}">${line.qty}</td>` +
    `<td align="right" style="padding:12px 0 12px 12px;font-family:${BODY};font-size:15px;color:${INK};white-space:nowrap;border-bottom:1px solid ${HAIRLINE}">${escapeHtml(naira(line.qty * line.unit))}</td>` +
    `</tr>`).join("");
  const subtotals: [string, string][] = [["Subtotal", naira(totals.subtotal)]];
  if (totals.vatRate) subtotals.push([`VAT (${totals.vatRate}%)`, naira(totals.vat)]);
  const foot = subtotals.map(([label, value]) =>
    `<tr><td colspan="2" align="right" style="padding:10px 0 0;font-family:${BODY};font-size:14px;color:${MUTED}">${escapeHtml(label)}</td>` +
    `<td align="right" style="padding:10px 0 0 12px;font-family:${BODY};font-size:14px;color:${INK};white-space:nowrap">${escapeHtml(value)}</td></tr>`).join("");
  const grand =
    `<tr><td colspan="2" align="right" style="padding:12px 0 0;font-family:${DISPLAY};font-size:16px;font-weight:700;color:${INK}">Total</td>` +
    `<td align="right" style="padding:12px 0 0 12px;font-family:${DISPLAY};font-size:18px;font-weight:700;color:${NAVY};white-space:nowrap">${escapeHtml(naira(totals.total))}</td></tr>`;
  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 22px">${head}${body}${foot}${grand}</table>`;
}

/** The same lines, for the text part. */
function moneyLinesText(lines: MoneyLine[], totals: MoneyTotals) {
  const rows = lines.map((line) => `  - ${line.description} (x${line.qty}): ${naira(line.qty * line.unit)}`);
  const tail = [`  Subtotal: ${naira(totals.subtotal)}`];
  if (totals.vatRate) tail.push(`  VAT (${totals.vatRate}%): ${naira(totals.vat)}`);
  tail.push(`  Total: ${naira(totals.total)}`);
  return [...rows, "", ...tail].join("\n");
}

const QR_CID = "wdc-document-qr";

/**
 * The document's QR code, as an attached SVG.
 *
 * IT REUSES `qrSvg()` rather than encoding a second time, so an invoice's code
 * is made by the same encoder, with the same measured module and error
 * correction decisions, as the ones on the site.
 *
 * THE MARK IS DELIBERATELY NOT PUNCHED INTO THIS ONE. `qrSvg` places it as an
 * `<image href>` pointing at a file on our site, and every mail client that
 * blocks remote images -- which is most of them, by default -- would render
 * the code with a hole in the middle and nothing in the hole. A code with a
 * hole in it is a damaged code, so this one keeps its modules and drops the
 * decoration.
 *
 * BE HONEST ABOUT WHAT RENDERS. Apple Mail draws SVG; Gmail and Outlook do
 * not. That is exactly why the URL sits beside it as ordinary text: the code
 * is a convenience for somebody holding a printed copy, never the only way to
 * reach the document. If delivery evidence ever shows people need the image
 * itself, the upgrade is a PNG out of the `qrcode` dependency we already have,
 * not a new package.
 */
async function documentQr(requested: string) {
  /* Resolved before it is encoded, so the code and the link beside it always
     point at the same, allowed, address. */
  const url = resolveUrl(requested);
  const svg = await qrSvg(url, { dark: NAVY, light: CARD, margin: 2, level: "M" });
  const html =
    `<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:4px 0 18px">` +
    `<tr><td style="padding:12px;background:${CARD};border:1px solid ${HAIRLINE};border-radius:12px">` +
    `<img src="cid:${QR_CID}" width="132" height="132" alt="QR code linking to this document" style="display:block;width:132px;height:132px">` +
    `</td>` +
    `<td style="padding-left:16px;vertical-align:middle">` +
    `<p style="margin:0;font-family:${BODY};font-size:13px;line-height:1.6;color:${MUTED}">Scan to open this document, or use the link.<br>` +
    `<a href="${safeUrl(url)}" style="color:${NAVY}">${escapeHtml(url)}</a></p>` +
    `</td></tr></table>`;
  const attachment: EmailAttachment = {
    filename: "document-qr.svg",
    content: svg,
    contentType: "image/svg+xml",
    cid: QR_CID,
  };
  return { html, attachment };
}

/* ------------------------------------------------------------------- shell */

const LEGAL_LINE =
  `${COMPANY_NAME}. ${REGISTERED_NAME}, ${REGISTRATION_NO}, registered with the ${REGISTRAR}.`;

/**
 * The unsubscribe target.
 *
 * A `mailto:` and not a URL, for the same reason lib/email.ts sets the
 * `List-Unsubscribe` header to one: there is no unsubscribe endpoint yet, and
 * a link to a page that does not exist is worse than an address a person can
 * read. Both change together the day the endpoint ships.
 */
const UNSUBSCRIBE_MAILTO = `mailto:${CONTACT_EMAIL}?subject=unsubscribe`;

/**
 * The frame every message in this file shares.
 *
 * `preheader` is the line the inbox shows after the subject. Left unset, a
 * client picks the first words it finds, which on a message that opens with a
 * greeting is "Hi Ada," -- a wasted second line in every inbox. The run of
 * zero-width spaces after it is the standard trick that stops Gmail appending
 * the body text to it.
 */
function shell(input: {
  title: string;
  preheader: string;
  eyebrow: string;
  heading: string;
  blocks: string[];
  unsubscribe?: boolean;
}) {
  const year = new Date().getFullYear();
  const unsubscribeRow = input.unsubscribe
    ? `<p style="margin:10px 0 0;font-family:${BODY};font-size:12px;line-height:1.6;color:${MUTED}">` +
      `You are receiving this because you contacted We Dig Creativity or are working with us on a project. ` +
      `<a href="${UNSUBSCRIBE_MAILTO}" style="color:${MUTED};text-decoration:underline">Unsubscribe</a>.</p>`
    : "";

  return `<!doctype html>
<html lang="en" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="x-apple-disable-message-reformatting">
<meta name="color-scheme" content="light">
<meta name="supported-color-schemes" content="light">
<title>${escapeHtml(input.title)}</title>
<!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml><![endif]-->
<style>
  /* The one rule that needs a stylesheet: a 600px table has to become a
     full-width one on a phone, and no inline style can express a breakpoint.
     Everything else is inline, so a client that drops this block loses
     nothing but the narrow layout. */
  @media only screen and (max-width:620px){
    .wdc-wrap{width:100% !important}
    .wdc-pad{padding-left:22px !important;padding-right:22px !important}
  }
</style>
</head>
<body style="margin:0;padding:0;background:${PAGE};-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%">
<div style="display:none;max-height:0;overflow:hidden;opacity:0;mso-hide:all">${escapeHtml(input.preheader)}&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:${PAGE}">
<tr><td align="center" style="padding:28px 12px">
<table role="presentation" class="wdc-wrap" width="${WIDTH}" cellpadding="0" cellspacing="0" border="0" style="width:${WIDTH}px;max-width:${WIDTH}px;background:${CARD};border:1px solid ${HAIRLINE};border-radius:16px">

<tr><td bgcolor="${NAVY}" class="wdc-pad" style="padding:22px 32px;background:${NAVY};border-radius:16px 16px 0 0">
  <table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr>
    <td style="padding-right:12px"><img src="${SITE_URL}/icon-192.png" width="36" height="36" alt="" style="display:block;width:36px;height:36px;border-radius:8px"></td>
    <td style="font-family:${DISPLAY};font-size:17px;font-weight:700;letter-spacing:.01em;color:#ffffff">We Dig Creativity</td>
  </tr></table>
</td></tr>

<tr><td class="wdc-pad" style="padding:32px 32px 8px">
  <p style="margin:0 0 10px;font-family:${BODY};font-size:11px;font-weight:700;letter-spacing:.14em;text-transform:uppercase;color:${ORANGE}">${escapeHtml(input.eyebrow)}</p>
  <h1 style="margin:0 0 18px;font-family:${DISPLAY};font-size:26px;line-height:1.25;font-weight:700;color:${INK}">${escapeHtml(input.heading)}</h1>
  ${input.blocks.join("\n  ")}
</td></tr>

<tr><td class="wdc-pad" style="padding:8px 32px 28px">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="border-top:1px solid ${HAIRLINE};padding-top:18px">
    <p style="margin:0 0 6px;font-family:${BODY};font-size:13px;line-height:1.6;color:${MUTED}">
      <a href="${SITE_URL}" style="color:${NAVY};text-decoration:none;font-weight:600">wedigcreativity.com.ng</a>
      &nbsp;&middot;&nbsp;<a href="mailto:${CONTACT_EMAIL}" style="color:${MUTED};text-decoration:none">${CONTACT_EMAIL}</a>
    </p>
    <p style="margin:0;font-family:${BODY};font-size:12px;line-height:1.6;color:${MUTED}">&copy; ${year} ${escapeHtml(LEGAL_LINE)}</p>
    ${unsubscribeRow}
  </td></tr></table>
</td></tr>

</table>
</td></tr>
</table>
</body>
</html>`;
}

/**
 * The signature and legal tail of the text part.
 *
 * The plain text carries the same footer the HTML does, because for a reader
 * on a text-only client it IS the message -- and an unsubscribe offered only
 * to people whose client renders HTML is not an unsubscribe.
 */
function textShell(body: string, options: { unsubscribe?: boolean } = {}) {
  const tail = [
    "",
    "--",
    "We Dig Creativity",
    SITE_URL.replace(/^https?:\/\//, ""),
    CONTACT_EMAIL,
    "",
    LEGAL_LINE,
  ];
  if (options.unsubscribe) {
    tail.push(
      "",
      "You are receiving this because you contacted We Dig Creativity or are",
      `working with us on a project. To stop these messages, reply to ${CONTACT_EMAIL}`,
      "with the word unsubscribe.",
    );
  }
  return `${body.trim()}\n${tail.join("\n")}\n`;
}

/* ================================================================ 1. enquiry */

export function enquiryReceiptEmail(input: { firstName: string; topic: string }): Email {
  const { firstName, topic } = input;
  return {
    subject: "We received your message: We Dig Creativity",
    /* The enquirer asked us a question; they did not ask for this copy. That
       is the whole test for `unsubscribe`, and this is the clearest case. */
    unsubscribe: true,
    text: textShell(`Hi ${firstName},

Your message about ${topic} reached us, and somebody on the team will read it
properly rather than reply automatically. You can expect an answer within the
same working day.

If anything has changed since you wrote, or you left something out, reply to
this email and it lands on the same thread.

Thank you for getting in touch.

The WDC team`, { unsubscribe: true }),
    html: shell({
      title: "We received your message",
      preheader: `Your message about ${topic} is with us. We reply the same working day.`,
      eyebrow: "Enquiry received",
      heading: "Your message is with us.",
      unsubscribe: true,
      blocks: [
        p(`Hi ${escapeHtml(firstName)},`),
        p(`Your message about <b>${escapeHtml(topic)}</b> reached us, and somebody on the team will read it properly rather than reply automatically. You can expect an answer within the same working day.`),
        p("If anything has changed since you wrote, or you left something out, reply to this email and it lands on the same thread."),
        small("A copy was sent automatically so you know the form worked."),
      ],
    }),
  };
}

/* ===================================================== 2. onboarding invite */

export function onboardingInvitationEmail(input: {
  name: string;
  service: string;
  url: string;
  /** How long the link lives, in days. Stated because it is true, not to rush. */
  expiresInDays: number;
}): Email {
  const { name, service, url, expiresInDays } = input;
  return {
    subject: `Start your ${service} project with WDC`,
    text: textShell(`Hi ${name},

Welcome aboard. Before we start on your ${service} project we need the brief in
your own words: what the work has to achieve, who it is for, and what already
exists that we should build on.

The form is here, and you can leave it and come back to it on any device:

${url}

It takes about ten minutes if you have the details to hand, and rather less if
you answer "I'm not sure, please advise me" wherever you would rather we took
the decision. That is a real answer, and you can change it later.

The link works for ${expiresInDays} days. If it expires, reply to this email
and we will send a fresh one.

The WDC team`),
    html: shell({
      title: "Start your project",
      preheader: `Your ${service} onboarding form is ready. It takes about ten minutes.`,
      eyebrow: "Onboarding",
      heading: "Welcome aboard. Tell us about the work.",
      blocks: [
        p(`Hi ${escapeHtml(name)},`),
        p(`Before we start on your <b>${escapeHtml(service)}</b> project we need the brief in your own words: what the work has to achieve, who it is for, and what already exists that we should build on.`),
        action("Open the onboarding form", url),
        p(`It takes about ten minutes if you have the details to hand, and rather less if you answer <i>&ldquo;I'm not sure, please advise me&rdquo;</i> wherever you would rather we took the decision. That is a real answer, and you can change it later.`),
        small(`You can leave the form and come back to it on any device. The link works for ${expiresInDays} days &mdash; if it expires, reply to this email and we will send a fresh one.`),
        fallbackLink(url),
      ],
    }),
  };
}

/* =================================================== 3. onboarding reminder */

export function onboardingReminderEmail(input: {
  name: string;
  service: string;
  url: string;
  /** Whole percent, from answered questions over total. Never invented. */
  progressPercent: number;
  daysLeft: number;
}): Email {
  const { name, service, url, progressPercent, daysLeft } = input;
  const where = progressPercent > 0
    ? `You are about ${progressPercent}% of the way through, and everything you typed is saved.`
    : "Nothing is filled in yet, so it is a clean start whenever you have ten minutes.";
  const deadline = daysLeft === 1 ? "tomorrow" : `in ${daysLeft} days`;
  return {
    subject: `Your ${service} brief is still open`,
    /* A reminder is the definition of mail the recipient did not ask for
       today, whatever they agreed to last week. */
    unsubscribe: true,
    text: textShell(`Hi ${name},

Your onboarding form for the ${service} project is still open. ${where}

Pick up where you left off:

${url}

This link expires ${deadline}. There is no rush from our side beyond that -- we
simply cannot schedule the work until we know what it is.

If the project is on hold, or is not going ahead after all, reply and say so
and we will stop reminding you.

The WDC team`, { unsubscribe: true }),
    html: shell({
      title: "Your brief is still open",
      preheader: `${where} The link expires ${deadline}.`,
      eyebrow: "Reminder",
      heading: "Your brief is still open.",
      unsubscribe: true,
      blocks: [
        p(`Hi ${escapeHtml(name)},`),
        p(`Your onboarding form for the <b>${escapeHtml(service)}</b> project is still open. ${escapeHtml(where)}`),
        action("Pick up where you left off", url),
        p(`This link expires ${escapeHtml(deadline)}. There is no rush from our side beyond that &mdash; we simply cannot schedule the work until we know what it is.`),
        small("If the project is on hold, or is not going ahead after all, reply and say so and we will stop reminding you."),
        fallbackLink(url),
      ],
    }),
  };
}

/* ================================================ 3b. onboarding next steps */

/**
 * "We have your brief. Here is what happens now."
 *
 * Sent once, after the form is submitted. It names every channel the project
 * might run on, because a client who has only ever seen an email from us will
 * otherwise be surprised by a WhatsApp group, and one who prefers WhatsApp
 * should know they can say so.
 *
 * THE ACCOUNT IS OPTIONAL, AND SAID SO. Nothing about the work needs one. The
 * invitation is offered, not sent: it is bound to this address when a person
 * issues it, which is what stops a forwarded email registering somebody else.
 */
export function onboardingNextStepsEmail(input: { name: string; service: string; company?: string }): Email {
  const { name, service, company } = input;
  const forWhom = company ? ` for ${company}` : "";
  return {
    subject: `Thank you, ${name}: your ${service} brief is with us`,
    /* They asked for the work, not for this message, which is the test the
       enquiry receipt uses too. */
    unsubscribe: true,
    text: textShell(`Hi ${name},

Thank you for completing the onboarding form for your ${service} project${forWhom}.
Your answers are saved and the brief is with the team.

What happens next:

1. Somebody on the team reads your brief properly. Anything you marked "I'm not
   sure, please advise me" is ours to recommend, and we will explain why.
2. We come back to you with any questions, then the proposed scope and price.
3. Once you are happy with both, we agree a start date and begin.

How we will stay in touch: project communication may happen through the client
dashboard, direct chat by email, a WhatsApp project group where that suits the
work, or another channel we agree with you. Reply and tell us what you prefer.

You do not need an account to work with us. If you would like to follow the
project in the client dashboard, reply and ask, and we will send a personal
invitation tied to this email address.

The WDC team`, { unsubscribe: true }),
    html: shell({
      title: "Your brief is with us",
      preheader: `Your ${service} brief is saved. Here is what happens next.`,
      eyebrow: "Onboarding complete",
      heading: "Thank you. Your brief is with us.",
      unsubscribe: true,
      blocks: [
        p(`Hi ${escapeHtml(name)},`),
        p(`Thank you for completing the onboarding form for your <b>${escapeHtml(service)}</b> project${escapeHtml(forWhom)}. Your answers are saved and the brief is with the team.`),
        panel([
          ["First", "We read your brief properly, and recommend on anything you asked us to advise on."],
          ["Then", "We come back with any questions, then the proposed scope and price."],
          ["After that", "Once you are happy with both, we agree a start date and begin."],
        ]),
        p("Project communication may happen through the client dashboard, direct chat by email, a WhatsApp project group where that suits the work, or another channel we agree with you. Reply and tell us what you prefer."),
        small("You do not need an account to work with us. If you would like to follow the project in the client dashboard, reply and ask, and we will send a personal invitation tied to this email address."),
      ],
    }),
  };
}

/* ================================================================== 4. quote */

export function quoteEmail(input: {
  clientName: string;
  quoteNumber: string;
  projectTitle: string;
  lines: MoneyLine[];
  totals: MoneyTotals;
  validUntil: Date;
  url: string;
}): Email {
  const { clientName, quoteNumber, projectTitle, lines, totals, validUntil, url } = input;
  return {
    subject: `Quote ${quoteNumber} - ${projectTitle}`,
    text: textShell(`Hi ${clientName},

Here is our quote for ${projectTitle}, reference ${quoteNumber}.

${moneyLinesText(lines, totals)}

This quote holds until ${emailDate(validUntil)}. It covers the work described
above and nothing else; anything added later is quoted separately before it
starts, so there are no surprises on the invoice.

Read it in full and accept it here:

${url}

If something in the scope is wrong, or you want a line taken out, say so and we
will re-issue rather than argue about it later.

The WDC team`),
    html: shell({
      title: `Quote ${quoteNumber}`,
      preheader: `${projectTitle}, ${naira(totals.total)}, valid until ${emailDate(validUntil)}.`,
      eyebrow: `Quote ${quoteNumber}`,
      heading: projectTitle,
      blocks: [
        p(`Hi ${escapeHtml(clientName)},`),
        p("Here is our quote for the work as we understand it."),
        moneyTable(lines, totals),
        panel([
          ["Quote reference", quoteNumber],
          ["Valid until", emailDate(validUntil)],
        ]),
        action("Read and accept the quote", url),
        p("This quote covers the work described above and nothing else. Anything added later is quoted separately before it starts, so there are no surprises on the invoice."),
        small("If something in the scope is wrong, or you want a line taken out, say so and we will re-issue rather than argue about it later."),
        fallbackLink(url),
      ],
    }),
  };
}

/* ================================================================ 5. invoice */

export async function invoiceEmail(input: {
  clientName: string;
  number: string;
  projectTitle: string;
  lines: MoneyLine[];
  totals: MoneyTotals;
  /** Kobo already received against this invoice. Zero on a first issue. */
  paid: number;
  issued: Date;
  due: Date;
  url: string;
}): Promise<Email> {
  const { clientName, number, projectTitle, lines, totals, paid, issued, due, url } = input;
  const outstanding = Math.max(0, totals.total - paid);
  const partPaid = paid > 0 && outstanding > 0;
  const qr = await documentQr(url);

  const rows: [string, string][] = [
    ["Invoice number", number],
    ["Issued", emailDate(issued)],
    ["Due", emailDate(due)],
  ];
  if (paid > 0) rows.push(["Already paid", naira(paid)]);
  rows.push([partPaid ? "Balance outstanding" : "Amount due", naira(outstanding)]);

  const paidLine = paid > 0 ? `  Already paid: ${naira(paid)}\n` : "";
  const dueLabel = partPaid ? "Balance outstanding" : "Amount due";

  return {
    subject: `Invoice ${number} - ${naira(outstanding)} due ${emailDate(due)}`,
    attachments: [qr.attachment],
    text: textShell(`Hi ${clientName},

This is invoice ${number} for ${projectTitle}.

${moneyLinesText(lines, totals)}
${paidLine}  ${dueLabel}: ${naira(outstanding)}

Issued ${emailDate(issued)}, due ${emailDate(due)}.

You can read the invoice and pay it here:

${url}

Card and bank transfer both work through that link. If you would rather send a
direct transfer, or pay by cash or POS, tell us which and we will record it
against this invoice so your statement stays straight.

The WDC team`),
    html: shell({
      title: `Invoice ${number}`,
      preheader: `${naira(outstanding)} due ${emailDate(due)} for ${projectTitle}.`,
      eyebrow: `Invoice ${number}`,
      heading: partPaid ? "Balance outstanding on your invoice" : "Your invoice is ready",
      blocks: [
        p(`Hi ${escapeHtml(clientName)},`),
        p(`This is invoice <b>${escapeHtml(number)}</b> for ${escapeHtml(projectTitle)}.`),
        moneyTable(lines, totals),
        panel(rows),
        action("Read and pay the invoice", url),
        qr.html,
        p("Card and bank transfer both work through that link. If you would rather send a direct transfer, or pay by cash or POS, tell us which and we will record it against this invoice so your statement stays straight."),
        fallbackLink(url),
      ],
    }),
  };
}

/* ================================================================ 6. receipt */

export async function receiptEmail(input: {
  clientName: string;
  receiptNumber: string;
  invoiceNumber: string;
  amount: number;
  method: string;
  reference: string;
  paidAt: Date;
  /** Kobo still owed on the invoice after this payment. */
  balance: number;
  url: string;
}): Promise<Email> {
  const { clientName, receiptNumber, invoiceNumber, amount, method, reference, paidAt, balance, url } = input;
  const qr = await documentQr(url);
  const settled = balance <= 0;
  const balanceLine = settled
    ? "Balance: nothing further is owed on this invoice."
    : `Balance still outstanding: ${naira(balance)}`;

  return {
    subject: `Receipt ${receiptNumber} - ${naira(amount)} received`,
    attachments: [qr.attachment],
    text: textShell(`Hi ${clientName},

We have received ${naira(amount)} against invoice ${invoiceNumber}. Thank you.

  Receipt number: ${receiptNumber}
  Invoice: ${invoiceNumber}
  Amount received: ${naira(amount)}
  Method: ${method}
  Reference: ${reference}
  Received: ${emailDateTime(paidAt)}
  ${balanceLine}

Your copy of the receipt is here:

${url}

Keep it for your records. If any detail above does not match what you sent,
reply to this email and we will look at it the same day.

The WDC team`),
    html: shell({
      title: `Receipt ${receiptNumber}`,
      preheader: `${naira(amount)} received against invoice ${invoiceNumber}.`,
      eyebrow: `Receipt ${receiptNumber}`,
      heading: `${naira(amount)} received. Thank you.`,
      blocks: [
        p(`Hi ${escapeHtml(clientName)},`),
        p(`This confirms a payment against invoice <b>${escapeHtml(invoiceNumber)}</b>.`),
        panel([
          ["Receipt number", receiptNumber],
          ["Invoice", invoiceNumber],
          ["Amount received", naira(amount)],
          ["Method", method],
          ["Reference", reference],
          ["Received", emailDateTime(paidAt)],
          ["Balance", settled ? "Nothing further owed" : naira(balance)],
        ]),
        action("Open your receipt", url),
        qr.html,
        small("Keep it for your records. If any detail above does not match what you sent, reply to this email and we will look at it the same day."),
        fallbackLink(url),
      ],
    }),
  };
}

/* ========================================================== 7. project stage */

export function projectStageEmail(input: {
  clientName: string;
  projectTitle: string;
  fromStage: string;
  toStage: string;
  /** What actually changed, in the studio's words. Optional, never invented. */
  note?: string;
  url: string;
}): Email {
  const { clientName, projectTitle, fromStage, toStage, note, url } = input;
  return {
    subject: `${projectTitle} is now at ${toStage}`,
    /* A progress notice is useful mail, and it is still mail nobody asked for
       on the day it arrives. */
    unsubscribe: true,
    text: textShell(`Hi ${clientName},

${projectTitle} has moved from ${fromStage} to ${toStage}.
${note ? `\n${note}\n` : ""}
You can see where the project stands, and everything that has happened on it so
far, here:

${url}

Nothing is needed from you unless we have asked for it separately.

The WDC team`, { unsubscribe: true }),
    html: shell({
      title: `${projectTitle} - ${toStage}`,
      preheader: `Moved from ${fromStage} to ${toStage}.`,
      eyebrow: "Project update",
      heading: `${projectTitle} is now at ${toStage}.`,
      unsubscribe: true,
      blocks: [
        p(`Hi ${escapeHtml(clientName)},`),
        panel([["Was", fromStage], ["Now", toStage]]),
        ...(note ? [p(escapeHtml(note))] : []),
        action("See the project", url),
        small("Nothing is needed from you unless we have asked for it separately."),
        fallbackLink(url),
      ],
    }),
  };
}

/* ===================================================== 8. deliverable ready */

export function deliverableReadyEmail(input: {
  clientName: string;
  projectTitle: string;
  deliverable: string;
  url: string;
  /** When we need the answer, so the schedule cannot slip silently. */
  respondBy: Date;
}): Email {
  const { clientName, projectTitle, deliverable, url, respondBy } = input;
  return {
    subject: `${deliverable} is ready for your approval`,
    text: textShell(`Hi ${clientName},

${deliverable} for ${projectTitle} is ready for you to look at.

Open it here, leave any comments directly on it, and either approve it or send
it back with changes:

${url}

We have held ${emailDate(respondBy)} in the schedule for your answer. If it
comes later than that, the stages after it move by the same amount -- which is
the only reason we mention a date at all.

The WDC team`),
    html: shell({
      title: `${deliverable} is ready`,
      preheader: `${deliverable} for ${projectTitle} is ready for your approval.`,
      eyebrow: "Ready for approval",
      heading: `${deliverable} is ready for you.`,
      blocks: [
        p(`Hi ${escapeHtml(clientName)},`),
        p(`${escapeHtml(deliverable)} for <b>${escapeHtml(projectTitle)}</b> is ready. Open it, leave any comments directly on it, and either approve it or send it back with changes.`),
        action("Review and approve", url),
        panel([["Project", projectTitle], ["We have held", emailDate(respondBy)]]),
        p(`If your answer comes after ${escapeHtml(emailDate(respondBy))}, the stages after it move by the same amount &mdash; which is the only reason we mention a date at all.`),
        fallbackLink(url),
      ],
    }),
  };
}

/* =============================================================== 9. sign-off */

export function signOffEmail(input: {
  clientName: string;
  projectTitle: string;
  deliverable: string;
  signedBy: string;
  signedAt: Date;
  url: string;
}): Email {
  const { clientName, projectTitle, deliverable, signedBy, signedAt, url } = input;
  return {
    subject: `Signed off: ${deliverable}`,
    text: textShell(`Hi ${clientName},

${deliverable} on ${projectTitle} is signed off. This is your record of it.

  Signed off by: ${signedBy}
  Date: ${emailDateTime(signedAt)}
  Project: ${projectTitle}

The signed record is kept with the project, and you can open it at any time:

${url}

Work on the next stage starts from here. If anything about this approval looks
wrong, tell us before we build on it rather than after.

The WDC team`),
    html: shell({
      title: `Signed off: ${deliverable}`,
      preheader: `${deliverable} was signed off by ${signedBy}.`,
      eyebrow: "Sign-off",
      heading: `${deliverable} is signed off.`,
      blocks: [
        p(`Hi ${escapeHtml(clientName)},`),
        p("This is your record of the approval."),
        panel([
          ["Signed off by", signedBy],
          ["Date", emailDateTime(signedAt)],
          ["Project", projectTitle],
        ]),
        action("Open the signed record", url),
        p("Work on the next stage starts from here. If anything about this approval looks wrong, tell us before we build on it rather than after."),
        fallbackLink(url),
      ],
    }),
  };
}

/* ======================================================== 10. password reset */

export function passwordResetEmail(input: {
  /** First name where we have one; the address is a poor substitute but true. */
  name?: string;
  url: string;
  expiresInMinutes: number;
}): Email {
  const { name, url, expiresInMinutes } = input;
  const greeting = name ? `Hi ${name},` : "Hello,";
  const life = expiresInMinutes === 60 ? "one hour" : `${expiresInMinutes} minutes`;
  return {
    subject: "Reset your We Dig Creativity password",
    /* NO unsubscribe on this one, and that is deliberate. A password reset is
       a message the recipient asked for seconds ago, and offering to
       unsubscribe from account security is how somebody loses access to their
       own account. `List-Unsubscribe` is for bulk mail; this is not bulk. */
    text: textShell(`${greeting}

Somebody asked to reset the password on your We Dig Creativity account. If that
was you, open this link within ${life} and choose a new one:

${url}

The link works once, and then stops working.

If it was not you, nothing has happened and there is nothing you need to do.
Your current password still works and nobody has been let in. If these keep
arriving, reply and tell us -- that is worth knowing.

The WDC team`),
    html: shell({
      title: "Reset your password",
      preheader: `Choose a new password. The link works once and expires in ${life}.`,
      eyebrow: "Account security",
      heading: "Reset your password",
      blocks: [
        p(escapeHtml(greeting)),
        p("Somebody asked to reset the password on your We Dig Creativity account. If that was you, choose a new one now."),
        action("Choose a new password", url),
        p(`The link works once, and expires in ${escapeHtml(life)}.`),
        small("If it was not you, nothing has happened and there is nothing you need to do &mdash; your current password still works and nobody has been let in. If these keep arriving, reply and tell us."),
        fallbackLink(url),
      ],
    }),
  };
}

/* ============================================== 11. the estimate, on request */

/**
 * The scope estimate, sent because the reader asked for a copy.
 *
 * THE FIGURES ARE PASSED IN, NOT COMPUTED HERE, for the same reason the money
 * table's totals are: an email that does its own arithmetic is a second
 * opinion about a number, and the day it disagrees with the page the reader
 * saw there is no way to tell which one is right. `lib/estimate.ts` computes
 * once, on the server, from the answers; this renders what it returned.
 *
 * IT REPEATS THE ANSWERS. The estimate is worthless in a month without them --
 * "₦4m to ₦6m" in an inbox with no note of what was being priced is a number
 * somebody will quote back at us for a different project. Printed as a panel,
 * they are also the fastest possible brief for whoever picks up the reply.
 */
export function scopeEstimateEmail(input: {
  /** Already formatted by the caller, in the currency and shape the page used. */
  rangeNgn: string;
  rangeUsd: string;
  days: number;
  phases: Array<{ label: string; range: string }>;
  answers: Array<{ question: string; answer: string }>;
  assumptions: string[];
  url: string;
}): Email {
  const { rangeNgn, rangeUsd, days, phases, answers, assumptions, url } = input;

  const phaseRows = phases.map((phase) => [phase.label, phase.range] as [string, string]);
  const answerRows = answers.map((row) => [row.question, row.answer] as [string, string]);

  return {
    subject: `Your indicative range: ${rangeNgn}`,
    /* NO UNSUBSCRIBE, and the rule is the one the enquiry receipt states from
       the other side. There, the enquirer asked us a question and did not ask
       for the copy, so the copy owes them an opt-out. Here the reader pressed
       "email it to me": this message IS the thing they asked for, like the
       password reset, and an unsubscribe line on it offers to opt out of the
       only thing they wanted. They are added to no list, so there is nothing
       to opt out of. The day this is followed by anything they did not ask
       for, that message carries the flag. */
    text: textShell(`Hello,

Here is the range you worked out on our estimator, with the answers you gave so
it still makes sense when you open this in a fortnight.

  Indicative range: ${rangeNgn} (${rangeUsd})
  Roughly ${days} days of the team's time

Where it goes:
${phaseRows.map(([label, range]) => `  - ${label}: ${range}`).join("\n")}

What you told us:
${answerRows.map(([question, answer]) => `  - ${question} ${answer}`).join("\n")}

What it assumes:
${assumptions.map((line) => `  - ${line}`).join("\n")}

This is a range and not a quote. It is what work of this shape usually costs us
to do properly, and the real figure comes out of one conversation about what you
actually need. Reply to this email and we will have it.

${url}

The WDC team`),
    html: shell({
      title: "Your indicative range",
      preheader: `${rangeNgn} for the project you described, with the phases broken out.`,
      eyebrow: "Indicative range",
      heading: rangeNgn,
      blocks: [
        p(`That is ${escapeHtml(rangeUsd)}, and about <b>${days} days</b> of the team&rsquo;s time. Calendar time is longer, because your review and ours both take days nobody is building on.`),
        p("<b>Where it goes</b>"),
        panel(phaseRows),
        p("<b>What you told us</b>"),
        panel(answerRows),
        p("<b>What it assumes</b>"),
        small(assumptions.map((line) => `&bull; ${escapeHtml(line)}`).join("<br>")),
        p("This is a range and not a quote. It is what work of this shape usually costs us to do properly, and the real figure comes out of one conversation about what you actually need."),
        action("Talk it through with us", url),
        fallbackLink(url),
      ],
    }),
  };
}

/* ========================================== 12. the site report, on request */

/**
 * The on-page report from /tools/seo, sent once the reader gives an address.
 *
 * IT IS SENT WHETHER OR NOT LIGHTHOUSE RAN. That is the whole shape of this
 * message and it comes from rule 1 of `docs/tools-programme.md`: the metered
 * half is an upgrade on an answer we can already give free, never the answer
 * itself. On a day the PageSpeed budget is spent, or on an installation with
 * no key at all, `scores` is empty and the mail carries the on-page findings
 * plus a line saying a person will run the rest. That is a better outcome for
 * the reader than an apology, and a better one for us than silence.
 */
export function siteReportEmail(input: {
  site: string;
  /** The on-page findings, already reduced to a label and a verdict. */
  findings: Array<{ label: string; detail: string }>;
  /** Lighthouse, where it ran. Empty means it did not, and the copy changes. */
  scores: Array<{ label: string; score: number }>;
  /** The biggest wins Lighthouse named, where it ran. */
  opportunities: string[];
  url: string;
}): Email {
  const { site, findings, scores, opportunities, url } = input;
  const ran = scores.length > 0;

  const scoreRows = scores.map((s) => [s.label, `${s.score} / 100`] as [string, string]);
  const findingRows = findings.map((f) => [f.label, f.detail] as [string, string]);

  const lighthouseText = ran
    ? `Lighthouse, run by Google on your live page:
${scoreRows.map(([label, value]) => `  - ${label}: ${value}`).join("\n")}

${opportunities.length ? `The biggest wins it found:\n${opportunities.map((o) => `  - ${o}`).join("\n")}` : "It found nothing large enough to be worth naming, which is rarer than you would think."}`
    : `The full Lighthouse run is queued rather than attached: we cap how many of
those we ask Google for in a day, and today's are spent. Somebody here will run
yours by hand and reply with it. Nothing above depends on it.`;

  return {
    subject: `Your site report: ${site}`,
    /* No unsubscribe, for the reason written on the estimate above: they asked
       for this one message, it is the thing they asked for, and nothing is
       added to any list. */
    text: textShell(`Hello,

Here is the report for ${site}, in full and in writing so you can forward it to
whoever looks after the site.

What we read off the page itself:
${findingRows.map(([label, detail]) => `  - ${label}: ${detail}`).join("\n")}

${lighthouseText}

Every one of these is fixable, and most of them are an afternoon rather than a
rebuild. Reply to this email if you would like us to do it, or to argue with any
of it.

${url}

The WDC team`),
    html: shell({
      title: "Your site report",
      preheader: `The on-page findings for ${site}${ran ? ", with Lighthouse scores" : ""}.`,
      eyebrow: "Site report",
      heading: escapeHtml(site),
      blocks: [
        p("Here is the report in full, so you can forward it to whoever looks after the site."),
        p("<b>What we read off the page itself</b>"),
        panel(findingRows),
        ...(ran
          ? [
              p("<b>Lighthouse, run by Google on your live page</b>"),
              panel(scoreRows),
              ...(opportunities.length
                ? [small(`The biggest wins it found:<br>${opportunities.map((o) => `&bull; ${escapeHtml(o)}`).join("<br>")}`)]
                : [small("It found nothing large enough to be worth naming, which is rarer than you would think.")]),
            ]
          : [
              p("<b>The Lighthouse run is queued</b>"),
              small("We cap how many of those we ask Google for in a day, and today&rsquo;s are spent. Somebody here will run yours by hand and reply with it &mdash; nothing above depends on it."),
            ]),
        p("Every one of these is fixable, and most of them are an afternoon rather than a rebuild."),
        action("Ask us to fix them", url),
        fallbackLink(url),
      ],
    }),
  };
}
