import { naira } from "@/lib/admin/types";
import { qrSvg } from "@/lib/qr";
import {
  COMPANY_NAME, CONTACT_EMAIL, LOCATION, REGISTERED_NAME, REGISTRAR, REGISTRATION_NO, SITE_URL,
} from "@/lib/site";

/**
 * THE TRANSACTIONAL EMAIL SET.
 *
 * Ten messages over one shell, so the studio's mail looks like one company
 * rather than ten afternoons. Every builder returns a complete `Email` --
 * subject, plain text, full HTML document -- and nothing here sends anything:
 * `sendMail()` in lib/email.ts is the only thing that talks to a mail server,
 * and every one of these is composed before it is called.
 *
 * WHY TABLES AND INLINE STYLES, in 2026. Outlook on Windows still renders mail
 * through Word's HTML engine, which has no flexbox, no grid, no `max-width`
 * worth the name and drops most of a `<style>` block. A table with widths on
 * the cells is the only layout every client agrees about. The `<style>` block
 * that IS here carries one media query for phones and nothing load-bearing:
 * remove it and the mail still reads.
 *
 * WHY A FULL DOCUMENT AND NOT A `<div>`. Every message this project sent
 * before this file existed was a bare `<div>`. A fragment has no charset, no
 * language, no viewport and no title, so Gmail guesses the encoding, iOS
 * shrinks the whole thing to fit a 980px page, and a screen reader announces
 * the message with no name. Filters also score a document-shaped message above
 * a fragment, which matters here more than usual -- see
 * plans/email-deliverability.md for why our reputation has no slack in it.
 *
 * WHY THE PLAIN TEXT IS WRITTEN, NOT STRIPPED. A `text` part generated by
 * pulling the tags off the HTML reads like a ransom note and every filter
 * knows what one looks like; a missing one is worse still, because Gmail
 * treats HTML-only mail as a bulk signal. So each message below writes its
 * text part as prose -- the same message, said the way you would say it in a
 * plain reply -- and it is the version a watch, a screen reader and a
 * text-only client actually get.
 *
 * WHY THE BUTTON IS A DEEPER ORANGE THAN THE LOGO. The label is white, and
 * white on #ff6500 measures 2.95:1, which fails AA. #c95000 is the site's own
 * `--accent-ink`, the orange it already uses wherever orange has to be read,
 * and white on it is 4.53:1. Pinned by tests/email-templates.spec.ts.
 *
 * NO `server-only` HERE ON PURPOSE. This module builds strings: it holds no
 * credential, opens no connection and reads no environment beyond the public
 * site URL. Leaving the guard off is what lets the spec import it directly and
 * assert on the real output rather than on a copy of it.
 */

/* ------------------------------------------------------------------ tokens */

const NAVY = "#000065";
/** The button's fill: see the note at the top of this file. */
const ACCENT_INK = "#c95000";
const INK = "#0e0e2c";
const MUTED = "#666680";
const HAIRLINE = "#e7e7ef";
const PAGE = "#f4f4f8";
const CARD = "#ffffff";

/* The brand faces are named first for the handful of clients that have them
   installed locally, then the stack every other client will actually use. A
   webfont is not an option: Gmail strips `@font-face` outright. */
const DISPLAY = "'Space Grotesk','Segoe UI',Helvetica,Arial,sans-serif";
const BODY = "'Outfit','Segoe UI',Helvetica,Arial,sans-serif";

/** Where the pictures live: built by scripts/build-email-assets.mjs. */
const ASSETS = `${SITE_URL}/email`;

/** The content column. 600px is the width every client renders without help. */
const WIDTH = 600;

export type EmailAttachment = {
  filename: string;
  content: string;
  contentType: string;
  /** Referenced from the HTML as `cid:<id>`. */
  cid: string;
};

export type Email = {
  subject: string;
  text: string;
  html: string;
  attachments?: EmailAttachment[];
  /**
   * True for anything the recipient did not individually ask us to send. It
   * puts an unsubscribe line in the footer AND makes `sendMail()` set
   * `List-Unsubscribe`; the two must agree, which is why one flag drives both.
   */
  unsubscribe?: boolean;
};

/* ---------------------------------------------------------------- escaping */

/**
 * Everything interpolated into an HTML part goes through this.
 *
 * It lives here rather than in lib/email.ts because this is the module that
 * builds HTML; lib/email.ts re-exports it so its existing call sites are
 * unchanged. A client's company name is attacker-supplied text as surely as
 * anything on the web is -- somebody typed it into a form.
 */
export function escapeHtml(value: string) {
  return value.replace(/[&<>"']/g, (char) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;",
  })[char]!);
}

/**
 * A URL is only allowed into an `href` if it is one we could have made.
 *
 * `javascript:` in an anchor is mostly a browser problem rather than a mail
 * one, but these builders are also what the admin will preview in a browser,
 * and a rejected link that renders as our own site is a better failure than a
 * link that runs something.
 */
function resolveUrl(value: string) {
  return /^https?:\/\//i.test(value) ? value : SITE_URL;
}

function safeUrl(value: string) {
  return escapeHtml(resolveUrl(value));
}

/* -------------------------------------------------------------- formatting */

/**
 * One day, one spelling, one timezone.
 *
 * Lagos explicitly: a due date rendered from the server's own clock says the
 * 14th to a reader in Lagos and the 13th to the same invoice opened from a US
 * region, and an invoice that disagrees with itself about its due date is an
 * invoice somebody argues about.
 */
export function emailDate(value: Date) {
  return new Intl.DateTimeFormat("en-GB", {
    day: "numeric", month: "long", year: "numeric", timeZone: "Africa/Lagos",
  }).format(value);
}

function emailDateTime(value: Date) {
  return new Intl.DateTimeFormat("en-GB", {
    day: "numeric", month: "long", year: "numeric",
    hour: "2-digit", minute: "2-digit", timeZone: "Africa/Lagos",
  }).format(value);
}

/* ------------------------------------------------------------------ blocks */

/** A paragraph. Its argument is already-escaped markup, not raw user text. */
function p(html: string) {
  return `<p class="wdc-ink" style="margin:0 0 16px;font-family:${BODY};font-size:16px;line-height:1.65;color:${INK}">${html}</p>`;
}

function small(html: string) {
  return `<p class="wdc-muted" style="margin:0 0 16px;font-family:${BODY};font-size:13px;line-height:1.6;color:${MUTED}">${html}</p>`;
}

/**
 * THE ONE NUMBER THAT MATTERS, set apart: the amount due, the amount
 * received, the new stage. The sign-in code's panel, carried into every email
 * that has a figure. `label` sits above it, `note` below.
 */
function figure(value: string, opts: { label?: string; note?: string } = {}) {
  return (
    `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" class="wdc-fig" ` +
    `style="margin:0 0 20px;background:${PAGE};border:1px solid ${HAIRLINE};border-radius:12px"><tr><td align="center" style="padding:18px 20px">` +
    (opts.label ? `<p class="wdc-muted" style="margin:0 0 6px;font-family:${BODY};font-size:12px;letter-spacing:.08em;text-transform:uppercase;font-weight:600;color:${MUTED}">${escapeHtml(opts.label)}</p>` : "") +
    `<p class="wdc-figv" style="margin:0;font-family:${DISPLAY};font-size:32px;line-height:1.2;font-weight:700;letter-spacing:.01em;color:${NAVY}">${escapeHtml(value)}</p>` +
    (opts.note ? `<p class="wdc-muted" style="margin:6px 0 0;font-family:${BODY};font-size:13px;line-height:1.5;color:${MUTED}">${escapeHtml(opts.note)}</p>` : "") +
    `</td></tr></table>`
  );
}

/**
 * The call to action: full width, orange, white label, the site's arrow.
 *
 * A table with a background on the cell rather than a styled anchor, because
 * Outlook ignores padding on an inline element and would render the button as
 * underlined text on a coloured word. The anchor is a block that fills the
 * cell, so the whole bar is the target, and it clears 44px.
 *
 * THE ARROW IS A PICTURE. Gmail strips inline SVG, so it is lucide's
 * arrow-right rendered by scripts/build-email-assets.mjs. With images off it
 * has no alt and simply is not there; the label still says everything.
 */
function action(label: string, href: string) {
  return (
    `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="width:100%;margin:8px 0 24px">` +
    `<tr><td bgcolor="${ACCENT_INK}" align="center" style="background:${ACCENT_INK};border-radius:12px">` +
    `<a href="${safeUrl(href)}" style="display:block;padding:16px 24px;font-family:${BODY};font-size:17px;line-height:22px;` +
    `font-weight:700;color:#ffffff;text-decoration:none;text-align:center;border-radius:12px">${escapeHtml(label)}` +
    `&nbsp;&nbsp;<img src="${ASSETS}/arrow-right-white.png" width="18" height="18" alt="" style="display:inline-block;width:18px;height:18px;border:0;vertical-align:-3px"></a>` +
    `</td></tr></table>`
  );
}

/** A label/value panel: the facts of the message, set apart from the prose. */
function panel(rows: [string, string][]) {
  const cells = rows.map(([label, value], index) => {
    const top = index ? "10px" : "0";
    return (
      `<tr>` +
      `<td class="wdc-muted" style="padding:${top} 0 0;font-family:${BODY};font-size:13px;color:${MUTED};width:42%;vertical-align:top">${escapeHtml(label)}</td>` +
      `<td class="wdc-ink" style="padding:${top} 0 0;font-family:${BODY};font-size:15px;color:${INK};font-weight:600;vertical-align:top">${escapeHtml(value)}</td>` +
      `</tr>`
    );
  }).join("");
  return (
    `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" class="wdc-fig" ` +
    `style="margin:0 0 20px;background:${PAGE};border:1px solid ${HAIRLINE};border-radius:12px">` +
    `<tr><td style="padding:18px 20px">` +
    `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">${cells}</table>` +
    `</td></tr></table>`
  );
}

export type MoneyLine = { description: string; qty: number; unit: number };
export type MoneyTotals = { subtotal: number; vat: number; vatRate: number; total: number };

/**
 * The lines of a quote or an invoice, and their totals.
 *
 * THE TOTALS ARE PASSED IN, NOT COMPUTED HERE. An email that does its own
 * arithmetic is a second opinion about what somebody owes, and the day it
 * disagrees with the invoice screen there is no way to tell which one is
 * right. The caller computes once, with `invoiceTotals()`, and hands the
 * answer over; this only renders it.
 */
function moneyTable(lines: MoneyLine[], totals: MoneyTotals) {
  const th = `padding:0 0 8px;font-family:${BODY};font-size:12px;letter-spacing:.08em;text-transform:uppercase;color:${MUTED};font-weight:600;border-bottom:1px solid ${HAIRLINE}`;
  const head =
    `<tr>` +
    `<th align="left" style="${th}">Item</th>` +
    `<th align="right" style="${th}">Qty</th>` +
    `<th align="right" style="${th}">Amount</th>` +
    `</tr>`;
  const body = lines.map((line) =>
    `<tr>` +
    `<td align="left" style="padding:12px 0;font-family:${BODY};font-size:15px;color:${INK};border-bottom:1px solid ${HAIRLINE}">${escapeHtml(line.description)}</td>` +
    `<td align="right" style="padding:12px 0 12px 12px;font-family:${BODY};font-size:15px;color:${MUTED};border-bottom:1px solid ${HAIRLINE}">${line.qty}</td>` +
    `<td align="right" style="padding:12px 0 12px 12px;font-family:${BODY};font-size:15px;color:${INK};white-space:nowrap;border-bottom:1px solid ${HAIRLINE}">${escapeHtml(naira(line.qty * line.unit))}</td>` +
    `</tr>`).join("");
  const subtotals: [string, string][] = [["Subtotal", naira(totals.subtotal)]];
  if (totals.vatRate) subtotals.push([`VAT (${totals.vatRate}%)`, naira(totals.vat)]);
  const foot = subtotals.map(([label, value]) =>
    `<tr><td colspan="2" align="right" style="padding:10px 0 0;font-family:${BODY};font-size:14px;color:${MUTED}">${escapeHtml(label)}</td>` +
    `<td align="right" style="padding:10px 0 0 12px;font-family:${BODY};font-size:14px;color:${INK};white-space:nowrap">${escapeHtml(value)}</td></tr>`).join("");
  const grand =
    `<tr><td colspan="2" align="right" style="padding:12px 0 0;font-family:${DISPLAY};font-size:16px;font-weight:700;color:${INK}">Total</td>` +
    `<td align="right" style="padding:12px 0 0 12px;font-family:${DISPLAY};font-size:18px;font-weight:700;color:${NAVY};white-space:nowrap">${escapeHtml(naira(totals.total))}</td></tr>`;
  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 22px">${head}${body}${foot}${grand}</table>`;
}

/** The same lines, for the text part. */
function moneyLinesText(lines: MoneyLine[], totals: MoneyTotals) {
  const rows = lines.map((line) => `  - ${line.description} (x${line.qty}): ${naira(line.qty * line.unit)}`);
  const tail = [`  Subtotal: ${naira(totals.subtotal)}`];
  if (totals.vatRate) tail.push(`  VAT (${totals.vatRate}%): ${naira(totals.vat)}`);
  tail.push(`  Total: ${naira(totals.total)}`);
  return [...rows, "", ...tail].join("\n");
}

const QR_CID = "wdc-document-qr";

/**
 * The document's QR code, as an attached SVG.
 *
 * IT REUSES `qrSvg()` rather than encoding a second time, so an invoice's code
 * is made by the same encoder, with the same measured module and error
 * correction decisions, as the ones on the site.
 *
 * THE MARK IS DELIBERATELY NOT PUNCHED INTO THIS ONE. `qrSvg` places it as an
 * `<image href>` pointing at a file on our site, and every mail client that
 * blocks remote images -- which is most of them, by default -- would render
 * the code with a hole in the middle and nothing in the hole. A code with a
 * hole in it is a damaged code, so this one keeps its modules and drops the
 * decoration.
 *
 * BE HONEST ABOUT WHAT RENDERS. Apple Mail draws SVG; Gmail and Outlook do
 * not. That is exactly why the URL sits beside it as ordinary text: the code
 * is a convenience for somebody holding a printed copy, never the only way to
 * reach the document. If delivery evidence ever shows people need the image
 * itself, the upgrade is a PNG out of the `qrcode` dependency we already have,
 * not a new package.
 */
async function documentQr(requested: string) {
  /* Resolved before it is encoded, so the code and the link beside it always
     point at the same, allowed, address. */
  const url = resolveUrl(requested);
  const svg = await qrSvg(url, { dark: NAVY, light: CARD, margin: 2, level: "M" });
  const html =
    `<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:4px 0 18px">` +
    `<tr><td style="padding:12px;background:${CARD};border:1px solid ${HAIRLINE};border-radius:12px">` +
    `<img src="cid:${QR_CID}" width="132" height="132" alt="QR code linking to this document" style="display:block;width:132px;height:132px">` +
    `</td>` +
    `<td style="padding-left:16px;vertical-align:middle">` +
    `<p style="margin:0;font-family:${BODY};font-size:13px;line-height:1.6;color:${MUTED}">Scan to open this document on your phone.</p>` +
    `</td></tr></table>`;
  const attachment: EmailAttachment = {
    filename: "document-qr.svg",
    content: svg,
    contentType: "image/svg+xml",
    cid: QR_CID,
  };
  return { html, attachment };
}

/* ------------------------------------------------------------------- shell */

const LEGAL_LINE =
  `${COMPANY_NAME}. ${REGISTERED_NAME}, ${REGISTRATION_NO}, registered with the ${REGISTRAR}.`;

/**
 * The unsubscribe target.
 *
 * A `mailto:` and not a URL, for the same reason lib/email.ts sets the
 * `List-Unsubscribe` header to one: there is no unsubscribe endpoint yet, and
 * a link to a page that does not exist is worse than an address a person can
 * read. Both change together the day the endpoint ships.
 */
const UNSUBSCRIBE_MAILTO = `mailto:${CONTACT_EMAIL}?subject=unsubscribe`;

/**
 * Where the footer names the person it was sent to. The template does not
 * know the address; `sendMail()` does, and swaps it in with `addressTo()`.
 * Anything that renders a template without sending it reads "you".
 */
const RECIPIENT_SLOT = `<span data-wdc-recipient>you</span>`;

/** Fills the footer's "sent to" line with the address the message is going to. */
export function addressTo(html: string, to: string) {
  return html.replace(RECIPIENT_SLOT, `<span style="color:${INK}">${escapeHtml(to)}</span>`);
}

/**
 * WHERE THE FOOTER'S ROW OF MARKS GOES. The profiles are settings (Settings >
 * Business profile, lib/social.ts), and a template is built before anything
 * has necessarily read them, so the frame leaves this slot and `sendMail`
 * fills it once it has (the same move as the recipient line above). An
 * unfilled slot is a comment, so a preview shows no row rather than a broken one.
 */
const SOCIAL_SLOT = "<!--wdc-social-->";
function socialRow() {
  return SOCIAL_SLOT;
}

/** One mark per profile, none while there are none. */
export function withSocials(html: string, links: { network: string; label: string; url: string }[]) {
  if (!html.includes(SOCIAL_SLOT)) return html;
  if (!links.length) return html.replace(SOCIAL_SLOT, "");
  const cells = links.map(
    (link, index) =>
      `<td style="padding:0 ${index === links.length - 1 ? 0 : 20}px 0 0">` +
      `<a href="${safeUrl(link.url)}" style="text-decoration:none"><img src="${ASSETS}/social-${link.network}.png" width="22" height="22" alt="${escapeHtml(link.label)}" style="display:block;width:22px;height:22px;border:0"></a></td>`,
  ).join("");
  return html.replace(SOCIAL_SLOT, `<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 20px"><tr>${cells}</tr></table>`);
}

/**
 * The frame every message in this file shares.
 *
 * `preheader` is the line the inbox shows after the subject. Left unset, a
 * client picks the first words it finds, which on a message that opens with a
 * greeting is "Hi Ada," -- a wasted second line in every inbox. The run of
 * zero-width spaces after it is the standard trick that stops Gmail appending
 * the body text to it.
 *
 * LIGHT BY DEFAULT, WITH ITS OWN DARK STEPS for the clients that ask (the
 * `prefers-color-scheme` block below), and safe when one darkens it without
 * asking: the Gmail and Outlook apps darken light mail whatever it says. So nothing here depends on the card staying white: the
 * header logo is white on a navy cell, which those apps leave dark; the
 * social marks are mid-grey, which reads on white and on near-black alike;
 * and every colour of type is left for the client to invert.
 *
 * THE FOOTER'S NAVY LOGO IS THE ONE WEAK SPOT. Navy on a darkened card is
 * hard to see. Outlook marks its dark mode with `[data-ogsc]`, so there the
 * white lockup is swapped in; the Gmail apps darken without saying so, and
 * nothing in an email can respond to that.
 */
function shell(input: {
  title: string;
  preheader: string;
  heading: string;
  blocks: string[];
  unsubscribe?: boolean;
  /** One sentence on why this arrived, and where to switch it off (the design's footer rule). */
  why?: string;
  manage?: "client" | "staff";
}) {
  const year = new Date().getFullYear();
  const manageUrl = input.manage === "client" ? `${SITE_URL}/portal/settings` : input.manage === "staff" ? `${SITE_URL}/admin/settings/notifications` : "";
  const why = input.why
    ? `<p class="wdc-muted" style="margin:0 0 16px;font-family:${BODY};font-size:13px;line-height:1.6;color:${MUTED}">${escapeHtml(input.why)}` +
      (manageUrl ? ` <a class="wdc-link" href="${manageUrl}" style="color:${ACCENT_INK};text-decoration:underline">Manage what we email you</a>.` : "") + `</p>`
    : "";
  const unsubscribe = input.unsubscribe
    ? ` <a href="${UNSUBSCRIBE_MAILTO}" style="color:${MUTED};text-decoration:underline">Unsubscribe</a>.`
    : "";

  return `<!doctype html>
<html lang="en" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="x-apple-disable-message-reformatting">
<meta name="color-scheme" content="light dark">
<meta name="supported-color-schemes" content="light dark">
<title>${escapeHtml(input.title)}</title>
<!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml><![endif]-->
<style>
  /* The one rule that needs a stylesheet: a 600px table has to become a
     full-width one on a phone, and no inline style can express a breakpoint.
     Everything else is inline, so a client that drops this block loses
     nothing but the narrow layout. */
  @media only screen and (max-width:620px){
    .wdc-wrap{width:100% !important}
    .wdc-pad{padding-left:22px !important;padding-right:22px !important}
  }
  /* DARK MODE, for the clients that ask (Apple Mail, iOS Mail): the email
     design's own dark steps, not an automatic inversion. The navy header
     stays navy; the card, the type, the figure panels and the footer logo
     swap. Clients that darken without asking (Gmail's apps) ignore this and
     nothing important depends on them. */
  @media (prefers-color-scheme: dark){
    .wdc-page{background:#0a0a1a !important}
    .wdc-card{background:#15152b !important;border-color:#2c2c48 !important}
    .wdc-ink{color:#f1f1f7 !important}
    .wdc-muted{color:#a9a9c2 !important}
    .wdc-fig{background:#0d0d22 !important;border-color:#2c2c48 !important}
    .wdc-figv{color:#ffffff !important}
    .wdc-hair{border-color:#2c2c48 !important}
    .wdc-link{color:#ff8a3d !important}
    .wdc-logo-light{display:none !important}
    .wdc-logo-dark{display:block !important}
  }
  /* Outlook's dark mode: the navy footer logo would vanish, so show the white one. */
  [data-ogsc] .wdc-logo-light{display:none !important}
  [data-ogsc] .wdc-logo-dark{display:block !important}
</style>
</head>
<body class="wdc-page" style="margin:0;padding:0;background:${PAGE};-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%">
<div style="display:none;max-height:0;overflow:hidden;opacity:0;mso-hide:all">${escapeHtml(input.preheader)}&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" class="wdc-page" style="background:${PAGE}">
<tr><td align="center" style="padding:28px 12px">
<table role="presentation" class="wdc-wrap wdc-card" width="${WIDTH}" cellpadding="0" cellspacing="0" border="0" style="width:${WIDTH}px;max-width:${WIDTH}px;background:${CARD};border:1px solid ${HAIRLINE};border-radius:16px">

<tr><td bgcolor="${NAVY}" class="wdc-pad" style="padding:24px 32px;background:${NAVY};border-radius:16px 16px 0 0">
  <a href="${SITE_URL}" style="text-decoration:none"><img src="${ASSETS}/logo-white.png" width="152" height="50" alt="We Dig Creativity" style="display:block;width:152px;height:50px;border:0;color:#ffffff;font-family:${DISPLAY};font-size:18px;font-weight:700"></a>
</td></tr>

<tr><td class="wdc-pad" style="padding:32px 32px 8px">
  <h1 class="wdc-ink" style="margin:0 0 18px;font-family:${DISPLAY};font-size:26px;line-height:1.25;font-weight:700;color:${INK}">${escapeHtml(input.heading)}</h1>
  ${input.blocks.join("\n  ")}
</td></tr>

<tr><td class="wdc-pad" style="padding:8px 32px 32px">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td class="wdc-hair" style="border-top:1px solid ${HAIRLINE};padding-top:28px">
    <a href="${SITE_URL}" style="text-decoration:none"><img src="${ASSETS}/logo-navy.png" width="122" height="40" alt="We Dig Creativity" class="wdc-logo-light" style="display:block;width:122px;height:40px;border:0;margin:0 0 20px;color:${NAVY};font-family:${DISPLAY};font-size:16px;font-weight:700"></a>
    <!--[if !mso]><!--><a href="${SITE_URL}" style="text-decoration:none"><img src="${ASSETS}/logo-white.png" width="122" height="40" alt="" class="wdc-logo-dark" style="display:none;width:122px;height:40px;border:0;margin:0 0 20px"></a><!--<![endif]-->
    ${socialRow()}
    ${why}
    <p class="wdc-muted" style="margin:0 0 4px;font-family:${BODY};font-size:13px;line-height:1.6;color:${MUTED}">&copy; ${year} ${escapeHtml(COMPANY_NAME)}</p>
    <p class="wdc-muted" style="margin:0 0 16px;font-family:${BODY};font-size:13px;line-height:1.6;color:${MUTED}">${escapeHtml(LOCATION)}</p>
    <p class="wdc-muted" style="margin:0 0 16px;font-family:${BODY};font-size:13px;line-height:1.6;color:${MUTED}">This email was sent to ${RECIPIENT_SLOT}.${unsubscribe}</p>
    <p class="wdc-muted" style="margin:0;font-family:${BODY};font-size:12px;line-height:1.6;color:${MUTED}">${escapeHtml(REGISTERED_NAME)}, ${escapeHtml(REGISTRATION_NO)}, registered with the ${escapeHtml(REGISTRAR)}.</p>
  </td></tr></table>
</td></tr>

</table>
</td></tr>
</table>
</body>
</html>`;
}

/**
 * The signature and legal tail of the text part.
 *
 * The plain text carries the same footer the HTML does, because for a reader
 * on a text-only client it IS the message -- and an unsubscribe offered only
 * to people whose client renders HTML is not an unsubscribe.
 */
function textShell(body: string, options: { unsubscribe?: boolean } = {}) {
  const tail = [
    "",
    "--",
    "We Dig Creativity",
    SITE_URL.replace(/^https?:\/\//, ""),
    CONTACT_EMAIL,
    LOCATION,
    "",
    LEGAL_LINE,
  ];
  if (options.unsubscribe) {
    tail.push(
      "",
      "You are receiving this because you contacted We Dig Creativity or are",
      `working with us on a project. To stop these messages, reply to ${CONTACT_EMAIL}`,
      "with the word unsubscribe.",
    );
  }
  return `${body.trim()}\n${tail.join("\n")}\n`;
}

/* ================================================================ 1. enquiry */

export function enquiryReceiptEmail(input: { firstName: string; topic: string }): Email {
  const { firstName, topic } = input;
  return {
    subject: "We received your message: We Dig Creativity",
    /* The enquirer asked us a question; they did not ask for this copy. That
       is the whole test for `unsubscribe`, and this is the clearest case. */
    unsubscribe: true,
    text: textShell(`Hi ${firstName},

Your message about ${topic} reached us, and somebody on the team will read it
properly rather than reply automatically. You can expect an answer within the
same working day.

If anything has changed since you wrote, or you left something out, reply to
this email and it lands on the same thread.

Thank you for getting in touch.

The WDC team`, { unsubscribe: true }),
    html: shell({
      title: "We received your message",
      preheader: `Your message about ${topic} is with us. We reply the same working day.`,
      heading: "Your message is with us.",
      why: "You get this because you sent us a message on the site.",
      unsubscribe: true,
      blocks: [
        p(`Hi ${escapeHtml(firstName)},`),
        p(`Your message about <b>${escapeHtml(topic)}</b> reached us, and somebody on the team will read it properly rather than reply automatically. You can expect an answer within the same working day.`),
        p("If anything has changed since you wrote, or you left something out, reply to this email and it lands on the same thread."),
        small("A copy was sent automatically so you know the form worked."),
      ],
    }),
  };
}

/* ===================================================== 2. onboarding invite */

export function onboardingInvitationEmail(input: {
  name: string;
  service: string;
  url: string;
  /** How long the link lives, in days. Stated because it is true, not to rush. */
  expiresInDays: number;
}): Email {
  const { name, service, url, expiresInDays } = input;
  return {
    subject: `Start your ${service} project with WDC`,
    text: textShell(`Hi ${name},

Welcome aboard. Before we start on your ${service} project we need the brief in
your own words: what the work has to achieve, who it is for, and what already
exists that we should build on.

The form is here, and you can leave it and come back to it on any device:

${url}

It takes about ten minutes if you have the details to hand, and rather less if
you answer "I'm not sure, please advise me" wherever you would rather we took
the decision. That is a real answer, and you can change it later.

The link works for ${expiresInDays} days. If it expires, reply to this email
and we will send a fresh one.

The WDC team`),
    html: shell({
      title: "Start your project",
      preheader: `Your ${service} onboarding form is ready. It takes about ten minutes.`,
      heading: "Welcome aboard. Tell us about the work.",
      blocks: [
        p(`Hi ${escapeHtml(name)},`),
        p(`Before we start on your <b>${escapeHtml(service)}</b> project we need the brief in your own words: what the work has to achieve, who it is for, and what already exists that we should build on.`),
        action("Open the onboarding form", url),
        p(`It takes about ten minutes if you have the details to hand, and rather less if you answer <i>&ldquo;I'm not sure, please advise me&rdquo;</i> wherever you would rather we took the decision. That is a real answer, and you can change it later.`),
        small(`You can leave the form and come back to it on any device. The link works for ${expiresInDays} days &mdash; if it expires, reply to this email and we will send a fresh one.`),
      ],
    }),
  };
}

/* =================================================== 3. onboarding reminder */

export function onboardingReminderEmail(input: {
  name: string;
  service: string;
  url: string;
  /** Whole percent, from answered questions over total. Never invented. */
  progressPercent: number;
  daysLeft: number;
}): Email {
  const { name, service, url, progressPercent, daysLeft } = input;
  const where = progressPercent > 0
    ? `You are about ${progressPercent}% of the way through, and everything you typed is saved.`
    : "Nothing is filled in yet, so it is a clean start whenever you have ten minutes.";
  const deadline = daysLeft === 1 ? "tomorrow" : `in ${daysLeft} days`;
  return {
    subject: `Your ${service} brief is still open`,
    /* A reminder is the definition of mail the recipient did not ask for
       today, whatever they agreed to last week. */
    unsubscribe: true,
    text: textShell(`Hi ${name},

Your onboarding form for the ${service} project is still open. ${where}

Pick up where you left off:

${url}

This link expires ${deadline}. There is no rush from our side beyond that -- we
simply cannot schedule the work until we know what it is.

If the project is on hold, or is not going ahead after all, reply and say so
and we will stop reminding you.

The WDC team`, { unsubscribe: true }),
    html: shell({
      title: "Your brief is still open",
      preheader: `${where} The link expires ${deadline}.`,
      heading: "Your brief is still open.",
      unsubscribe: true,
      blocks: [
        p(`Hi ${escapeHtml(name)},`),
        p(`Your onboarding form for the <b>${escapeHtml(service)}</b> project is still open. ${escapeHtml(where)}`),
        action("Pick up where you left off", url),
        p(`This link expires ${escapeHtml(deadline)}. There is no rush from our side beyond that &mdash; we simply cannot schedule the work until we know what it is.`),
        small("If the project is on hold, or is not going ahead after all, reply and say so and we will stop reminding you."),
      ],
    }),
  };
}

/* ================================================ 3b. onboarding next steps */

/**
 * "We have your brief. Here is what happens now."
 *
 * Sent once, after the form is submitted. It names every channel the project
 * might run on, because a client who has only ever seen an email from us will
 * otherwise be surprised by a WhatsApp group, and one who prefers WhatsApp
 * should know they can say so.
 *
 * THE ACCOUNT IS OPTIONAL, AND SAID SO. Nothing about the work needs one. The
 * invitation is offered, not sent: it is bound to this address when a person
 * issues it, which is what stops a forwarded email registering somebody else.
 */
export function onboardingNextStepsEmail(input: { name: string; service: string; company?: string }): Email {
  const { name, service, company } = input;
  const forWhom = company ? ` for ${company}` : "";
  return {
    subject: `Thank you, ${name}: your ${service} brief is with us`,
    /* They asked for the work, not for this message, which is the test the
       enquiry receipt uses too. */
    unsubscribe: true,
    text: textShell(`Hi ${name},

Thank you for completing the onboarding form for your ${service} project${forWhom}.
Your answers are saved and the brief is with the team.

What happens next:

1. Somebody on the team reads your brief properly. Anything you marked "I'm not
   sure, please advise me" is ours to recommend, and we will explain why.
2. We come back to you with any questions, then the proposed scope and price.
3. Once you are happy with both, we agree a start date and begin.

How we will stay in touch: project communication may happen through the client
dashboard, direct chat by email, a WhatsApp project group where that suits the
work, or another channel we agree with you. Reply and tell us what you prefer.

You do not need an account to work with us. If you would like to follow the
project in the client dashboard, reply and ask, and we will send a personal
invitation tied to this email address.

The WDC team`, { unsubscribe: true }),
    html: shell({
      title: "Your brief is with us",
      preheader: `Your ${service} brief is saved. Here is what happens next.`,
      heading: "Thank you. Your brief is with us.",
      why: "You get this because you sent us a brief on the site.",
      unsubscribe: true,
      blocks: [
        p(`Hi ${escapeHtml(name)},`),
        p(`Thank you for completing the onboarding form for your <b>${escapeHtml(service)}</b> project${escapeHtml(forWhom)}. Your answers are saved and the brief is with the team.`),
        panel([
          ["First", "We read your brief properly, and recommend on anything you asked us to advise on."],
          ["Then", "We come back with any questions, then the proposed scope and price."],
          ["After that", "Once you are happy with both, we agree a start date and begin."],
        ]),
        p("Project communication may happen through the client dashboard, direct chat by email, a WhatsApp project group where that suits the work, or another channel we agree with you. Reply and tell us what you prefer."),
        small("You do not need an account to work with us. If you would like to follow the project in the client dashboard, reply and ask, and we will send a personal invitation tied to this email address."),
      ],
    }),
  };
}

/* ================================================================== 4. quote */

export function quoteEmail(input: {
  clientName: string;
  quoteNumber: string;
  projectTitle: string;
  lines: MoneyLine[];
  totals: MoneyTotals;
  validUntil: Date;
  url: string;
}): Email {
  const { clientName, quoteNumber, projectTitle, lines, totals, validUntil, url } = input;
  return {
    subject: `Quote ${quoteNumber} - ${projectTitle}`,
    text: textShell(`Hi ${clientName},

Here is our quote for ${projectTitle}, reference ${quoteNumber}.

${moneyLinesText(lines, totals)}

This quote holds until ${emailDate(validUntil)}. It covers the work described
above and nothing else; anything added later is quoted separately before it
starts, so there are no surprises on the invoice.

Read it in full and accept it here:

${url}

If something in the scope is wrong, or you want a line taken out, say so and we
will re-issue rather than argue about it later.

The WDC team`),
    html: shell({
      title: `Quote ${quoteNumber}`,
      preheader: `${projectTitle}, ${naira(totals.total)}, valid until ${emailDate(validUntil)}.`,
      heading: projectTitle,
      blocks: [
        p(`Hi ${escapeHtml(clientName)},`),
        p("Here is our quote for the work as we understand it."),
        moneyTable(lines, totals),
        panel([
          ["Quote reference", quoteNumber],
          ["Valid until", emailDate(validUntil)],
        ]),
        action("Read and accept the quote", url),
        p("This quote covers the work described above and nothing else. Anything added later is quoted separately before it starts, so there are no surprises on the invoice."),
        small("If something in the scope is wrong, or you want a line taken out, say so and we will re-issue rather than argue about it later."),
      ],
    }),
  };
}

/* ================================================================ 5. invoice */

export async function invoiceEmail(input: {
  clientName: string;
  number: string;
  projectTitle: string;
  lines: MoneyLine[];
  totals: MoneyTotals;
  /** Kobo already received against this invoice. Zero on a first issue. */
  paid: number;
  issued: Date;
  due: Date;
  url: string;
}): Promise<Email> {
  const { clientName, number, projectTitle, lines, totals, paid, issued, due, url } = input;
  const outstanding = Math.max(0, totals.total - paid);
  const partPaid = paid > 0 && outstanding > 0;
  const qr = await documentQr(url);

  const rows: [string, string][] = [
    ["Invoice number", number],
    ["Issued", emailDate(issued)],
    ["Due", emailDate(due)],
  ];
  if (paid > 0) rows.push(["Already paid", naira(paid)]);
  rows.push([partPaid ? "Balance outstanding" : "Amount due", naira(outstanding)]);

  const paidLine = paid > 0 ? `  Already paid: ${naira(paid)}\n` : "";
  const dueLabel = partPaid ? "Balance outstanding" : "Amount due";

  return {
    subject: `Invoice ${number} - ${naira(outstanding)} due ${emailDate(due)}`,
    attachments: [qr.attachment],
    text: textShell(`Hi ${clientName},

This is invoice ${number} for ${projectTitle}.

${moneyLinesText(lines, totals)}
${paidLine}  ${dueLabel}: ${naira(outstanding)}

Issued ${emailDate(issued)}, due ${emailDate(due)}.

You can read the invoice and pay it here:

${url}

Card and bank transfer both work through that link. If you would rather send a
direct transfer, or pay by cash or POS, tell us which and we will record it
against this invoice so your statement stays straight.

The WDC team`),
    html: shell({
      title: `Invoice ${number}`,
      preheader: `${naira(outstanding)} due ${emailDate(due)} for ${projectTitle}.`,
      heading: partPaid ? "Balance outstanding on your invoice" : "Your invoice is ready",
      blocks: [
        p(`Hi ${escapeHtml(clientName)},`),
        p(`This is invoice <b>${escapeHtml(number)}</b> for ${escapeHtml(projectTitle)}.`),
        moneyTable(lines, totals),
        panel(rows),
        action("Read and pay the invoice", url),
        qr.html,
        p("Card and bank transfer both work through that link. If you would rather send a direct transfer, or pay by cash or POS, tell us which and we will record it against this invoice so your statement stays straight."),
      ],
    }),
  };
}

/* ================================================================ 6. receipt */

export async function receiptEmail(input: {
  clientName: string;
  receiptNumber: string;
  invoiceNumber: string;
  amount: number;
  method: string;
  reference: string;
  paidAt: Date;
  /** Kobo still owed on the invoice after this payment. */
  balance: number;
  url: string;
}): Promise<Email> {
  const { clientName, receiptNumber, invoiceNumber, amount, method, reference, paidAt, balance, url } = input;
  const qr = await documentQr(url);
  const settled = balance <= 0;
  const balanceLine = settled
    ? "Balance: nothing further is owed on this invoice."
    : `Balance still outstanding: ${naira(balance)}`;

  return {
    subject: `Receipt ${receiptNumber} - ${naira(amount)} received`,
    attachments: [qr.attachment],
    text: textShell(`Hi ${clientName},

We have received ${naira(amount)} against invoice ${invoiceNumber}. Thank you.

  Receipt number: ${receiptNumber}
  Invoice: ${invoiceNumber}
  Amount received: ${naira(amount)}
  Method: ${method}
  Reference: ${reference}
  Received: ${emailDateTime(paidAt)}
  ${balanceLine}

Your copy of the receipt is here:

${url}

Keep it for your records. If any detail above does not match what you sent,
reply to this email and we will look at it the same day.

The WDC team`),
    html: shell({
      title: `Receipt ${receiptNumber}`,
      preheader: `${naira(amount)} received against invoice ${invoiceNumber}.`,
      heading: `${naira(amount)} received. Thank you.`,
      blocks: [
        p(`Hi ${escapeHtml(clientName)},`),
        p(`This confirms a payment against invoice <b>${escapeHtml(invoiceNumber)}</b>.`),
        panel([
          ["Receipt number", receiptNumber],
          ["Invoice", invoiceNumber],
          ["Amount received", naira(amount)],
          ["Method", method],
          ["Reference", reference],
          ["Received", emailDateTime(paidAt)],
          ["Balance", settled ? "Nothing further owed" : naira(balance)],
        ]),
        action("Open your receipt", url),
        qr.html,
        small("Keep it for your records. If any detail above does not match what you sent, reply to this email and we will look at it the same day."),
      ],
    }),
  };
}

/* ========================================================== 7. project stage */

export function projectStageEmail(input: {
  clientName: string;
  projectTitle: string;
  fromStage: string;
  toStage: string;
  /** What actually changed, in the studio's words. Optional, never invented. */
  note?: string;
  url: string;
}): Email {
  const { clientName, projectTitle, fromStage, toStage, note, url } = input;
  return {
    subject: `${projectTitle} is now at ${toStage}`,
    /* A progress notice is useful mail, and it is still mail nobody asked for
       on the day it arrives. */
    unsubscribe: true,
    text: textShell(`Hi ${clientName},

${projectTitle} has moved from ${fromStage} to ${toStage}.
${note ? `\n${note}\n` : ""}
You can see where the project stands, and everything that has happened on it so
far, here:

${url}

Nothing is needed from you unless we have asked for it separately.

The WDC team`, { unsubscribe: true }),
    html: shell({
      title: `${projectTitle} - ${toStage}`,
      preheader: `Moved from ${fromStage} to ${toStage}.`,
      heading: `${projectTitle} is now at ${toStage}.`,
      why: "You get project updates while we work on your project.",
      manage: "client",
      unsubscribe: true,
      blocks: [
        p(`Hi ${escapeHtml(clientName)},`),
        panel([["Was", fromStage], ["Now", toStage]]),
        ...(note ? [p(escapeHtml(note))] : []),
        action("See the project", url),
        small("Nothing is needed from you unless we have asked for it separately."),
      ],
    }),
  };
}

/* ===================================================== 8. deliverable ready */

/** The studio answered a question the client raised in the portal. */
export function supportReplyEmail(input: { clientName: string; subject: string; reply: string; author: string; url: string }): Email {
  const { clientName, subject, reply, author, url } = input;
  return {
    subject: `Re: ${subject}`,
    /* An answer to their own question, and still switchable with the rest of
       the project messages. */
    unsubscribe: true,
    text: textShell(`Hi ${clientName},

${author} replied to "${subject}":

${reply}

Read the conversation or answer it here:

${url}

The WDC team`, { unsubscribe: true }),
    html: shell({
      title: `Re: ${subject}`,
      preheader: reply.slice(0, 120),
      heading: "We replied to your question.",
      why: "You get this because you asked us a question in your portal.",
      manage: "client",
      unsubscribe: true,
      blocks: [
        p(`Hi ${escapeHtml(clientName)},`),
        panel([["About", subject], ["From", author]]),
        p(escapeHtml(reply).replace(/\n/g, "<br>")),
        action("Read and reply", url),
      ],
    }),
  };
}

/** For the studio: a client opened a question, or answered one. */
export function supportNoticeEmail(input: { company: string; subject: string; body: string; opened: boolean; url: string }): Email {
  const { company, subject, body, opened, url } = input;
  const heading = opened ? `${company} asked a question.` : `${company} replied.`;
  return {
    subject: `${opened ? "New question" : "Reply"} from ${company}: ${subject}`,
    text: textShell(`${heading}

${subject}

${body}

Answer it in the admin:

${url}`),
    html: shell({
      title: subject,
      preheader: body.slice(0, 120),
      heading,
      blocks: [
        panel([["Client", company], ["About", subject]]),
        p(escapeHtml(body).replace(/\n/g, "<br>")),
        action("Answer it", url),
      ],
      why: "You get this because support notices are on.",
      manage: "staff",
    }),
  };
}

export function paymentNoticeEmail(input: { company: string; amount: string; invoice: string; left: string; method: string; url: string }): Email {
  const { company, amount, invoice, left, method, url } = input;
  const heading = `${company} paid ${amount}.`;
  return {
    subject: `Payment received: ${amount} from ${company}`,
    text: textShell(`${heading}

Invoice ${invoice}, by ${method}. ${left}

In the admin:

${url}`),
    html: shell({
      title: `Payment received from ${company}`,
      preheader: `${amount} against ${invoice}. ${left}`,
      heading,
      blocks: [
        figure(amount, { label: "Received" }),
        panel([["Client", company], ["Invoice", invoice], ["Paid by", method], ["Still owed", left]]),
        action("Open the invoice", url),
      ],
      why: "You get this because payment notices are on.",
      manage: "staff",
    }),
  };
}

export function deliverableReadyEmail(input: {
  clientName: string;
  projectTitle: string;
  deliverable: string;
  url: string;
  /** When we need the answer, so the schedule cannot slip silently. */
  respondBy: Date;
}): Email {
  const { clientName, projectTitle, deliverable, url, respondBy } = input;
  return {
    subject: `${deliverable} is ready for your approval`,
    text: textShell(`Hi ${clientName},

${deliverable} for ${projectTitle} is ready for you to look at.

Open it here, leave any comments directly on it, and either approve it or send
it back with changes:

${url}

We have held ${emailDate(respondBy)} in the schedule for your answer. If it
comes later than that, the stages after it move by the same amount -- which is
the only reason we mention a date at all.

The WDC team`),
    html: shell({
      title: `${deliverable} is ready`,
      preheader: `${deliverable} for ${projectTitle} is ready for your approval.`,
      heading: `${deliverable} is ready for you.`,
      why: "You get this when something is ready for you to review.",
      manage: "client",
      blocks: [
        p(`Hi ${escapeHtml(clientName)},`),
        p(`${escapeHtml(deliverable)} for <b>${escapeHtml(projectTitle)}</b> is ready. Open it, leave any comments directly on it, and either approve it or send it back with changes.`),
        action("Review and approve", url),
        panel([["Project", projectTitle], ["We have held", emailDate(respondBy)]]),
        p(`If your answer comes after ${escapeHtml(emailDate(respondBy))}, the stages after it move by the same amount &mdash; which is the only reason we mention a date at all.`),
      ],
    }),
  };
}

/* =============================================================== 9. sign-off */

export function signOffEmail(input: {
  clientName: string;
  projectTitle: string;
  deliverable: string;
  signedBy: string;
  signedAt: Date;
  url: string;
}): Email {
  const { clientName, projectTitle, deliverable, signedBy, signedAt, url } = input;
  return {
    subject: `Signed off: ${deliverable}`,
    text: textShell(`Hi ${clientName},

${deliverable} on ${projectTitle} is signed off. This is your record of it.

  Signed off by: ${signedBy}
  Date: ${emailDateTime(signedAt)}
  Project: ${projectTitle}

The signed record is kept with the project, and you can open it at any time:

${url}

Work on the next stage starts from here. If anything about this approval looks
wrong, tell us before we build on it rather than after.

The WDC team`),
    html: shell({
      title: `Signed off: ${deliverable}`,
      preheader: `${deliverable} was signed off by ${signedBy}.`,
      heading: `${deliverable} is signed off.`,
      why: "You get a copy of every sign-off, for your records.",
      blocks: [
        p(`Hi ${escapeHtml(clientName)},`),
        p("This is your record of the approval."),
        panel([
          ["Signed off by", signedBy],
          ["Date", emailDateTime(signedAt)],
          ["Project", projectTitle],
        ]),
        action("Open the signed record", url),
        p("Work on the next stage starts from here. If anything about this approval looks wrong, tell us before we build on it rather than after."),
      ],
    }),
  };
}

/* ======================================================== 10. password reset */

export function passwordResetEmail(input: {
  /** First name where we have one; the address is a poor substitute but true. */
  name?: string;
  url: string;
  expiresInMinutes: number;
}): Email {
  const { name, url, expiresInMinutes } = input;
  const greeting = name ? `Hi ${name},` : "Hello,";
  const life = expiresInMinutes === 60 ? "one hour" : `${expiresInMinutes} minutes`;
  return {
    subject: "Reset your We Dig Creativity password",
    /* NO unsubscribe on this one, and that is deliberate. A password reset is
       a message the recipient asked for seconds ago, and offering to
       unsubscribe from account security is how somebody loses access to their
       own account. `List-Unsubscribe` is for bulk mail; this is not bulk. */
    text: textShell(`${greeting}

Somebody asked to reset the password on your We Dig Creativity account. If that
was you, open this link within ${life} and choose a new one:

${url}

The link works once, and then stops working.

If it was not you, nothing has happened and there is nothing you need to do.
Your current password still works and nobody has been let in. If these keep
arriving, reply and tell us -- that is worth knowing.

The WDC team`),
    html: shell({
      title: "Reset your password",
      preheader: `Choose a new password. The link works once and expires in ${life}.`,
      heading: "Reset your password",
      why: "Security emails always arrive.",
      blocks: [
        p(escapeHtml(greeting)),
        p("Somebody asked to reset the password on your We Dig Creativity account. If that was you, choose a new one now."),
        action("Choose a new password", url),
        p(`The link works once, and expires in ${escapeHtml(life)}.`),
        small("If it was not you, nothing has happened and there is nothing you need to do &mdash; your current password still works and nobody has been let in. If these keep arriving, reply and tell us."),
      ],
    }),
  };
}

/**
 * The sign-in link AND the six-digit code, in one message.
 *
 * TWO WAYS IN, ONE EMAIL, because they answer two different situations. The
 * link is for somebody reading their mail on the device they want to be signed
 * in on. The code is for everybody else: mail on the phone, login on the
 * laptop. A session cookie belongs to the browser that opened the link, so the
 * link alone would sign in the phone and leave the laptop waiting for ever.
 * Using either one spends both -- see `hooks.after` in lib/auth.ts.
 *
 * The code is set in the display face at a size that survives a glance from
 * across a desk, and spaced so a reader copying it does not lose their place.
 */
export function signInEmail(input: {
  name?: string;
  url: string;
  code: string;
  expiresInMinutes: number;
}): Email {
  const { name, url, code, expiresInMinutes } = input;
  const greeting = name ? `Hi ${name},` : "Hello,";
  const life = `${expiresInMinutes} minutes`;
  const spaced = `${code.slice(0, 3)} ${code.slice(3)}`;
  return {
    subject: `${spaced} is your We Dig Creativity sign-in code`,
    /* No unsubscribe, for the reason the reset email gives: somebody asked for
       this seconds ago, and it is account access, not bulk mail. */
    text: textShell(`${greeting}

Here is your sign-in link for We Dig Creativity. It works for ${life}:

${url}

Signing in on a different device? Enter this code on the login page instead:

${spaced}

The link and the code work once. Using either one cancels the other.

If you did not ask to sign in, you can ignore this email. Nobody can get in
without it.

The WDC team`),
    html: shell({
      title: "Your sign-in link",
      preheader: `Your code is ${spaced}. It works for ${life}.`,
      heading: "Your sign-in link",
      why: "Security emails always arrive.",
      blocks: [
        p(escapeHtml(greeting)),
        p("Here is your link to sign in to We Dig Creativity. Open it on the device you want to use."),
        action("Sign in to WDC", url),
        p("Signing in on a different device? Enter this code on the login page instead:"),
        `<p style="margin:0 0 20px;padding:16px 20px;background:${PAGE};border:1px solid ${HAIRLINE};border-radius:12px;` +
          `font-family:${DISPLAY};font-size:32px;font-weight:700;letter-spacing:.18em;color:${NAVY};text-align:center">${escapeHtml(spaced)}</p>`,
        p(`The link and the code each work once, for ${escapeHtml(life)}. Using either one cancels the other.`),
        small("If you did not ask to sign in, you can ignore this email. Nobody can get in without it."),
      ],
    }),
  };
}

/**
 * The code that confirms a new password, asked for from the account page.
 * No current password is asked there; this code, sent to the account's own
 * inbox, is what proves the change is theirs.
 */
export function passwordCodeEmail(input: { name?: string; code: string; expiresInMinutes: number }): Email {
  const { name, code, expiresInMinutes } = input;
  const greeting = name ? `Hi ${name},` : "Hello,";
  const spaced = `${code.slice(0, 3)} ${code.slice(3)}`;
  return {
    subject: `${spaced} is your code to change your password`,
    text: textShell(`${greeting}

Enter this code to confirm your new We Dig Creativity password. It works for ${expiresInMinutes} minutes:

${spaced}

If you did not ask to change your password, ignore this email and nothing changes. Someone may be signed in as you, so sign out your other devices from your account page.

The WDC team`),
    html: shell({
      title: "Confirm your new password",
      preheader: `Your code is ${spaced}. It works for ${expiresInMinutes} minutes.`,
      heading: "Confirm your new password",
      why: "Security emails always arrive.",
      blocks: [
        p(escapeHtml(greeting)),
        p("Enter this code on your account page to confirm your new password:"),
        `<p style="margin:0 0 20px;padding:16px 20px;background:${PAGE};border:1px solid ${HAIRLINE};border-radius:12px;` +
          `font-family:${DISPLAY};font-size:32px;font-weight:700;letter-spacing:.18em;color:${NAVY};text-align:center">${escapeHtml(spaced)}</p>`,
        p(`It works once, for ${expiresInMinutes} minutes.`),
        small("If you did not ask to change your password, ignore this email and nothing changes. Someone may be signed in as you, so sign out your other devices from your account page."),
      ],
    }),
  };
}

/* ================================================= 10b. an account, offered */

/**
 * The invitation to have an account: a client to their portal, or a member
 * of staff to the admin.
 *
 * IT SAYS WHICH ADDRESS THE ACCOUNT WILL BE, in words, because that is the
 * one thing the reader cannot change: the account is made for this inbox,
 * and a forwarded copy makes the same account, not a new one.
 *
 * No unsubscribe line: it is a single message somebody at the studio chose to
 * send, about access, not a list.
 */
export function accountInvitationEmail(input: {
  name?: string;
  email: string;
  url: string;
  role: "client" | "staff";
  invitedBy: string;
  expiresInDays: number;
}): Email {
  const { name, email, url, role, invitedBy, expiresInDays } = input;
  const greeting = name ? `Hi ${name},` : "Hello,";
  const life = `${expiresInDays} days`;
  const what = role === "staff"
    ? "an account on the We Dig Creativity studio admin"
    : "an account on your We Dig Creativity project portal, where you can follow your project, approve work and see your invoices";
  const optional = role === "client"
    ? "\n\nAn account is optional. Everything still reaches you by email and the channels we agreed; the portal is there if you want it."
    : "";
  return {
    subject: role === "staff" ? "Your We Dig Creativity team account" : "Your We Dig Creativity project portal",
    text: textShell(`${greeting}

${invitedBy} has set up ${what}.

Open this link to finish it. It works once, for ${life}:

${url}

The account will be for ${email}. You can choose a password, or continue
with Google if this address is a Google account.${optional}

If you were not expecting this, you can ignore it and nothing is created.

The WDC team`),
    html: shell({
      title: role === "staff" ? "Your team account" : "Your project portal",
      preheader: `Finish setting up your account for ${email}. The link works for ${life}.`,
      heading: role === "staff" ? "Your team account is ready" : "Your project portal is ready",
      blocks: [
        p(escapeHtml(greeting)),
        p(`${escapeHtml(invitedBy)} has set up ${escapeHtml(what)}.`),
        action("Finish setting up", url),
        p(`The account will be for <b>${escapeHtml(email)}</b>. You can choose a password, or continue with Google if this address is a Google account.`),
        ...(role === "client" ? [p("An account is optional. Everything still reaches you by email and the channels we agreed; the portal is there if you want it.")] : []),
        small(`The link works once, for ${escapeHtml(life)}. If you were not expecting this, you can ignore it and nothing is created.`),
      ],
    }),
  };
}

/* ========================================== 12. the site report, on request */

/**
 * The on-page report from /tools/seo, sent once the reader gives an address.
 *
 * IT IS SENT WHETHER OR NOT LIGHTHOUSE RAN. That is the whole shape of this
 * message and it comes from rule 1 of `docs/tools-programme.md`: the metered
 * half is an upgrade on an answer we can already give free, never the answer
 * itself. On a day the PageSpeed budget is spent, or on an installation with
 * no key at all, `scores` is empty and the mail carries the on-page findings
 * plus a line saying a person will run the rest. That is a better outcome for
 * the reader than an apology, and a better one for us than silence.
 */
export function siteReportEmail(input: {
  site: string;
  /** The on-page findings, already reduced to a label and a verdict. */
  findings: Array<{ label: string; detail: string }>;
  /** Lighthouse, where it ran. Empty means it did not, and the copy changes. */
  scores: Array<{ label: string; score: number }>;
  /** The biggest wins Lighthouse named, where it ran. */
  opportunities: string[];
  url: string;
}): Email {
  const { site, findings, scores, opportunities, url } = input;
  const ran = scores.length > 0;

  const scoreRows = scores.map((s) => [s.label, `${s.score} / 100`] as [string, string]);
  const findingRows = findings.map((f) => [f.label, f.detail] as [string, string]);

  const lighthouseText = ran
    ? `Lighthouse, run by Google on your live page:
${scoreRows.map(([label, value]) => `  - ${label}: ${value}`).join("\n")}

${opportunities.length ? `The biggest wins it found:\n${opportunities.map((o) => `  - ${o}`).join("\n")}` : "It found nothing large enough to be worth naming, which is rarer than you would think."}`
    : `The full Lighthouse run is queued rather than attached: we cap how many of
those we ask Google for in a day, and today's are spent. Somebody here will run
yours by hand and reply with it. Nothing above depends on it.`;

  return {
    subject: `Your site report: ${site}`,
    /* No unsubscribe, for the reason written on the estimate above: they asked
       for this one message, it is the thing they asked for, and nothing is
       added to any list. */
    text: textShell(`Hello,

Here is the report for ${site}, in full and in writing so you can forward it to
whoever looks after the site.

What we read off the page itself:
${findingRows.map(([label, detail]) => `  - ${label}: ${detail}`).join("\n")}

${lighthouseText}

Every one of these is fixable, and most of them are an afternoon rather than a
rebuild. Reply to this email if you would like us to do it, or to argue with any
of it.

${url}

The WDC team`),
    html: shell({
      title: "Your site report",
      preheader: `The on-page findings for ${site}${ran ? ", with Lighthouse scores" : ""}.`,
      heading: escapeHtml(site),
      blocks: [
        p("Here is the report in full, so you can forward it to whoever looks after the site."),
        p("<b>What we read off the page itself</b>"),
        panel(findingRows),
        ...(ran
          ? [
              p("<b>Lighthouse, run by Google on your live page</b>"),
              panel(scoreRows),
              ...(opportunities.length
                ? [small(`The biggest wins it found:<br>${opportunities.map((o) => `&bull; ${escapeHtml(o)}`).join("<br>")}`)]
                : [small("It found nothing large enough to be worth naming, which is rarer than you would think.")]),
            ]
          : [
              p("<b>The Lighthouse run is queued</b>"),
              small("We cap how many of those we ask Google for in a day, and today&rsquo;s are spent. Somebody here will run yours by hand and reply with it &mdash; nothing above depends on it."),
            ]),
        p("Every one of these is fixable, and most of them are an afternoon rather than a rebuild."),
        action("Ask us to fix them", url),
      ],
    }),
  };
}

/* ======================================== the frame, for mail built elsewhere */

/**
 * THE SAME FRAME FOR EVERY MESSAGE WE SEND, including the ones composed
 * outside this file: the money mail, the onboarding links, the newsletter
 * confirmation and the studio's own lead notifications. Each of those used
 * to hand-write a bare `<div>` with its own eyebrow and its own button, which
 * is how a receipt came to look like a different company from the sign-in
 * link. Build the body from these blocks and pass it to `composeEmailHtml`.
 */
export { shell as composeEmailHtml, p as emailP, small as emailSmall, action as emailButton, panel as emailPanel, figure as emailFigure };

/* ====================================================== maintenance: back */

/**
 * The one message a maintenance "notify me" sign-up asked for.
 *
 * NO UNSUBSCRIBE, and nothing to unsubscribe from: the address was given for
 * this message alone and is deleted once it is sent, which the message says.
 */
export function backOnlineEmail(): Email {
  const url = SITE_URL;
  return {
    subject: "We Dig Creativity is back online",
    text: textShell(`Hello,

You asked us to tell you when our site was back. It is:

${url}

This was the only message about it. We have deleted your address from
that list, so you will not hear from us again unless you get in touch.

The WDC team`),
    html: shell({
      title: "We are back online",
      preheader: "You asked us to tell you when the site was back. It is.",
      heading: "We are back online.",
      why: "You get this because you asked on our maintenance page to be told when the site was back. It was the only one.",
      blocks: [
        p("You asked us to tell you when our site was back. It is."),
        action("Visit the site", url),
        small("This was the only message about it. We have deleted your address from that list, so you will not hear from us again unless you get in touch."),
      ],
    }),
  };
}

/**
 * "Is this where the studio's notices should go?" -- sent to a NEW reply-to
 * address before it takes effect (lib/notice-address.ts). Studio notices
 * carry what clients wrote; an address nobody at the studio reads, or a typo,
 * would send them to a stranger, so the address proves itself first.
 */
export function noticeAddressEmail(input: { url: string; by: string; hours: number }): Email {
  const { url, by, hours } = input;
  return {
    subject: "Confirm this address for We Dig Creativity notices",
    text: textShell(`Hello,

${by} asked for the studio's notices (new enquiries, briefs, tickets and
payments) and clients' replies to come to this address. Nothing changes until
it is confirmed. If this is right, open this link within ${hours} hours:

${url}

If you do not know what this is, ignore it: nothing changes, and the notices
keep going where they go now.

The WDC team`),
    html: shell({
      title: "Confirm this address",
      preheader: `Nothing changes until this is confirmed. The link lasts ${hours} hours.`,
      heading: "Confirm this address",
      why: "Sent because this address was entered in the studio's email settings.",
      blocks: [
        p("Hello,"),
        p(`${escapeHtml(by)} asked for the studio's notices (new enquiries, briefs, tickets and payments) and clients' replies to come to this address. Nothing changes until it is confirmed.`),
        action("Confirm this address", url),
        p(`The link works once and lasts ${hours} hours.`),
        small("If you do not know what this is, ignore it: nothing changes, and the notices keep going where they go now."),
      ],
    }),
  };
}
