import {
  Activity, Airplay, AlarmClock, Album, Anchor, Aperture, AppWindow, Archive, Armchair, AtSign, Award, Axe, Baby, Backpack, BadgeCheck, BadgeDollarSign, BadgePercent, Banknote, BarChart, BarChart2, BarChart3, Bath, Battery, Beaker, Bed, Beer, Bell, Bike, Binary, Bird, Bitcoin, Blocks, Bluetooth, Bone, Book, BookOpen, BookText, Bookmark, Bot, Box, Boxes, Braces, Brain, Briefcase, Brush, Bug,  Building2, Bus, Cake, Calculator, Calendar, CalendarCheck, Camera, Candy, Car, Carrot, Cast, Castle, Cat, Check, CheckCircle, Cherry, Church, Circle, CircleDollarSign, Clapperboard, Clipboard, ClipboardCheck, Clock, Cloud, CloudLightning, CloudUpload, Club,  Code2, Coffee, Cog, Coins, Command, Compass, Component, Computer, ConciergeBell, Construction, Contact, Cookie, Copy, Copyright, Cpu, CreditCard, Croissant, Crop, Cross, Crown, Cuboid, CupSoda, Currency, Database, Diamond, Dices, Disc, Divide, Dog, DoorOpen, Download, Droplet, Drum, Dumbbell, Ear, Egg, Equal, Eraser, Euro, Factory, Fan, Feather, FileCode, FileText, Film, Filter, Fingerprint, Fish, Flag, Flame, Flashlight, FlaskConical, Flower, Folder, FolderKanban, Footprints, Forklift, Frame, Fuel, Gamepad2, Gauge, Gavel, Gem, Ghost, Gift, GitBranch, Glasses, Globe, Goal, GraduationCap, Grape, Grid, Grip, Hammer, Hand, HandHeart, Handshake, HardDrive, HardHat, Hash, Headphones, Heart, HeartHandshake, HeartPulse, Helicopter, Hexagon, Highlighter, History, Home, Hotel, Hourglass, IceCream, Image, Inbox, Infinity, Joystick, Key, Keyboard, Lamp, Landmark, Languages, Laptop, Layers, Layout, LayoutDashboard, LayoutGrid, Leaf, Library, LifeBuoy, Lightbulb, LineChart, Link, List, Loader, Locate, Lock, LogIn, Luggage, Magnet, Mail, Map, MapPin, Medal, Megaphone, Menu, MessageCircle, MessageSquare, MessagesSquare, Mic, Mic2, Microscope, Milk, Monitor, Moon, Mountain, MousePointer, Move, Music, Navigation, Network, Newspaper, Notebook, Nut, Octagon, Package, Paintbrush, Palette, PanelsTopLeft, Paperclip, PartyPopper, Pause, PenTool, Pencil, Percent, PersonStanding,  PhoneCall, PieChart, PiggyBank, Pill, Pin, Pizza, Plane, Play, Plug, Plus, Podcast, Popcorn, Presentation, Printer, Puzzle, QrCode, Quote, Radio, Rainbow, Receipt, Rocket, Rss, Ruler, Salad, Sandwich, Satellite, Save, Scale, Scan,  Scissors, ScreenShare, Scroll, Search, Send, Server, Settings, Shapes, Share2, Shield, ShieldCheck, Ship, Shirt, ShoppingBag, ShoppingCart, Shovel, Shrub, Signal, Siren, Slice, Smartphone, Smile, Snowflake, Sofa, Soup, Sparkles, Speaker, Speech, Sprout, Square, Squirrel, Stamp, Star, Stethoscope, Sticker, Store, Sun, Sunrise, Sword, Swords, Syringe, Table, Tablet, Tag, Target, Tent, Terminal, Thermometer, ThumbsUp, Ticket, Timer, Tornado, Tractor, TrafficCone, Train, Trash, Trees, TrendingUp, Triangle, Trophy, Truck, Tv, Umbrella, Undo, Unlock, Upload, Usb, User, UserPlus, Users, Utensils, Vegan, Verified, Video, Voicemail, Volume2, Wallet, Wand2, Warehouse, Watch, Waves, Webcam, Wheat, Wifi, Wind, Wine, Wrench, Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * THE ICONS A PROJECT CAN WEAR (the owner's ask: an icon per project, picked
 * or random, shown to the client too). A closed set, named, so the server can
 * refuse anything else and the portal draws the same one. `kw` holds everyday
 * words the name does not say (money finds banknote and wallet), which is what
 * the picker's search matches besides the name. The first block are the keys
 * saved before the set grew; they stay so no project loses its icon.
 */
export const PROJECT_ICONS: Record<string, { icon: LucideIcon; label: string; kw?: string }> = {
  palette: { icon: Palette, label: "Palette" },
  pen: { icon: PenTool, label: "Pen" },
  layers: { icon: Layers, label: "Layers" },
  gem: { icon: Gem, label: "Gem" },
  globe: { icon: Globe, label: "Globe" },
  code: { icon: Code2, label: "Code" },
  phone: { icon: Smartphone, label: "Phone" },
  cpu: { icon: Cpu, label: "Chip" },
  bot: { icon: Bot, label: "Bot" },
  search: { icon: Search, label: "Search" },
  chart: { icon: BarChart3, label: "Chart" },
  megaphone: { icon: Megaphone, label: "Megaphone" },
  rocket: { icon: Rocket, label: "Rocket" },
  trophy: { icon: Trophy, label: "Trophy" },
  camera: { icon: Camera, label: "Camera" },
  film: { icon: Film, label: "Film" },
  music: { icon: Music, label: "Music" },
  bag: { icon: ShoppingBag, label: "Shopping" },
  store: { icon: Store, label: "Shop" },
  box: { icon: Box, label: "Box" },
  briefcase: { icon: Briefcase, label: "Briefcase" },
  building: { icon: Building2, label: "Building" },
  home: { icon: Home, label: "Home" },
  school: { icon: GraduationCap, label: "School" },
  health: { icon: HeartPulse, label: "Health" },
  food: { icon: Utensils, label: "Food" },
  coffee: { icon: Coffee, label: "Coffee" },
  leaf: { icon: Leaf, label: "Leaf" },
  fashion: { icon: Shirt, label: "Fashion" },
  car: { icon: Car, label: "Car" },
  travel: { icon: Plane, label: "Travel" },
  "activity": { icon: Activity, label: "Activity" },
  "airplay": { icon: Airplay, label: "Airplay" },
  "alarm-clock": { icon: AlarmClock, label: "Alarm Clock" },
  "album": { icon: Album, label: "Album" },
  "anchor": { icon: Anchor, label: "Anchor" },
  "aperture": { icon: Aperture, label: "Aperture" },
  "app-window": { icon: AppWindow, label: "App Window" },
  "archive": { icon: Archive, label: "Archive" },
  "armchair": { icon: Armchair, label: "Armchair" },
  "at-sign": { icon: AtSign, label: "At Sign" },
  "award": { icon: Award, label: "Award", kw: "win prize" },
  "axe": { icon: Axe, label: "Axe" },
  "baby": { icon: Baby, label: "Baby", kw: "kids family" },
  "backpack": { icon: Backpack, label: "Backpack" },
  "badge-check": { icon: BadgeCheck, label: "Badge Check" },
  "badge-dollar-sign": { icon: BadgeDollarSign, label: "Badge Dollar Sign", kw: "money finance" },
  "badge-percent": { icon: BadgePercent, label: "Badge Percent", kw: "discount promo sale" },
  "banknote": { icon: Banknote, label: "Banknote", kw: "money cash naira pay" },
  "bar-chart": { icon: BarChart, label: "Bar Chart", kw: "analytics report data" },
  "bar-chart-2": { icon: BarChart2, label: "Bar Chart 2" },
  "bar-chart-3": { icon: BarChart3, label: "Bar Chart 3" },
  "bath": { icon: Bath, label: "Bath" },
  "battery": { icon: Battery, label: "Battery", kw: "power energy" },
  "beaker": { icon: Beaker, label: "Beaker" },
  "bed": { icon: Bed, label: "Bed" },
  "beer": { icon: Beer, label: "Beer", kw: "drink bar" },
  "bell": { icon: Bell, label: "Bell" },
  "bike": { icon: Bike, label: "Bike", kw: "transport sport" },
  "binary": { icon: Binary, label: "Binary" },
  "bird": { icon: Bird, label: "Bird" },
  "bitcoin": { icon: Bitcoin, label: "Bitcoin", kw: "crypto money" },
  "blocks": { icon: Blocks, label: "Blocks" },
  "bluetooth": { icon: Bluetooth, label: "Bluetooth" },
  "bone": { icon: Bone, label: "Bone" },
  "book": { icon: Book, label: "Book" },
  "book-open": { icon: BookOpen, label: "Book Open", kw: "education reading course" },
  "book-text": { icon: BookText, label: "Book Text" },
  "bookmark": { icon: Bookmark, label: "Bookmark" },
  "boxes": { icon: Boxes, label: "Boxes" },
  "braces": { icon: Braces, label: "Braces" },
  "brain": { icon: Brain, label: "Brain", kw: "ai idea think" },
  "brush": { icon: Brush, label: "Brush", kw: "design art paint" },
  "bug": { icon: Bug, label: "Bug" },
  "building-2": { icon: Building2, label: "Building 2" },
  "bus": { icon: Bus, label: "Bus", kw: "transport travel" },
  "cake": { icon: Cake, label: "Cake", kw: "food bakery party" },
  "calculator": { icon: Calculator, label: "Calculator", kw: "accounting finance maths" },
  "calendar": { icon: Calendar, label: "Calendar", kw: "date event schedule" },
  "calendar-check": { icon: CalendarCheck, label: "Calendar Check" },
  "candy": { icon: Candy, label: "Candy" },
  "carrot": { icon: Carrot, label: "Carrot" },
  "cast": { icon: Cast, label: "Cast" },
  "castle": { icon: Castle, label: "Castle" },
  "cat": { icon: Cat, label: "Cat", kw: "pet animal" },
  "check": { icon: Check, label: "Check" },
  "check-circle": { icon: CheckCircle, label: "Check Circle" },
  "cherry": { icon: Cherry, label: "Cherry" },
  "church": { icon: Church, label: "Church", kw: "faith religion" },
  "circle": { icon: Circle, label: "Circle" },
  "circle-dollar-sign": { icon: CircleDollarSign, label: "Circle Dollar Sign", kw: "money finance" },
  "clapperboard": { icon: Clapperboard, label: "Clapperboard", kw: "video film media" },
  "clipboard": { icon: Clipboard, label: "Clipboard" },
  "clipboard-check": { icon: ClipboardCheck, label: "Clipboard Check", kw: "checklist task" },
  "clock": { icon: Clock, label: "Clock", kw: "time" },
  "cloud": { icon: Cloud, label: "Cloud", kw: "hosting storage" },
  "cloud-lightning": { icon: CloudLightning, label: "Cloud Lightning" },
  "cloud-upload": { icon: CloudUpload, label: "Cloud Upload" },
  "club": { icon: Club, label: "Club" },
  "code-2": { icon: Code2, label: "Code 2" },
  "cog": { icon: Cog, label: "Cog" },
  "coins": { icon: Coins, label: "Coins", kw: "money cash pay" },
  "command": { icon: Command, label: "Command" },
  "compass": { icon: Compass, label: "Compass", kw: "travel direction" },
  "component": { icon: Component, label: "Component" },
  "computer": { icon: Computer, label: "Computer" },
  "concierge-bell": { icon: ConciergeBell, label: "Concierge Bell" },
  "construction": { icon: Construction, label: "Construction", kw: "building site" },
  "contact": { icon: Contact, label: "Contact" },
  "cookie": { icon: Cookie, label: "Cookie" },
  "copy": { icon: Copy, label: "Copy" },
  "copyright": { icon: Copyright, label: "Copyright" },
  "credit-card": { icon: CreditCard, label: "Credit Card", kw: "money pay card payment" },
  "croissant": { icon: Croissant, label: "Croissant" },
  "crop": { icon: Crop, label: "Crop" },
  "cross": { icon: Cross, label: "Cross" },
  "crown": { icon: Crown, label: "Crown", kw: "premium brand royal" },
  "cuboid": { icon: Cuboid, label: "Cuboid" },
  "cup-soda": { icon: CupSoda, label: "Cup Soda" },
  "currency": { icon: Currency, label: "Currency" },
  "database": { icon: Database, label: "Database", kw: "data storage" },
  "diamond": { icon: Diamond, label: "Diamond" },
  "dices": { icon: Dices, label: "Dices", kw: "game" },
  "disc": { icon: Disc, label: "Disc" },
  "divide": { icon: Divide, label: "Divide" },
  "dog": { icon: Dog, label: "Dog", kw: "pet animal" },
  "door-open": { icon: DoorOpen, label: "Door Open" },
  "download": { icon: Download, label: "Download" },
  "droplet": { icon: Droplet, label: "Droplet" },
  "drum": { icon: Drum, label: "Drum" },
  "dumbbell": { icon: Dumbbell, label: "Dumbbell", kw: "fitness gym sport" },
  "ear": { icon: Ear, label: "Ear" },
  "egg": { icon: Egg, label: "Egg" },
  "equal": { icon: Equal, label: "Equal" },
  "eraser": { icon: Eraser, label: "Eraser" },
  "euro": { icon: Euro, label: "Euro", kw: "money currency" },
  "factory": { icon: Factory, label: "Factory", kw: "manufacturing industry" },
  "fan": { icon: Fan, label: "Fan" },
  "feather": { icon: Feather, label: "Feather" },
  "file-code": { icon: FileCode, label: "File Code" },
  "file-text": { icon: FileText, label: "File Text" },
  "filter": { icon: Filter, label: "Filter" },
  "fingerprint": { icon: Fingerprint, label: "Fingerprint", kw: "security identity" },
  "fish": { icon: Fish, label: "Fish", kw: "pet food animal" },
  "flag": { icon: Flag, label: "Flag" },
  "flame": { icon: Flame, label: "Flame" },
  "flashlight": { icon: Flashlight, label: "Flashlight" },
  "flask-conical": { icon: FlaskConical, label: "Flask Conical" },
  "flower": { icon: Flower, label: "Flower", kw: "nature beauty wedding" },
  "folder": { icon: Folder, label: "Folder" },
  "folder-kanban": { icon: FolderKanban, label: "Folder Kanban" },
  "footprints": { icon: Footprints, label: "Footprints" },
  "forklift": { icon: Forklift, label: "Forklift" },
  "frame": { icon: Frame, label: "Frame" },
  "fuel": { icon: Fuel, label: "Fuel", kw: "energy petrol" },
  "gamepad-2": { icon: Gamepad2, label: "Gamepad 2", kw: "game gaming" },
  "gauge": { icon: Gauge, label: "Gauge" },
  "gavel": { icon: Gavel, label: "Gavel", kw: "legal law court" },
  "ghost": { icon: Ghost, label: "Ghost" },
  "gift": { icon: Gift, label: "Gift", kw: "promo present" },
  "git-branch": { icon: GitBranch, label: "Git Branch" },
  "glasses": { icon: Glasses, label: "Glasses" },
  "goal": { icon: Goal, label: "Goal" },
  "graduation-cap": { icon: GraduationCap, label: "Graduation Cap", kw: "school education course training" },
  "grape": { icon: Grape, label: "Grape" },
  "grid": { icon: Grid, label: "Grid" },
  "grip": { icon: Grip, label: "Grip" },
  "hammer": { icon: Hammer, label: "Hammer", kw: "build tools repair" },
  "hand": { icon: Hand, label: "Hand" },
  "hand-heart": { icon: HandHeart, label: "Hand Heart" },
  "handshake": { icon: Handshake, label: "Handshake", kw: "deal partnership" },
  "hard-drive": { icon: HardDrive, label: "Hard Drive", kw: "storage data" },
  "hard-hat": { icon: HardHat, label: "Hard Hat", kw: "construction engineering" },
  "hash": { icon: Hash, label: "Hash", kw: "social tag" },
  "headphones": { icon: Headphones, label: "Headphones", kw: "audio music sound" },
  "heart": { icon: Heart, label: "Heart" },
  "heart-handshake": { icon: HeartHandshake, label: "Heart Handshake", kw: "partnership charity" },
  "heart-pulse": { icon: HeartPulse, label: "Heart Pulse", kw: "health medical" },
  "helicopter": { icon: Helicopter, label: "Helicopter" },
  "hexagon": { icon: Hexagon, label: "Hexagon" },
  "highlighter": { icon: Highlighter, label: "Highlighter" },
  "history": { icon: History, label: "History" },
  "hotel": { icon: Hotel, label: "Hotel", kw: "travel stay property" },
  "hourglass": { icon: Hourglass, label: "Hourglass", kw: "time wait" },
  "ice-cream": { icon: IceCream, label: "Ice Cream" },
  "image": { icon: Image, label: "Image", kw: "photo picture" },
  "inbox": { icon: Inbox, label: "Inbox" },
  "infinity": { icon: Infinity, label: "Infinity" },
  "joystick": { icon: Joystick, label: "Joystick" },
  "key": { icon: Key, label: "Key", kw: "security access" },
  "keyboard": { icon: Keyboard, label: "Keyboard" },
  "lamp": { icon: Lamp, label: "Lamp" },
  "landmark": { icon: Landmark, label: "Landmark", kw: "bank money law" },
  "languages": { icon: Languages, label: "Languages" },
  "laptop": { icon: Laptop, label: "Laptop" },
  "layout": { icon: Layout, label: "Layout" },
  "layout-dashboard": { icon: LayoutDashboard, label: "Layout Dashboard", kw: "web dashboard app" },
  "layout-grid": { icon: LayoutGrid, label: "Layout Grid" },
  "library": { icon: Library, label: "Library" },
  "life-buoy": { icon: LifeBuoy, label: "Life Buoy" },
  "lightbulb": { icon: Lightbulb, label: "Lightbulb", kw: "idea creative" },
  "line-chart": { icon: LineChart, label: "Line Chart", kw: "analytics report data" },
  "link": { icon: Link, label: "Link" },
  "list": { icon: List, label: "List" },
  "loader": { icon: Loader, label: "Loader" },
  "locate": { icon: Locate, label: "Locate" },
  "lock": { icon: Lock, label: "Lock", kw: "security private" },
  "log-in": { icon: LogIn, label: "Log In" },
  "luggage": { icon: Luggage, label: "Luggage", kw: "travel trip" },
  "magnet": { icon: Magnet, label: "Magnet" },
  "mail": { icon: Mail, label: "Mail", kw: "email message inbox" },
  "map": { icon: Map, label: "Map", kw: "travel location" },
  "map-pin": { icon: MapPin, label: "Map Pin", kw: "location place" },
  "medal": { icon: Medal, label: "Medal", kw: "win award" },
  "menu": { icon: Menu, label: "Menu" },
  "message-circle": { icon: MessageCircle, label: "Message Circle", kw: "chat" },
  "message-square": { icon: MessageSquare, label: "Message Square", kw: "chat" },
  "messages-square": { icon: MessagesSquare, label: "Messages Square", kw: "chat" },
  "mic": { icon: Mic, label: "Mic", kw: "audio podcast voice" },
  "mic-2": { icon: Mic2, label: "Mic 2" },
  "microscope": { icon: Microscope, label: "Microscope" },
  "milk": { icon: Milk, label: "Milk" },
  "monitor": { icon: Monitor, label: "Monitor", kw: "web website screen computer" },
  "moon": { icon: Moon, label: "Moon" },
  "mountain": { icon: Mountain, label: "Mountain", kw: "outdoors travel" },
  "mouse-pointer": { icon: MousePointer, label: "Mouse Pointer" },
  "move": { icon: Move, label: "Move" },
  "navigation": { icon: Navigation, label: "Navigation" },
  "network": { icon: Network, label: "Network" },
  "newspaper": { icon: Newspaper, label: "Newspaper", kw: "news blog press" },
  "notebook": { icon: Notebook, label: "Notebook" },
  "nut": { icon: Nut, label: "Nut" },
  "octagon": { icon: Octagon, label: "Octagon" },
  "package": { icon: Package, label: "Package" },
  "paintbrush": { icon: Paintbrush, label: "Paintbrush", kw: "design art paint" },
  "panels-top-left": { icon: PanelsTopLeft, label: "Panels Top Left" },
  "paperclip": { icon: Paperclip, label: "Paperclip" },
  "party-popper": { icon: PartyPopper, label: "Party Popper", kw: "event celebrate launch" },
  "pause": { icon: Pause, label: "Pause" },
  "pen-tool": { icon: PenTool, label: "Pen Tool", kw: "design logo brand vector" },
  "pencil": { icon: Pencil, label: "Pencil" },
  "percent": { icon: Percent, label: "Percent" },
  "person-standing": { icon: PersonStanding, label: "Person Standing" },
  "phone-call": { icon: PhoneCall, label: "Phone Call" },
  "pie-chart": { icon: PieChart, label: "Pie Chart", kw: "analytics report data" },
  "piggy-bank": { icon: PiggyBank, label: "Piggy Bank", kw: "money savings" },
  "pill": { icon: Pill, label: "Pill", kw: "health medical pharmacy" },
  "pin": { icon: Pin, label: "Pin" },
  "pizza": { icon: Pizza, label: "Pizza", kw: "food restaurant" },
  "plane": { icon: Plane, label: "Plane", kw: "travel flight airline" },
  "play": { icon: Play, label: "Play" },
  "plug": { icon: Plug, label: "Plug", kw: "power energy electric" },
  "plus": { icon: Plus, label: "Plus" },
  "podcast": { icon: Podcast, label: "Podcast" },
  "popcorn": { icon: Popcorn, label: "Popcorn" },
  "presentation": { icon: Presentation, label: "Presentation", kw: "slides pitch deck" },
  "printer": { icon: Printer, label: "Printer", kw: "office print" },
  "puzzle": { icon: Puzzle, label: "Puzzle", kw: "game plugin" },
  "qr-code": { icon: QrCode, label: "Qr Code" },
  "quote": { icon: Quote, label: "Quote" },
  "radio": { icon: Radio, label: "Radio" },
  "rainbow": { icon: Rainbow, label: "Rainbow" },
  "receipt": { icon: Receipt, label: "Receipt", kw: "invoice money bill" },
  "rss": { icon: Rss, label: "Rss", kw: "blog feed news" },
  "ruler": { icon: Ruler, label: "Ruler" },
  "salad": { icon: Salad, label: "Salad", kw: "food healthy" },
  "sandwich": { icon: Sandwich, label: "Sandwich" },
  "satellite": { icon: Satellite, label: "Satellite", kw: "space internet" },
  "save": { icon: Save, label: "Save" },
  "scale": { icon: Scale, label: "Scale", kw: "legal law justice" },
  "scan": { icon: Scan, label: "Scan" },
  "scissors": { icon: Scissors, label: "Scissors", kw: "fashion salon cut" },
  "screen-share": { icon: ScreenShare, label: "Screen Share" },
  "scroll": { icon: Scroll, label: "Scroll" },
  "send": { icon: Send, label: "Send" },
  "server": { icon: Server, label: "Server", kw: "data hosting" },
  "settings": { icon: Settings, label: "Settings" },
  "shapes": { icon: Shapes, label: "Shapes" },
  "share-2": { icon: Share2, label: "Share 2", kw: "social share" },
  "shield": { icon: Shield, label: "Shield", kw: "security safe protect" },
  "shield-check": { icon: ShieldCheck, label: "Shield Check", kw: "security safe protect" },
  "ship": { icon: Ship, label: "Ship", kw: "shipping travel boat" },
  "shirt": { icon: Shirt, label: "Shirt", kw: "fashion clothes" },
  "shopping-bag": { icon: ShoppingBag, label: "Shopping Bag", kw: "shop ecommerce store buy" },
  "shopping-cart": { icon: ShoppingCart, label: "Shopping Cart", kw: "shop ecommerce store buy" },
  "shovel": { icon: Shovel, label: "Shovel" },
  "shrub": { icon: Shrub, label: "Shrub" },
  "signal": { icon: Signal, label: "Signal" },
  "siren": { icon: Siren, label: "Siren" },
  "slice": { icon: Slice, label: "Slice" },
  "smartphone": { icon: Smartphone, label: "Smartphone", kw: "phone mobile app" },
  "smile": { icon: Smile, label: "Smile" },
  "snowflake": { icon: Snowflake, label: "Snowflake" },
  "sofa": { icon: Sofa, label: "Sofa" },
  "soup": { icon: Soup, label: "Soup" },
  "sparkles": { icon: Sparkles, label: "Sparkles", kw: "idea magic ai new" },
  "speaker": { icon: Speaker, label: "Speaker" },
  "speech": { icon: Speech, label: "Speech" },
  "sprout": { icon: Sprout, label: "Sprout", kw: "growth farm eco" },
  "square": { icon: Square, label: "Square" },
  "squirrel": { icon: Squirrel, label: "Squirrel" },
  "stamp": { icon: Stamp, label: "Stamp" },
  "star": { icon: Star, label: "Star" },
  "stethoscope": { icon: Stethoscope, label: "Stethoscope", kw: "health medical doctor" },
  "sticker": { icon: Sticker, label: "Sticker" },
  "sun": { icon: Sun, label: "Sun", kw: "weather energy solar" },
  "sunrise": { icon: Sunrise, label: "Sunrise" },
  "sword": { icon: Sword, label: "Sword" },
  "swords": { icon: Swords, label: "Swords" },
  "syringe": { icon: Syringe, label: "Syringe" },
  "table": { icon: Table, label: "Table" },
  "tablet": { icon: Tablet, label: "Tablet" },
  "tag": { icon: Tag, label: "Tag" },
  "target": { icon: Target, label: "Target", kw: "goal marketing aim" },
  "tent": { icon: Tent, label: "Tent", kw: "camping outdoors" },
  "terminal": { icon: Terminal, label: "Terminal", kw: "developer code software" },
  "thermometer": { icon: Thermometer, label: "Thermometer" },
  "thumbs-up": { icon: ThumbsUp, label: "Thumbs Up", kw: "social like" },
  "ticket": { icon: Ticket, label: "Ticket", kw: "event entry" },
  "timer": { icon: Timer, label: "Timer", kw: "time" },
  "tornado": { icon: Tornado, label: "Tornado" },
  "tractor": { icon: Tractor, label: "Tractor", kw: "farm agriculture" },
  "traffic-cone": { icon: TrafficCone, label: "Traffic Cone" },
  "train": { icon: Train, label: "Train", kw: "transport travel" },
  "trash": { icon: Trash, label: "Trash" },
  "trees": { icon: Trees, label: "Trees" },
  "trending-up": { icon: TrendingUp, label: "Trending Up", kw: "growth sales analytics" },
  "triangle": { icon: Triangle, label: "Triangle" },
  "truck": { icon: Truck, label: "Truck", kw: "delivery logistics transport" },
  "tv": { icon: Tv, label: "Tv" },
  "umbrella": { icon: Umbrella, label: "Umbrella" },
  "undo": { icon: Undo, label: "Undo" },
  "unlock": { icon: Unlock, label: "Unlock" },
  "upload": { icon: Upload, label: "Upload" },
  "usb": { icon: Usb, label: "Usb" },
  "user": { icon: User, label: "User", kw: "person profile" },
  "user-plus": { icon: UserPlus, label: "User Plus" },
  "users": { icon: Users, label: "Users", kw: "people team group" },
  "utensils": { icon: Utensils, label: "Utensils", kw: "food restaurant eat" },
  "vegan": { icon: Vegan, label: "Vegan" },
  "verified": { icon: Verified, label: "Verified" },
  "video": { icon: Video, label: "Video", kw: "film media" },
  "voicemail": { icon: Voicemail, label: "Voicemail" },
  "volume-2": { icon: Volume2, label: "Volume 2" },
  "wallet": { icon: Wallet, label: "Wallet", kw: "money pay cash" },
  "wand-2": { icon: Wand2, label: "Wand 2" },
  "warehouse": { icon: Warehouse, label: "Warehouse", kw: "storage logistics stock" },
  "watch": { icon: Watch, label: "Watch" },
  "waves": { icon: Waves, label: "Waves" },
  "webcam": { icon: Webcam, label: "Webcam" },
  "wheat": { icon: Wheat, label: "Wheat", kw: "farm agriculture" },
  "wifi": { icon: Wifi, label: "Wifi", kw: "internet network" },
  "wind": { icon: Wind, label: "Wind" },
  "wine": { icon: Wine, label: "Wine", kw: "drink bar restaurant" },
  "wrench": { icon: Wrench, label: "Wrench", kw: "build tools repair" },
  "zap": { icon: Zap, label: "Zap", kw: "power energy electric fast" },
};

export const PROJECT_ICON_NAMES = Object.keys(PROJECT_ICONS);

export function isProjectIcon(v: unknown): v is string {
  return typeof v === "string" && Object.hasOwn(PROJECT_ICONS, v);
}

export function randomProjectIcon(): string {
  return PROJECT_ICON_NAMES[Math.floor(Math.random() * PROJECT_ICON_NAMES.length)];
}

/** The icon to draw for a project: its own, else the folder. */
export function projectIconOf(name: string | undefined): LucideIcon {
  return (name && PROJECT_ICONS[name]?.icon) || FolderKanban;
}
